### ISSUE TITLE
hero-description shows page content while excerpt is empty

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#1]
Demo: https://calvintam.dev/bio/

It should not show anything when excerpt is empty.

**Comment by eddiesigner** [comment]
@calvintam236 Thank you for the heads up! It's already fixed in the latest version:

https://github.com/eddiesigner/liebling/releases/tag/v.0.1.1

**Comment by calvintam236** [comment]
Fix confirmed. Thanks.
