### ISSUE TITLE
JavaScript source files

### ISSUE THREAD

**Issue by Aareksio** [eddiesigner/liebling#10]
Hey,

could you please publish the source of javascript files included in the theme?

**Comment by eddiesigner** [comment]
@Aareksio I published the source code in [this gist](https://gist.github.com/eddiesigner/6f8745b84c2080c7f96c8a02d64209f4) because I don't want to have that code as it is in the theme due performance reasons.

**Comment by Aareksio** [comment]
@eddiesigner 
Please consider placing the code on git, eg. in `src` directory. It will allow people to comment and contribute to it, as well as make the project more trustworthy - I want to know what code is shipped to my users.

**Comment by eddiesigner** [comment]
@Aareksio You're right, I just added the source files to the repo and deleted that gist, now people can see the javascript and sass files if they want to.
