### ISSUE TITLE
Can't activated theme

### ISSUE THREAD

**Issue by naufdotal** [eddiesigner/liebling#105]
Hi,
this theme is awesome, but i got the following errors during the theme compatility checking for Ghost Version 3.1.1:

> Activation successful with errors
> Errors
> Highly recommended to fix, functionality could be restricted
> 
>     The .kg-width-wide CSS class is required to appear styled in your theme
>     The .kg-width-full CSS class is required to appear styled in your theme
>     The .kg-gallery-container CSS class is required to appear styled in your theme
>     The .kg-gallery-row CSS class is required to appear styled in your theme
>     The .kg-gallery-image CSS class is required to appear styled in your theme
>     The .kg-bookmark-card CSS class is required to appear styled in your theme
>     The .kg-bookmark-container CSS class is required to appear styled in your theme
>     The .kg-bookmark-content CSS class is required to appear styled in your theme
>     The .kg-bookmark-title CSS class is required to appear styled in your theme
>     The .kg-bookmark-description CSS class is required to appear styled in your theme
>     The .kg-bookmark-metadata CSS class is required to appear styled in your theme
>     The .kg-bookmark-icon CSS class is required to appear styled in your theme
>     The .kg-bookmark-author CSS class is required to appear styled in your theme
>     The .kg-bookmark-publisher CSS class is required to appear styled in your theme
>     The .kg-bookmark-thumbnail CSS class is required to appear styled in your theme

**Comment by eddiesigner** [comment]
It seems like you have an old version of this theme, the styles for those classes are included, please download the latest version from the [releases page](https://github.com/eddiesigner/liebling/releases).
