### ISSUE TITLE
Social Media Icons not working

### ISSUE THREAD

**Issue by RealCodeTips** [eddiesigner/liebling#109]
Is there something specific needed to get the social media icons working? I cloned the repo and ran `npm run production`, then uploaded the zip file but the social media icons aren't working.

![image](https://user-images.githubusercontent.com/49099061/71010252-78870100-20e3-11ea-8f55-7ede64ce8b52.png)

The CSS appears to have the proper `content` value

![image](https://user-images.githubusercontent.com/49099061/71010467-cc91e580-20e3-11ea-944f-5038582bf71b.png)

When I download the zip from the Release page, everything works fine, but there are a couple modifications I want to do so interested how to get this working when working from source?

**Comment by RealCodeTips** [comment]
Figured it out - it's because the `fonts` directory/files didn't exist in the `assets` directory. As soon as I moved them across from the `src/sass/fonts/icomoon` directory and recompiled, it all worked fine. 

Not sure if there's a bug in the webpack config or something?

**Comment by eddiesigner** [comment]
Thanks for the heads up! I already fixed it with this commit https://github.com/eddiesigner/liebling/commit/8ff20eb5285728602c0079d8735811516d70da3b
