### ISSUE TITLE
post - author section background color for sites without subscribe

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#11]
Demos:
https://calvintam.dev/past-present/
https://liebling.eduardogomez.io/how-to-set-intentions-that-energize-you/

For me, I am not using subscribe for email feature. There is no background color differences between post, `m-author` and `m-recommended`. It is just plain white, making the overall layout weird.

Can you also fix the padding for no posts found? Looks like not styled (excessive empty space there).

PS: `m-recommended` has no padding/margin top at `<section></section>` tag. Is it intentional?

**Comment by eddiesigner** [comment]
I fixed the issue when you are not using the subscribers feature, now the sections are more well defined.

I removed extra space at the bottom of the message "No posts found".

I also added padding at the top of the `m-recommended` section.

**Comment by calvintam236** [comment]
It looks better now. Thanks @eddiesigner
