### ISSUE TITLE
Open External Links in a new tab (by default)

### ISSUE THREAD

**Issue by youngpilot** [eddiesigner/liebling#110]
Hi Eddie,

thanks for your great Ghost theme! I love it! Right now I'm starting to configure it to my needs. One of my needs is that all external links open in a new tab. Using html syntax is not a solution for me, because I need this functionality also in menus. Further i need it often and would love it to be implemented into the theme.

Can you help me implement this feature?

**Comment by MattchZA** [comment]
Hey @youngpilot this might be a good work around?

https://forum.ghost.org/t/open-links-in-new-window/1726/3

**Comment by youngpilot** [comment]
Thanks for your suggestion! I tried the solution from @mantebridts from this thread, but wasn't able to get it to work.

**Comment by MattchZA** [comment]
@youngpilot after I sent this to you I tested it myself on liebling and couldn't get it to work. There must be some JS blocking the function. I have it working fine on Casper theme. Very strange.

**Comment by eddiesigner** [comment]
@youngpilot You can implement this feature by injecting the following code into the **Code injection** page of your Ghost instance (**Site Footer** section):

```html
<script>
  const anchors = document.querySelectorAll('a');
    
  for (x = 0, l = anchors.length; x < l; x++) {
    const regex = new RegExp('/' + window.location.host + '/');
        
    if (!regex.test(anchors[x].href)) {
      anchors[x].setAttribute('target', '_blank');
    }
  }
</script>
```

The solution provided by @MattchZA doesn't work because it uses jQuery which is loaded after your code snippet.

**Comment by youngpilot** [comment]
That's it! Thank you much @eddiesigner and @MattchZA for your help!
