### ISSUE TITLE
Smaller / configurable footer

### ISSUE THREAD

**Issue by diwakergupta** [eddiesigner/liebling#111]
Is there an easy way to make the footer more compact, or align things side-by-side (vs. vertically) like in the footer in the Casper theme? Would prefer to avoid having to modify the hbs files if possible and my CSS-foo isn't as strong. Thanks for the great theme!

**Comment by eddiesigner** [comment]
You can paste the following code into the the _Site Header Code injection_ section of your Ghost instance:

```html
<style>
@media only screen and (min-width:48rem) {
  .m-footer__content {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 35px 0;
  }

  .m-footer-copyright {
    margin-right: 50px;
    margin-bottom: 0;
  }

  .m-footer-social {
    margin-bottom: 0;
  }

  .m-footer-copyright.jslicense {
    margin-left: 50px;
    margin-bottom: 0;
  }
}
</style>
```

This code will make the footer more compact and align things side-by-side but centered in relation to their container. Sadly if you want to have one part on the left side and another part on the right side then the layout has to be changed and that's outside the scope of this issue.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
