### ISSUE TITLE
Issues with html elements

### ISSUE THREAD

**Issue by makeitcount** [eddiesigner/liebling#113]
HTML code inside post does not work well. Weird behavior, text overlap and things. Tried both inserting html in markdown as well as a separate html block.

**Comment by eddiesigner** [comment]
I just tested it and custom HTML content inside posts works well (with Markdown too).

Could you provide a screenshot or a page link so I can see it?

**Comment by makeitcount** [comment]
Allow me some time to get back to you. It was some html I wrote and had separate css and javascript injected via `code injection` feature "for individual posts" in ghost.

**Comment by makeitcount** [comment]
I thing this is fine. I checked again. 
Although after uploading the theme, it messed up the posts which had html content 
**BUT** when I copied the post content to clipboard and pasted again, it worked fine. 

Only few tiny issues were there such as text alignment for `span` elements was seen to be left-aligned when I defined it to be center. Which I think is not an issue, just creating a parent div with alignment styles fixed it.
