### ISSUE TITLE
European Date Format

### ISSUE THREAD

**Issue by youngpilot** [eddiesigner/liebling#114]
Hi Eddie,
I'm using liebling with the 'de-informal' translation. Unfortunately the translation doesn't change the date format on the published posts. It is still displayed in the american way: Jan. 04, 2020
I'd love to have the option to display it in the european/german format fully written out: 4. Januar 2020

Can you help me make this change?
Thanks,
Julian

**Comment by D3473R** [comment]
Hi, 
sadly there is no way yet in ghostjs to load the date format from the locale or a setting in the ui.
You can modify the `post.hbs` from `{{date published_at}}` to `{{date published_at format="DD. MMMM YYYY"}}` to display the post dates in the german date format.
```
λ git diff
diff --git a/post.hbs b/post.hbs
index 4857610..c57b61b 100644
--- a/post.hbs
+++ b/post.hbs
@@ -34,7 +34,7 @@ into the {body} of the default.hbs template --}}
                 <a href="{{primary_tag.url}}" class="m-heading__meta__tag">{{primary_tag.name}}</a>
                 <span class="m-heading__meta__divider">&bull;</span>
                 {{/if}}
-                <span class="m-heading__meta__time">{{date published_at}}</span>
+                <span class="m-heading__meta__time">{{date published_at format="DD. MMMM YYYY"}}</span>
               </div>
             </header>
             <div class="pos-relative js-post-content">
```

**Comment by youngpilot** [comment]
Thanks, that did the trick :)
