### ISSUE TITLE
Website not displaying properly 

### ISSUE THREAD

**Issue by nomadtechiemike** [eddiesigner/liebling#115]
Just downloaded the zip file added new theme after activating it my site looks a mess - this is on a clean install https://prnt.sc/qjhm9u

**Comment by DanHakimi** [comment]
You can't just download the repository -- the readme tells you where to download the theme zips from. Go there.

**Comment by D3473R** [comment]
> You can't just download the repository -- the readme tells you where to download the theme zips from. Go there.

This is the latest one: https://github.com/eddiesigner/liebling/releases/download/v.0.6.3/liebling.zip
