### ISSUE TITLE
Sharing Link Doesn't Work via Buster

### ISSUE THREAD

**Issue by DanHakimi** [eddiesigner/liebling#116]
I assume Buster compatibility is not a priority for theme development, but the links currently used to share to twitter/facebook are based on the localhost, url. That's pretty bad. Is there a straightforward way to correct this, or, if not, remove those icons so that people don't try to share invalid URLs?

**Comment by DanHakimi** [comment]
I've fixed the issue for my case -- I replaced the {{url absolute='true'}} line in post.hbs with my actual blog's proper hosted URL followed by {{url}} (the relative URL). I suppose, in the worst case, that buster users can do this in each case, but if there's a solution that works out of the box, that'd be good.

**Comment by eddiesigner** [comment]
I don't think this is a real issue, the only way `{{url absolute='true'}}` returns `localhost` is if you're running Ghost on your local computer which is fine. If you run Ghost on your server then `{{url absolute='true'}}` will return your proper domain url.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
