### ISSUE TITLE
Hide the hero image on selected pages

### ISSUE THREAD

**Issue by youngpilot** [eddiesigner/liebling#119]
I want to hide the hero image section on selected pages. For example on [this page](https://iosapps.de/empfehlen/), in order to save the space needed for the hero image atm.

Is there an easy way to implement this without affecting all pages?

**Comment by D3473R** [comment]
The easiest way for this is to create a seperate hbs file for this page.
In your example the url path is `empfehlen`. So you would create a `page-empfehlen.hbs` file with the following content:
```
{{!< default}}

{{!-- Everything inside the #post tags pulls data from the post --}}
{{#post}}
  <div class="main-wrap">
    {{!-- Special header.hbs partial to generate the <header> tag --}}
    {{> header}}
    <main style="padding-top: 75px;">
      <article>
        <div class="l-content">
          <div class="l-wrapper in-post" data-aos="fade-up" data-aos-delay="300">
            <div class="l-post-content">
              <div class="pos-relative js-post-content">
                {{content}}
              </div>
            </div>
          </div>
        </div>
      </article>
    </main>
  </div>
{{/post}}

{{!-- The #contentFor helper here will send everything inside it up to the matching #block helper found in default.hbs --}}
{{#contentFor "scripts"}}
  <script defer src="{{asset "js/page.js"}}"></script>
{{/contentFor}}
```

The `style="padding-top: 75px;";` is just an arbitrary padding to the top, you can use what you want.

**Comment by youngpilot** [comment]
Wow – perfect. Thank you so much!
