### ISSUE TITLE
Search is not appearing

### ISSUE THREAD

**Issue by veshitala** [eddiesigner/liebling#12]
When i am uploading this theme search  bar is not showing , what am i missing

**Comment by veshitala** [comment]
you can see demo here .

https://www.datadiscuss.com

**Comment by eddiesigner** [comment]
@veshitala Hi! To enable the search feature you have to follow these steps:

https://github.com/eddiesigner/liebling/wiki/How-to-enable-search

**Comment by veshitala** [comment]
Thank you so much now it is working fine
