### ISSUE TITLE
Setting up theme development environment with Docker on MacOS

### ISSUE THREAD

**Issue by youngpilot** [eddiesigner/liebling#120]
I followed the amazingly simple guide to develop this theme with Docker Desktop on MacOS. Thanks @D3473R! Unfortunately neither the page loads when accessing _http://localhost:3000_ nor the zip gets build when using the _npm run production_ command in the terminal. The terminal doesn't show any errors. Here is what I see:
```
Last login: Mon Jan  6 13:57:22 on ttys000
Rocinante:~ mrjs$ cd /Users/mrjs/Documents/Ghost/content/themes/liebling/src 
Rocinante:src mrjs$ npm install
npm WARN liebling@1.0.0 No description
npm WARN liebling@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: win-node-env@0.4.0 (node_modules/win-node-env):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-node-env@0.4.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

removed 9 packages and audited 28251 packages in 7.589s
found 0 vulnerabilities

Rocinante:src mrjs$ npm run get-database
Rocinante:src mrjs$ npm run docker-watch
Rocinante:src mrjs$ npm run production
Rocinante:src mrjs$ 
```

I guess I still have to setup some environment in/for the docker container? 
Any ideas how to get it running as intended?

**Comment by D3473R** [comment]
You should only need docker and docker-compose.
Maybe you have disabled npm scripts? [https://stackoverflow.com/a/38847762](https://stackoverflow.com/a/38847762)

**Comment by eddiesigner** [comment]
I think @D3473R is right, you can also try this: https://techformist.com/npm-run-does-nothing-at-svelte-startup/

**Comment by youngpilot** [comment]
Yes, you are right! It works now, after removing `ignore-scripts = true` from ~/.npmrc.
Thank you so much for your help!
