### ISSUE TITLE
Search feature doesn't work

### ISSUE THREAD

**Issue by patrickphatnguyen** [eddiesigner/liebling#125]
Hello, I've upgraded to Ghost 3.2 and the Search feature suddenly become unusable, no results showed up. Can anyone confirm that this is caused by Ghost 3.2 or because it's just me messing around with the source code ?:P Thank you!
This is my site: https://www.vietcs.org/

**Comment by D3473R** [comment]
Hi, your site responds `Error: Unknown Content API Key`, do you have changed or resetted yout content key?

**Comment by patrickphatnguyen** [comment]
Thank you @D3473R for your help. It works fine now!
