### ISSUE TITLE
CSS class errors

### ISSUE THREAD

**Issue by valentierra** [eddiesigner/liebling#126]
Hi There!

I am using ghost 3.2.0 and I am getting the following errors while using the Liebling theme:

Any guidance is much appreciated!

----------------------------------------
2020-01-12 04:12:21] WARN The currently active theme "liebling" has errors, but will still work.

The currently active theme "liebling" has errors, but will still work.

Error ID:
    baa04610-34f1-11ea-a490-6d3a0ac27811

Details:
    checkedVersion: 3.x
    name:           liebling
    path:           content/themes/liebling
    version:        0.6.3
    errors: 
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-width-wide</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-width-wide</code> CSS class is required otherwise wide images will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#image-size-implementations" target=_blank>here</a>.
        regex: 
        className: .kg-width-wide
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGWW
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-width-full</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-width-full</code> CSS class is required otherwise full width images will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#image-size-implementations" target=_blank>here</a>.
        regex: 
        className: .kg-width-full
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGWF
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-gallery-container</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-gallery-container</code> CSS class is required otherwise galleries will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#gallery-card" target=_blank>here</a>.
        regex: 
        className: .kg-gallery-container
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGGC
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-gallery-row</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-gallery-row</code> CSS class is required otherwise gallery rows will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#gallery-card" target=_blank>here</a>.
        regex: 
        className: .kg-gallery-row
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGGR
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-gallery-image</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-gallery-image</code> CSS class is required otherwise gallery images will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#gallery-card" target=_blank>here</a>.
        regex: 
        className: .kg-gallery-image
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGGI
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-card</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-card</code> CSS class is required otherwise the bookmark card will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-card
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBM
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-container</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-card</code> CSS class is required otherwise the bookmark card will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-container
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMCO
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-content</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-content</code> CSS class is required otherwise the bookmark card main content will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-content
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMCON
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-title</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-title</code> CSS class is required otherwise the bookmark card title will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-title
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMTI
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-description</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-description</code> CSS class is required otherwise the bookmark card description will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-description
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMDE
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-metadata</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-metadata</code> CSS class is required otherwise the bookmark card meta details will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-metadata
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMME
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-icon</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-icon</code> CSS class is required otherwise the bookmark card author icon will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-icon
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMIC
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-author</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-author</code> CSS class is required otherwise the bookmark card author name will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-author
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMAU
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-publisher</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-publisher</code> CSS class is required otherwise the bookmark card publisher name will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-publisher
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMPU
      - 
        fatal:     false
        level:     error
        rule:      The <code>.kg-bookmark-thumbnail</code> CSS class is required to appear styled in your theme
        details:   The <code>.kg-bookmark-thumbnail</code> CSS class is required otherwise the bookmark card thumbnail image will appear unstyled.Find out more about required theme changes for the Koenig editor <a href="https://ghost.org/docs/api/handlebars-themes/editor/#bookmark-card" target=_blank>here</a>.
        regex: 
        className: .kg-bookmark-thumbnail
        css:       true
        failures: 
          - 
            ref: styles
        code:      GS050-CSS-KGBMTH

----------------------------------------

**Comment by eddiesigner** [comment]
Please check this out: https://github.com/eddiesigner/liebling/issues/105 

You're using an old version of this theme.

**Comment by valentierra** [comment]
My bad. Thank you!

**Comment by valentierra** [comment]
Isn't it the last version 0.6.3? I am getting the same error messages with this version.

**Comment by valentierra** [comment]
Initially, I installed 0.6.3 liebling theme it through the package.json file dependencies, with the errors mention above. Later I uploaded the theme which seem to correct the missing files. Now it seems to work fine.
