### ISSUE TITLE
Assets broken when Ghost 3.0 installed in subdirectory.

### ISSUE THREAD

**Issue by ntchi** [eddiesigner/liebling#128]
Hi!

We have installed this amazing theme on a Ghost that lives in a /blog subdirectory.  And the theme is looking for icons icomoon.ttf in  /assets not /blog/assets.  Any ways to edit this globally so the theme knows it resides in a subdirectory instead or root?

Cheers,

**Comment by eddiesigner** [comment]
So all the assets (css/images/js) are working but the icons?

**Comment by ntchi** [comment]
A bit like the issue #109.

I think people who installed ghost in a subdirectory like Mysite.com/blog for instance will have this issue.

Since it tries to load some stuff in /assets instead of /blog/assets

**Comment by eddiesigner** [comment]
I fixed this issue, please download the lates version from here: https://github.com/eddiesigner/liebling/releases/tag/v.0.6.5
