### ISSUE TITLE
Posts excerpt in Home page

### ISSUE THREAD

**Issue by xiyizhou** [eddiesigner/liebling#132]
is there any plan add Posts excerpt in Home page, like this.
![Snipaste_2020-01-31_19-42-19](https://user-images.githubusercontent.com/55862635/73536824-d9835200-4461-11ea-8760-12f0615f9b11.png)

**Comment by eddiesigner** [comment]
Sorry but I don't have plans to display posts excerpts. The reason is because I want all the post cards to have the same height and for aesthetic reasons. There are several implications to be solved regarding that and I don't plan to work on it at the moment.

Thanks for your understanding.

**Comment by xiyizhou** [comment]
Thank you for your reply
