### ISSUE TITLE
How to keep header fixed when scrolling down

### ISSUE THREAD

**Issue by sspieler** [eddiesigner/liebling#133]
wanted to keep the header fixed as you scoll down. Can u pls help?

**Comment by eddiesigner** [comment]
I guess the easiest way to do it is by injecting these styles to the _Site Header Code injection_ section of your Ghost instance:

```html
<style>
.m-header {
  position: fixed !important;
  transform: none !important;
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
