### ISSUE TITLE
Change size of featured card

### ISSUE THREAD

**Issue by devjacquesN** [eddiesigner/liebling#135]
Hi there, can you please let me know how to change the featured post card to stretch across the whole screen instead of just being on the left.

**Comment by eddiesigner** [comment]
Hi,

You can inject the following code into the _Site Header Code injection_ section of your Ghost instance:

```html
<style>
  @media only screen and (min-width:64rem) {
    .m-featured-slider {
      width:calc(100% - 40px);
      margin: -40px 20px 20px;
    }
  }
</style>
```

Cheers.

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
