### ISSUE TITLE
Prism line numbers is not aligned with lines of code

### ISSUE THREAD

**Issue by roniemartinez** [eddiesigner/liebling#138]
I followed the guide from Ghost [website](https://ghost.org/tutorials/code-syntax-highlighting/ and syntax) highlighting from liebling [wiki](https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism)

It resulted in the following image:
![image](https://user-images.githubusercontent.com/2573537/75086438-27760c00-556f-11ea-9c96-c152560c6b7f.png)

**Comment by eddiesigner** [comment]
I will release a new version soon to fix that, in the meantime you can paste the following snippet in the Code injection page of your Ghost instance (Site Header):

```html
<style>
.l-post-content pre.line-numbers > code {
  padding: 0;
}
</style>
```

**Comment by roniemartinez** [comment]
Thanks @eddiesigner worked like a charm.
![image](https://user-images.githubusercontent.com/2573537/75103265-505fd500-5633-11ea-8e6e-656fd0f7145d.png)
