### ISSUE TITLE
IS there a plan to make toc for this theme?

### ISSUE THREAD

**Issue by TillLindemann** [eddiesigner/liebling#146]
Thank you for this beautiful theme, I really love it and appreciate your great work.
But recently I've been working on adding toc for my blog, Although there is an official tutorial for this, But I failed many times , because this theme is a little different from other themes.
here is the tutorial:
https://ghost.org/tutorials/adding-a-table-of-contents/?_ga=2.8856117.1440588615.1584581452-1250222531.1584338288

And I went into trouble at this step:
```javascript
<script>
    tocbot.init({
        tocSelector: '.toc',
        contentSelector: '.post-content',
        hasInnerContainers: true
    });
</script>
```

my blog indicates that it does not have the ".post-content" element, so the toc can not be established.
So I wonder if you would plan to do this?

**Comment by eddiesigner** [comment]
Hi 👋 

I don't have plans to give native support for this since a very few people might need it and because you can integrate it for yourself if needed.

To solve the issue you just need to use `.js-post-content` instead of `.post-content`

**Comment by TillLindemann** [comment]
@eddiesigner Thank You so much, I fixed this problem according to your suggestion. Close this issue.
IF anyone run into the same problem , please follow the suggestion above.
