### ISSUE TITLE
Form styling

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#15]
Demo: https://calvintam.dev/p/ce382342-c4dd-4d0a-8bf5-bd63d55a6611/

Looks like there is no styling for form? I am trying to setup a contact form using formspree.io.

**Comment by eddiesigner** [comment]
Thanks for the heads up, I already added styles to form controls, although if you want to distribute the controls in some specific way, you will have to add your own styles in the **Code injection** section.

**Comment by calvintam236** [comment]
Thanks @eddiesigner
