### ISSUE TITLE
Footer layout 

### ISSUE THREAD

**Issue by giuwolf** [eddiesigner/liebling#155]
How can i change the footer layout? 
I would like to add items side-by-side, as mentioned in the issue #111. 
I would really appreciate if someone could help me with this one. :)

**Comment by eddiesigner** [comment]
@giuwolf Have you tried the code I posted in that issue? https://github.com/eddiesigner/liebling/issues/111#issuecomment-571581176

**Comment by giuwolf** [comment]
It worked! Thanks a lot :)
