### ISSUE TITLE
How do I hide the hero header?

### ISSUE THREAD

**Issue by muhyal** [eddiesigner/liebling#156]
Hi,

Thank you very much for this awesome style.

How can I hide the hero image and title, desc.. on the homepage without breaking author page, post page hero header image?

I made a few edits on hero.hbs and index.hbs and I see errors :)

![Screenshot_2](https://user-images.githubusercontent.com/55546452/78667824-4e4f8e00-78e2-11ea-8517-9b26d0736acf.png)
![Screenshot_1](https://user-images.githubusercontent.com/55546452/78667826-4f80bb00-78e2-11ea-97b9-aad2fa439e2f.png)

**Comment by eddiesigner** [comment]
You can remove the hero in the homepage by deleting from [line 14](https://github.com/eddiesigner/liebling/blob/master/index.hbs#L14) to [line 27](https://github.com/eddiesigner/liebling/blob/master/index.hbs#L27) in `index.hbs`

Then probably you will want to add some padding at the top, to do that you can inject the following styles into the _Code injection_ page (Site header block) of your Ghost admin:

```html
<style>
@media only screen and (min-width:48rem) {
  .l-content {
    padding: 60px 0 40px;
  }
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.

**Comment by MrNovy** [comment]
Hi, how can i hide the hero picture, tittle and description on the homepage only with the code injection page? 
Best regards!
