### ISSUE TITLE
Missing language Dutch

### ISSUE THREAD

**Issue by Qballjos** [eddiesigner/liebling#157]
Couldn't find a dutch language file so I made one for you.

save it as nl.json ;-)

{
  "% min read": "% min gelezen",
  "% posts": "% posts",
  "1 min read": "1 min gelezen",
  "1 post": "One post",
  "Among with": "<br>Samen met ",
  "Among with no break line": "Samen met ",
  "Apparently there are no posts at the moment, check again later.": "Helaas zijn er op dit moment geen berichten, kom later terug.",
  "Back to home": "Terug naar home",
  "Email cannot be blank.": "Email mag niet leeg zijn.",
  "Featured": "Aanbevolen",
  "Get the latest posts delivered right to your inbox.": "Krijg de laatste berichten rechtstreeks in je inbox.",
  "Go to the home page": "Gaan naar de home pagina",
  "Great! Next, complete checkout for full access.": "Top! Nu nog de checkout afronden voor volledige toegang.",
  "Great! You've successfully subscribed.": "Top! je hebt je succesvol ingeschreven.",
  "JavaScript license information": "JavaScript license information",
  "No posts": "Geen berichten",
  "No posts found": "Geen berichten gevonden",
  "No recent articles found :(": "Geen recente artikelen gevonden :(",
  "No results for your search, try something different.": "Geen resultaat voor je zoek opdracht, probeer het eens op een andere manier.",
  "No tags found :(": "Geen tags gevonden :(",
  "Now check your inbox and click the link to confirm your subscription.": "Kijk nu in je inbox en bevestig je inschijving",
  "Oops! There was an error sending the email, please try later.": "Oeps! Er heeft zich een fout voor gedaan bij het verzenden van de email, probeer het later nog eens.",
  "Page": "Pagina",
  "Page not found": "Pagina niet gevonden",
  "Please enter a valid email address": "Voor een geldig email adres in",
  "Posted by": "Gepost door",
  "Published with": "Gepubliceerd met",
  "Recent articles": "Recente artikelen",
  "Recommended for you": "Aanbevolen voor jou",
  "Stay up to date! Get all the latest & greatest posts delivered straight to your inbox.": "Blijf op de hoogte! Krijg alle beste en laatste berichten rechtstreeks in je inbox.",
  "Subscribe": "Schrijf je in",
  "Subscribe to": "Schrijf je in voor",
  "Subscribe to our newsletter": "Schrijf je in voor de nieuwsbrief",
  "Subscribed!": "Ingeschreven!",
  "Success! Your account is fully activated, you now have access to all content.": "Yes! je account is volledig geactiveerd, je hebt nu toegang to alle inhoud.",
  "Tags": "Tags",
  "Toggle dark mode": "Kleuren modus",
  "Type to search": "Type om te zoeken",
  "Unfortunately the page you were looking for could not be found.": "Helaas de pagina die je zocht kan niet worden gevonden.",
  "Welcome back! You've successfully signed in.": "Welkom terug! Je bent succesvol ingelogd.",
  "You've successfully subscribed to": "Je hebt je ingeschreven voor",
  "Your email address": "Uw email adres",
  "of": "of",
  "with the email address": "met het email adres",
  "with this tag": "met de tag"
}

**Comment by eddiesigner** [comment]
Hey, thank you! Only one thing, would you mind to open a pull request for this instead? 😅

**Comment by Qballjos** [comment]
Sure no problem made the PR
