### ISSUE TITLE
npm run production overwrites css changes

### ISSUE THREAD

**Issue by kelskelskels** [eddiesigner/liebling#158]
Maybe a stupid question, sorry. I'm not much of a developer.

I had no problems running the theme locally and seeing changes applied. However upon generating a .zip to upload to my ghost instance (npm run production), the app.css file got minified and overwrote any changes I had made. Is this to be expected? I would expect the app.css file inside the .zip to be minified, but not the app.css file inside the original repository.

Thanks for the awesome theme!

**Comment by kelskelskels** [comment]
Never mind, I now understand how scss works. Closing this out.

**Comment by demakufl** [comment]
Hey there, 

I just stumbled upon the same issue as well. Haven't worked with scss before. Reading into it now, but would you care to elaborate your findings? :)

**Comment by demakufl** [comment]
Okay, I got it now, too. Once I found the app.scss I noticed that changes to the css had to be made there instead in the app.css.
