### ISSUE TITLE
Reading progress indicator reaches 100% before post end

### ISSUE THREAD

**Issue by joshuamccracken** [eddiesigner/liebling#16]
Hi,

I noticed the reading progress indicator circle reaches 100% at about 75% of the way down the post. You can see an example on my site: https://thinkingtheology.org/the-eternal-security-of-believers/
What is the best way to fix this?

**Comment by eddiesigner** [comment]
This should be fixed in the latest release https://github.com/eddiesigner/liebling/releases/tag/v.0.1.9

**Comment by joshuamccracken** [comment]
Latest release fixed the issue thanks
