### ISSUE TITLE
Add an other commend system

### ISSUE THREAD

**Issue by Happyfeet01** [eddiesigner/liebling#160]
Hello,

I use an other Commend System on my Blog. "talkyard".

I have added the code in post.hbs and it works, but how can I center it? On mobile view it looks good, but not on Desktop. 

<center> </center> won't work. 

Can you help me?

https://dasnetzundich.de/ghost-cms-einrichten-mit-docker-compose/

**Comment by eddiesigner** [comment]
Hey, is this still relevant? I can see you're using a different theme, if not then I will close this issue ;)

**Comment by Happyfeet01** [comment]
Is still relevant :-)

**Comment by eddiesigner** [comment]
I can see that you're not using the tags and classes that are needed in order to display comments in a right way.

Please take a look to the file `post.hbs` from [line 149](https://github.com/eddiesigner/liebling/blob/master/post.hbs#L149) 

Basically you have to modify that file as follows:

```html
<section class="m-comments">
  <div class="m-load-comments">
    <div class="m-load-comments__line"></div>
    <button class="m-icon-button filled as-load-comments js-tooltip js-load-comments" data-tippy-content="Load comments">
      <span class="icon-comments"></span>
    </button>
  </div>
  <div class="m-load-comments__iframe l-wrapper in-comments js-comments-iframe">
    <!-- TALKYARD CODE GOES HERE -->
  </div>
</section>
```

**Comment by Happyfeet01** [comment]
if added the code like this. But not showing up

`          {{!-- If you want to embed comments, this is a good place to do it! --}}
          <center><a href="https://www.buymeacoffee.com/xxxxxx" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/arial-blue.png" alt="Kaffeespende" style="height: 51px !important;width: 217px !important;" ></a></center>
          {{!--
          <section class="m-comments">
            <div class="m-load-comments">
              <div class="m-load-comments__line"></div>
              <button class="m-icon-button filled as-load-comments js-tooltip js-load-comments" data-tippy-content="Load comments">
                <span class="icon-comments"></span>
              </button>
            </div>
            <div class="m-load-comments__iframe l-wrapper in-comments js-comments-iframe">
              <script>talkyardServerUrl='https://comment.domain.tld';</script>
              <script async defer src="https://comment.domain.tld/-/talkyard-comments.min.js"></script>
              
              <div class="talkyard-comments" data-discussion-id="{{comment_id}}" style="margin-top: 45px;">
              <noscript>Please enable Javascript to view comments.</noscript>
              <p style="margin-top: 25px; opacity: 0.9; font-size: 96%">Comments powered by
              <a href="https://www.talkyard.io">Talkyard</a>.</p>
              </div>
             </script>
            </div>
          </section>
          --}}
        {{/post}}`

**Comment by Happyfeet01** [comment]
@eddiesigner cis it possible that the comments are always visible?
