### ISSUE TITLE
center nav menu

### ISSUE THREAD

**Issue by habnai** [eddiesigner/liebling#162]
thank you for your work.how i can center the nav menu i mean the logo stay in the left and the menu in the center?

**Comment by eddiesigner** [comment]
To do that you have to modify the file `partials/header.hbs` and delete from [line 33](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L33) to [line 45](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L45).

After that you have to paste the following code after [line 30](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L30):

```hbs
{{#if @site.logo}}
  <a href="{{@site.url}}" class="m-logo">
    <img src="{{@site.logo}}" alt="{{@site.title}}">
  </a>
{{else}}
  <a href="{{@site.url}}" class="m-site-name in-desktop-menu">
    {{@site.title}}
  </a>
{{/if}}
```

Finally you have to head to the _Code injection_ page and paste the following code into the _Site Header_ block:

```html
<style>
.m-menu .m-logo,
.m-menu .m-site-name.in-desktop-menu {
  display: none;
}

@media only screen and (min-width:48rem) {
  .m-menu .m-logo,
  .m-menu .m-site-name.in-desktop-menu {
    display: inline-block;
  }

  .m-menu .m-site-name.in-desktop-menu {
    font-size: 1.125rem;
  }
}
</style>
```

**Comment by habnai** [comment]
Great.
Thank you
