### ISSUE TITLE
hi, I found such a problem.

### ISSUE THREAD

**Issue by fly12358** [eddiesigner/liebling#169]
When browsing a group of pictures in the article on the mobile phone, one of the pictures is not as wide as the screen when its attribute width and height are small. Click on the picture, and the picture will be blurred after zooming in.

Thank you for the template, it's awesome!👍

**Comment by eddiesigner** [comment]
Hmm I don't really understand the issue 😅 

Can you please provide screenshots or a link for this article?

**Comment by TMDBug** [comment]
Sorry, my English is getting rusty.  :(
please look at this pictures~ 
<img width="373" alt="blurs" src="https://user-images.githubusercontent.com/26156269/79934143-68fa3900-8484-11ea-826d-0a7d3b4ad315.png">
<img width="367" alt="clickPic" src="https://user-images.githubusercontent.com/26156269/79934152-6e578380-8484-11ea-83ed-44bfa8fbc58b.png">
<img width="369" alt="itsclear" src="https://user-images.githubusercontent.com/26156269/79934153-70214700-8484-11ea-8cb2-59bd72fa26df.png">

**Comment by eddiesigner** [comment]
Hi,

thanks for the screenshots, that was really helpful ;)

I already fixed it, please download the latest version from the [releases page](https://github.com/eddiesigner/liebling/releases).

**Comment by TMDBug** [comment]
👍
