### ISSUE TITLE
# of search results

### ISSUE THREAD

**Issue by expatabroad** [eddiesigner/liebling#17]
Hi - I just installed your theme today. Love your work

I have a question re: search function

I have got the search installed, and it works fine, except it only returns one result, even when there are multiple posts containing the same search term.

Is there a setting that I need to update, or is this just a limitation of the search functionality?

Thanks in advance :-)

**Comment by eddiesigner** [comment]
Sorry for the late answer but I was on vacation. Thanks for the heads up! I already fixed this issue, please download the latest version (0.2.0) and you're done ;)

**Comment by expatabroad** [comment]
Thanks so much for fixing this :-) Will give it a try
