### ISSUE TITLE
Adding the Commenting option in the blog

### ISSUE THREAD

**Issue by chaitanyasaxena97** [eddiesigner/liebling#170]
Hello 

I want to integrate disqus(Or any other platform) into my blogs for commenting options please let me know how to do this I think we also should have to add this feature to the theme

**Comment by eddiesigner** [comment]
Please take a look to this: https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog

**Comment by eddiesigner** [comment]
Please take a look to this: https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog

**Comment by eddiesigner** [comment]
Please take a look to this: https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog

**Comment by chaitanyasaxena97** [comment]
Thanks a lot
