### ISSUE TITLE
reduice number post card on home page

### ISSUE THREAD

**Issue by habnai** [eddiesigner/liebling#172]
hi i want show only 4 card on home page 2 on one line and 2 on second line, how modified the post-card on home page?

**Comment by eddiesigner** [comment]
To do that you would need to delete the slider of featured posts first from the file `index.hbs` (from line [33](https://github.com/eddiesigner/liebling/blob/master/index.hbs#L33) to line [77](https://github.com/eddiesigner/liebling/blob/master/index.hbs#L77)).

Then you have to edit the file `package.json` and change the value of `posts_per_page` to 4.

**Please note that the previous change will be applied on all your pages, not only on the home page.**

Finally you have to inject these styles in your Ghost admin (_Code injection > Site Header_):

```html
<style>
@media only screen and (min-width:64rem) {
  .home-template .m-article-card {
    width: calc(50% - 40px) !important;
  }
}
</style>
```

**Comment by habnai** [comment]
thank you
