### ISSUE TITLE
docker-compose development not loading

### ISSUE THREAD

**Issue by Chrisjb** [eddiesigner/liebling#173]
When running the `npm run docker-watch` command, the configuration seems to all work but when loading localhost:3000 the page just hangs and never loads.

The output in terminal is:
 

> > docker-compose up -d && node node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> Creating network "src_default" with the default driver
> Creating ghost ... done
> 10% building 5/5 modules 0 active
> webpack is watching the files…
> 
> 57% building 28/29 modules 1 active ...es/sass-loader/lib/loader.js??ref--5-4!/Users/chrisbailey/Documents/git-projects/liebling-new/src/sass/app.scssBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
> 98% after emitting SizeLimitsPlugin
> 
>  DONE  Compiled successfully in 2413ms                                                                                                         21:51:02
> 
>                         Asset      Size        Chunks             Chunk Names
>            /fonts/icomoon.eot    14 KiB                [emitted]  
>            /fonts/icomoon.svg    49 KiB                [emitted]  
>            /fonts/icomoon.ttf  13.8 KiB                [emitted]  
>           /fonts/icomoon.woff  13.9 KiB                [emitted]  
>                    /js/app.js  15.3 KiB       /js/app  [emitted]  /js/app
>                /js/helpers.js   4.3 KiB   /js/helpers  [emitted]  /js/helpers
>                   /js/home.js  5.91 KiB      /js/home  [emitted]  /js/home
>               /js/manifest.js  6.12 KiB  /js/manifest  [emitted]  /js/manifest
>                   /js/page.js  6.35 KiB      /js/page  [emitted]  /js/page
>                   /js/post.js  11.5 KiB      /js/post  [emitted]  /js/post
>                 /js/vendor.js   672 KiB    /js/vendor  [emitted]  /js/vendor
> /js/vendor/content-api.min.js  36.4 KiB                [emitted]  
>                   css/app.css   110 KiB   /js/helpers  [emitted]  /js/helpers
> [Browsersync] Proxying: http://localhost:2368
> [Browsersync] Access URLs:
>  --------------------------------------
>        Local: http://localhost:3000
>     External: http://192.168.0.129:3000
>  --------------------------------------
>           UI: http://localhost:3001
>  UI External: http://localhost:3001
>  --------------------------------------
> [Browsersync] Watching files...
> [Browsersync] Reloading Browsers... (buffered 80 events)

**Comment by eddiesigner** [comment]
Please check this out: https://github.com/eddiesigner/liebling/issues/64

If it still doesn't work for you, please just try to run that command one more time or wait a bit, usually after some seconds you can open `http://localhost:3000` and hit the refresh button a couple of times and it will work.

**Comment by Chrisjb** [comment]
Yes sorry forgot to mention I'd seen that post and tried reloading a bunch of times but no luck. As the last commenter said seems to be stuck in a loop! Going to try and figure out a workaround later

**Comment by D3473R** [comment]
> When running the `npm run docker-watch` command, the configuration seems to all work but when loading localhost:3000 the page just hangs and never loads.
> 
> The output in terminal is:
> 
> > > docker-compose up -d && node node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> > 
> > 
> > Creating network "src_default" with the default driver
> > Creating ghost ... done
> > 10% building 5/5 modules 0 active
> > webpack is watching the files…
> > 57% building 28/29 modules 1 active ...es/sass-loader/lib/loader.js??ref--5-4!/Users/chrisbailey/Documents/git-projects/liebling-new/src/sass/app.scssBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
> > 98% after emitting SizeLimitsPlugin
> > DONE  Compiled successfully in 2413ms                                                                                                         21:51:02
> > ```
> >                     Asset      Size        Chunks             Chunk Names
> >        /fonts/icomoon.eot    14 KiB                [emitted]  
> >        /fonts/icomoon.svg    49 KiB                [emitted]  
> >        /fonts/icomoon.ttf  13.8 KiB                [emitted]  
> >       /fonts/icomoon.woff  13.9 KiB                [emitted]  
> >                /js/app.js  15.3 KiB       /js/app  [emitted]  /js/app
> >            /js/helpers.js   4.3 KiB   /js/helpers  [emitted]  /js/helpers
> >               /js/home.js  5.91 KiB      /js/home  [emitted]  /js/home
> >           /js/manifest.js  6.12 KiB  /js/manifest  [emitted]  /js/manifest
> >               /js/page.js  6.35 KiB      /js/page  [emitted]  /js/page
> >               /js/post.js  11.5 KiB      /js/post  [emitted]  /js/post
> >             /js/vendor.js   672 KiB    /js/vendor  [emitted]  /js/vendor
> > ```
> > 
> > 
> > ## /js/vendor/content-api.min.js  36.4 KiB                [emitted]
> > css/app.css   110 KiB   /js/helpers  [emitted]  /js/helpers
> > [Browsersync] Proxying: http://localhost:2368
> > [Browsersync] Access URLs:
> > ```
> >    Local: http://localhost:3000
> > External: http://192.168.0.129:3000
> > ```
> > 
> > 
> > 
> > ```
> >       UI: http://localhost:3001
> > ```
> > 
> > 
> > ## UI External: http://localhost:3001
> > [Browsersync] Watching files...
> > [Browsersync] Reloading Browsers... (buffered 80 events)

Are there any errors in the browser javascript console? Open it with F12 in your Browser.

**Comment by Chrisjb** [comment]
> Are there any errors in the browser javascript console? Open it with F12 in your Browser.

No messages at all in the console even when ticking 'preserve log'. 

Ah I just opened up my docker desktop dashboard though and I see this error:

> Attaching to ghost
> 
> ghost | tar: apps: Cannot mkdir: No space left on device
> 
> ghost | tar: Exiting with failure status due to previous errors
> 
> ghost exited with code 2

**Comment by D3473R** [comment]
Okay, that could be the real issue.
Try to increase the disk image size: https://docs.docker.com/docker-for-mac/space/

**Comment by Chrisjb** [comment]
Yep turns out that was the real issue, sorry I didn't notice that before. Increased the disk size and ran `docker system prune` to free up some space and have it working now, cheers!
