### ISSUE TITLE
Taglist

### ISSUE THREAD

**Issue by andreasmaierhofer** [eddiesigner/liebling#178]
Hello!
First of all: I love your Theme, it's just great.

One thing I would really love is a Tag-Page like this:
http://sinai.aspirethemes.com/tags/

Since I have more and more Content on my page, this would be great to increase the usability.

Just an input. Thank you for your work.

**Comment by eddiesigner** [comment]
That's a good idea, I guess in the near future I'll release a new version that includes this feature.

**Comment by hiensarahly** [comment]
Hi @eddiesigner & friends please see if this could work:
- Create a custom-tagsCloud.hbs
- Add the following code:
 ```
{{!--
This template is used for the posts that are marked as pages.
--}}

{{!-- The tag below means: insert everything in this file
into the {body} of the default.hbs template --}}
{{!< default}}

{{!-- Everything inside the #post tags pulls data from the post --}}
{{#post}}
<div class="main-wrap">
  {{!-- Special header.hbs partial to generate the <header> tag --}}
  {{> header background=feature_image}}
  {{!-- Inject styles of the hero image to make it responsive --}}
  {{> hero background=feature_image}}
  <div class="m-hero__content" data-aos="fade-down">
    <h1 class="m-hero-title bigger">{{title}}</h1>
    {{#if custom_excerpt}}
    <p class="m-hero-description">{{custom_excerpt}}</p>
    {{/if}}
  </div>
  </section>
  <main>
    <article>
      <div class="l-content">
        <div class="l-wrapper in-post" data-aos="fade-up" data-aos-delay="300">
          <div class="l-post-content">
            <div class="pos-relative js-post-content">
              {{content}}
            </div>

            <div id="tagCloud">
              {{#get 'tags' limit='1' include='count.posts' order='count.posts asc'}}
              {{#foreach tags}}
              <script>
                var min = {{ count.posts }};
              </script>
              {{/foreach}}
              {{/get}}


              {{#get 'tags' limit='1' include='count.posts' order='count.posts desc'}}
              {{#foreach tags}}
              <script>
                var max = {{ count.posts }};
              </script>
              {{/foreach}}
              {{/get}}

              <script>
                const maxFontSize = 30;
                const minFontSize = 12;
                const maxColor = 255;
                const minColor = 135;
                const slopeSize = ((maxFontSize - minFontSize) / (max - min));
                const slopeColor = ((maxColor - minColor) / (max - min));
                const sizeB = (minFontSize - (slopeSize));
                const colorB = (minColor - (slopeColor));
              </script>

              {{#get 'tags' limit='all' include='count.posts' order='name ASC'}}
              {{#foreach tags}}
              <span class="tag-cloud" id="tag-{{ name }}">
                <a href='{{ url }}'>{{ name }}</a>
              </span>
              <script>
                var size = (slopeSize * ({{ count.posts }}) + sizeB);
                var spanColor = (slopeColor * ({{ count.posts }}) +(colorB));
                document.getElementById('tag-{{ name }}').style.fontSize = (size + "px");
              </script>
              {{/foreach}}
              {{/get}}

            </div>
          </div>
        </div>
      </div>
    </article>
  </main>
</div>
{{/post}}

{{!-- The #contentFor helper here will send everything inside it up to the matching #block helper found in default.hbs --}}
{{#contentFor "scripts"}}
<script defer src="{{asset "js/page.js"}}"></script>
{{/contentFor}}

```
- Create a Tags page, e.g. https://YOUR_BLOG_URL/tags
- Choose tagsCloud template in the page settings
- Done!

I got it working on my blog with Liebling theme, very glad! ^^ 

Credits:
- https://forums.engineerworkshop.com/t/how-to-make-a-tags-page/93/2
- https://github.com/Torqu3Wr3nch/nightCasper/blob/master/custom-tagsCloud.hbs

**Comment by eddiesigner** [comment]
@hiensarahly Thanks for sharing! Would you mind to show us a live example just to see how it looks? 😄 

Btw, I think you don't need to use `{{#get}}` twice in order to get the min and max values, I guess you can use it once and get those values by using `@first` and `@last` somehow, more info here: https://ghost.org/docs/api/v3/handlebars-themes/helpers/foreach/#first--last

**Comment by hiensarahly** [comment]
@eddiesigner The example tag page is here if you would like a look: https://zenyrgarden.com/tags/ I truly appreciate it!!

You know I didn't write that code piece :) but obviously the author is very open for improvement. It's great to tweak it to make it cleaner, I like that idea a lot!

**Comment by eddiesigner** [comment]
No problem ;) Thanks again for sharing!

**Comment by eddiesigner** [comment]
Hey everyone 👋🏻

I just released a new version that finally includes a Taglist page.

You can see a live demo here: https://liebling.eduardogomez.io/tags/ 

And you can see how to enable it here: https://github.com/eddiesigner/liebling/wiki/How-to-enable-Taglist-page

Please download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.7.7) to get it ;)

**Comment by eddiesigner** [comment]
I will close this issue since this feature is already implemented in the latest version ;)
