### ISSUE TITLE
Should have Code block different color for dark/light mode

### ISSUE THREAD

**Issue by JustHmmmm** [eddiesigner/liebling#179]
Hmmmm, I think this theme should have some CSS to modify code block text color instead of use same color with --link-color. It'll better if text have different color in dark mode and light mode. And I hope Font Awesome version for this theme will be released, FA is prettier - slower too, but I think it better than icomoon.

**Comment by eddiesigner** [comment]
Yes, I was also thinking of changing the color of the code blocks, although if what you're looking for is syntax highlighting, I recommend you check [this guide](https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism).

About the icons, I don't use icons directly from Font Awesome or from Icomoon, instead I have a custom icon set. Icomoon is only the tool I use to generate the font face.
