### ISSUE TITLE
How to enable dark mode only?

### ISSUE THREAD

**Issue by gingerbread-cyber** [eddiesigner/liebling#181]
Hey! I love your Theme it's beautiful and literally amazing. 

One thing I would really want is, in Casper theme we can modify the CSS file and change it to dark mode only. Here is the [reference from Ghost.org forum](https://forum.ghost.org/t/how-to-enable-dark-mode-in-casper-3-0/9822/4) Like that how can we customize dark mode only in Liebling theme? Please help me! :)

**Comment by eddiesigner** [comment]
The easiest way you can force dark theme is by injecting this code into the "Site Header Code injection" section of your Ghost instance:

```html
<style>
  :root,
  [data-theme="light"],
  [data-theme="dark"],
  :root:not([data-theme="light"]) {
    --background-color: #111;
    --primary-foreground-color: #ccc;
    --secondary-foreground-color: #fff;
    --primary-subtle-color: #2c2fe6;
    --secondary-subtle-color: #141920;
    --titles-color: #b4b4b4;
    --link-color: #2c2fe6;
    --primary-border-color: #1d1d1d;
    --secondary-border-color: #0f0f0f;
    --article-shadow-normal: 0 4px 5px 5px rgba(0,0,0,0.1);
    --article-shadow-hover: 0 4px 5px 10px rgba(0,0,0,0.1);
    --transparent-background-color: rgba(0,0,0,0.99);
    --footer-background-color: #080808;
    --submenu-shadow-color-opacity: 0.55;
    --button-shadow-color-normal: rgba(10, 10, 10, 0.5);
    --button-shadow-color-hover: rgba(10, 10, 10, 0.5);
    --toggle-darkmode-button-color: #efd114;
    --table-background-color-odd: #050505;
    --table-head-border-bottom: #1d1d1d;
  }
</style>
```

You might wanna also like to remove the toggle button too, to do that just edit the file `partials/header.hbs` and remove the code from [line 112](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L112) to [line 115](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L115).

**Comment by gingerbread-cyber** [comment]
Thank you so much! It worked ;)
You are an amazing developer ❤️

**Comment by Wsget** [comment]
thx.
