### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by giannisth** [eddiesigner/liebling#182]
Hi!
I am using your Theme, for my personal blog and it is great, 
I am from Greece and I translated to Greek lang when I will finish the translation I will send the file.
Could you please let me know if there is a proper way to update the theme at new version cause I made some modification to some .hbs files and if I use an updated version I will loose all modifications.

Thanks

**Comment by eddiesigner** [comment]
I guess the best way to keep it in sync is by forking this repo and pull the latest changes (if any) whenever you want. There is a guide that you can follow to do exactly that: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

After doing that, if you pull the latest changes from this repo and there are conflicts, you can decide if you want to keep our changes or yours.

If you want to make a contribution please don't forget to read [the guidelines](https://github.com/eddiesigner/liebling/wiki/Pull-Request-Guidelines) 😄

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
