### ISSUE TITLE
Newsletter/Subscribe 404

### ISSUE THREAD

**Issue by rizmonto** [eddiesigner/liebling#189]
Hello, I enabled **Members** under Labs and created a new link/page in the admin ghost admin panel under "**Design**" but unfortunately, I still get a 404 not found. Do I have to create a new page under Pages as well?

**Comment by eddiesigner** [comment]
Please take a look on this: https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.

**Comment by yurijean** [comment]
@eddiesigner same here, I did the steps described at the wiki (enabled Members and create newsletter page) for Ghost v3, but I get the 404 page when I access /newsletter

**Comment by eddiesigner** [comment]
Did you create a page called `Newsletter` in the Ghost admin as well or did you only add a link for the newsletter?

You have to create first a page called `Newsletter` and then add the link of that page in the navigation panel.

**Comment by yurijean** [comment]
Oops, I have only created the link for `/newsletter`. I suggest to put some more emphasis on this on the Wiki article, since @rizmonto isn't the only one who had this issue.

Thank you very much, @eddiesigner

**Comment by eddiesigner** [comment]
@yurijean I will do that ;)
