### ISSUE TITLE
search results limit (also) but can we search content not just titles

### ISSUE THREAD

**Issue by seigomark** [eddiesigner/liebling#19]
Firstly Eduardo

Thank you so much or the incredible theme, really love the performance and design. 
I saw another user mention number of search results was limited to one but can i also add to this the search seems to only be indexed on titles, can we change this to show all matches on al content?

Really appreciate your work and them!

**Comment by eddiesigner** [comment]
Sorry for the late answer but I was on vacation. I already fixed the issue with the number of results and now the search is indexing the content as well. Please download the latest version (0.2.0) to see the changes ;)

**Comment by seigomark** [comment]
You are awesome Eduardo.

Thanks for the quick fix and caring about what you create.
Have a great day!
Mark
