### ISSUE TITLE
Adding new javascript files gives 404 when v= parameter is added.

### ISSUE THREAD

**Issue by jaruesink** [eddiesigner/liebling#191]
I am trying to add a helloworld.js file into the js directory. It compiles correctly, but I cannot get it to load with the version added. I restarted docker-watch, but it seems like I'm missing something.

wepback.mix.js
```
mix
  .js('js/helpers.js', 'js/')
  .js('js/app.js', 'js/')
  .js('js/home.js', 'js/')
  .js('js/post.js', 'js/')
  .js('js/page.js', 'js/')
  .js('js/helloworld.jsx', 'js/')
```

**Comment by jaruesink** [comment]
It worked after killing the docker container and restarting it all. Not sure if there's an easier way to approach this?

**Comment by eddiesigner** [comment]
According to the Ghost docs:

> If you add any new files to your theme during development, you'll need to restart Ghost to see the changes take effect.

You can run `docker-compose restart` but I guess is the same as you did. It's more a Ghost limitation I would say.

**Comment by jaruesink** [comment]
Yeah.. just mildly inconvenient. Thanks!
