### ISSUE TITLE
Translate the theme to catalan

### ISSUE THREAD

**Issue by ferranrego** [eddiesigner/liebling#193]
Hello, I saw that Liebling has a list of community translations. Is there any guide on how to translate the theme to catalan?

Thanks!

**Comment by eddiesigner** [comment]
Hi,

not really but you can find some info about it here: https://ghost.org/docs/api/v3/handlebars-themes/helpers/translate/#making-a-theme-translatable

Basically you have to fork this repository, create a file called `ca.json` within the `locales` folder and write your translations based on the `partials/en.json` file.

After that you can create a pull request with your changes. If you decide to create a PR, please take a look on this link first: https://github.com/eddiesigner/liebling/wiki/Pull-Request-Guidelines

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
