### ISSUE TITLE
H1 for article titles should be replaced by H2

### ISSUE THREAD

**Issue by raduvultur** [eddiesigner/liebling#196]
This way there's only one H1 on the page. The SEO score is lowered by having multiple H1.

**Comment by eddiesigner** [comment]
You're right, if the requested changes from [this PR](https://github.com/eddiesigner/liebling/pull/195) are made, I can merge it and this could be fixed.

**Comment by raduvultur** [comment]
#199

**Comment by eddiesigner** [comment]
It's already merged it ;)
