### ISSUE TITLE
Reduce Publication cover height

### ISSUE THREAD

**Issue by cataldoc** [eddiesigner/liebling#198]
Hi

there's any way to reduce the height of the publication cover from the homepage ?

Cheers,
cataldoc

**Comment by eddiesigner** [comment]
Hi,

You can do that by heading to _Admin panel -> Code injection_ and injecting the following code into the _Site Header_ section:

```html
<style>
@media only screen and (min-width:48rem) {
  .home-template .m-hero {
    min-height: 300px !important; /* You can set the height you want here */
  }
}
</style>
```

**Comment by cataldoc** [comment]
Tnx a lot, that works !
