### ISSUE TITLE
background is not set to white with dark mode enabled in admin

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#2]
![Screen Shot 2019-05-14 at 10 51 54 AM](https://user-images.githubusercontent.com/6436149/57720355-8993ff00-7636-11e9-8869-25c379d295e5.png)

**Comment by eddiesigner** [comment]
@calvintam236 Oh, that's new, I didn't know that you can see a live preview right in the admin. Anyway, it should be fixed now.

**Comment by calvintam236** [comment]
Fix confirmed.
