### ISSUE TITLE
Mobile view - FB/Twitter/Back to top anchor not working in mobile view since update

### ISSUE THREAD

**Issue by expatabroad** [eddiesigner/liebling#20]
Hi Eduardo,
I noticed that since you did the update/fix to search, that in the mobile view, the bar that has the links to Facebook, Twitter & 'back to top'/% viewed is not anchoring to the foot of the screen.
![liebling](https://user-images.githubusercontent.com/53624361/62830962-7f6ea600-bc0f-11e9-8650-b90a58c5da20.png)
Initially I thought it was something I caused when tweaking the CSS, but your demo page at https://liebling.eduardogomez.io is having the same issue.

Hoped this could be fixed as it's a sweet function

**Comment by eddiesigner** [comment]
Oh damn, you're right, I fixed it with the latest release (0.2.1), please download it and now should be fine.
