### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by partizan007** [eddiesigner/liebling#202]
I recently started using the liebling theme for a project, really great work thank you.

I dont know how can I change the date format to DD MM YYYY?

Can anybody help me?

**Comment by eddiesigner** [comment]
You can pass a format string to the `{{date}}` helper. More info here: https://ghost.org/docs/api/v3/handlebars-themes/helpers/date/#description

For instance, if you want to change the date format in post pages, you can change [line 33](https://github.com/eddiesigner/liebling/blob/1e96082b1182c4d81700eb0a8e8bd57314c712b4/post.hbs#L33) like this:

```hbs
<span class="m-heading__meta__time">{{date published_at format=DD MM YYYY"}}</span>
```

**Comment by partizan007** [comment]
Thank you!!!
