### ISSUE TITLE
Different logo for dark and light themes

### ISSUE THREAD

**Issue by cmfam** [eddiesigner/liebling#204]
Our main logo (the one on the top left corner) is white in color which displays perfectly on the dark theme, but does not look good in the lighter theme.

Can we do something with the css to change the logo for light and dark themes? or Is there a possibility to upload two different logo one for light theme another for dark theme?

**Comment by eddiesigner** [comment]
Currently is not possible to upload two different logos in Ghost. What you can do  is to apply a filter to the logo to invert the color.

You can paste this code into _Code injection / Site Header_ in your Ghost Admin:

```html
<style>
.m-logo img {
  filter: invert(1);
}

[data-theme="light"] .m-logo img {
  filter: invert(1);
}

[data-theme="dark"] .m-logo img {
  filter: none;
}

@media (prefers-color-scheme: dark) {
  .m-logo img {
    filter: none;
  }

  [data-theme="light"] .m-logo img {
    filter: invert(1);
  }
}
</style>
```

**Comment by cmfam** [comment]
Thanks @eddiesigner, this helps.
