### ISSUE TITLE
Zoom icon on image with URL 

### ISSUE THREAD

**Issue by jugdeepgill** [eddiesigner/liebling#206]
Hi there, 

I love your theme and it's beautiful. However, I have an issue where I have an image with a URL. For example, 

`<a href="example"><img src="01.jpg" alt="example"></a>` 

Once I save this markup and publish my post, my post does show the image with link attached but the mouse icon becomes 'zoom icon'. 

I've attached an image below for you to understand what I'm saying, any idea on how this could be solved? 

[Image](https://ibb.co/ySXcRmH)

Again, thanks for the great theme.

**Comment by eddiesigner** [comment]
Hi 👋🏻

Thanks for the heads up! I already fixed this issue, please download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.7.2) 😉

Cheers.
