### ISSUE TITLE
Page returns error for largest contentful paint

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#208]
Hello,
I'm posting here because casper doesn't have that error. It seems there's an error with the LCP on google pagespeed: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsoundsirius.digitalpress.blog%2Fservices

The pages: 
 - https://soundsirius.digitalpress.blog/services
 - https://soundsirius.digitalpress.blog/products/

**Comment by nsursock** [comment]
also happening here: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsoundsirius.digitalpress.blog%2Ftestimonials%2F&tab=desktop

**Comment by eddiesigner** [comment]
I'm closing this since this is about the same topic that is already posted here: https://github.com/eddiesigner/liebling/issues/205
