### ISSUE TITLE
Making the theme translatable

### ISSUE THREAD

**Issue by clappingmonkey** [eddiesigner/liebling#22]
Hi! Very nice theme. Good job!

**Question:** _Are you planing making the theme translatable so it can be used in other languages?_  - [Ghost`s doc on the subject](https://ghost.org/docs/api/v2/handlebars-themes/helpers/translate/)

**Comment by D3473R** [comment]
I've customized this theme for a site and added german translations.
I will open a pull request, then you can add your locale too.

**Comment by eddiesigner** [comment]
Thank you @D3473R! I've added some missing translations and also I added the spanish locale.
