### ISSUE TITLE
CSS issue in focus input

### ISSUE THREAD

**Issue by kmanojkumar** [eddiesigner/liebling#222]
Hi,

There is an issue with focus input colour **#2997ff** used in certain areas of the page. This doesn't seem to be inline with the design colours. A variable is also not available in the _themes.scss. 

![Screenshot 2020-07-08 at 1 33 37 PM](https://user-images.githubusercontent.com/14366356/86894130-417c4980-c120-11ea-8707-b235c80967f3.png)
![Screenshot 2020-07-08 at 1 33 52 PM](https://user-images.githubusercontent.com/14366356/86894134-42ad7680-c120-11ea-9248-efada1436632.png)
![Screenshot 2020-07-08 at 1 34 22 PM](https://user-images.githubusercontent.com/14366356/86894137-43dea380-c120-11ea-8bdd-0fc4f3d0f4c0.png)

Screenshots for your reference.

Can you pls add a variable in the themes.scss for the same?

**Comment by eddiesigner** [comment]
I already changed this, now it uses `--primary-subtle-color` as color value. Please download the latest version in order to see the change: https://github.com/eddiesigner/liebling/releases/tag/v.0.7.6

Please remember that I added this style for accessibility reasons mostly ;)
