### ISSUE TITLE
How to auto slide for featured post

### ISSUE THREAD

**Issue by nadrasaputra** [eddiesigner/liebling#229]
How to make slider for featured post autoslide?

**Comment by eddiesigner** [comment]
You have to change a bit the file [`home.js`](https://github.com/eddiesigner/liebling/blob/master/src/js/home.js), in order to do that you have first to follow [this guide](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) to create a custom version of this theme.

Then you have to add the following line to the `featuredSlider` configuration object:

```js
autoplay: 2000, // or any other amount of miliseconds
```

You can't change it directly in the javascript file that is located in the `assets` directory because that file is minified for performance reasons and it's overwritten in every new release.

**Comment by nadrasaputra** [comment]
Great...it works.
Thank you.

**Comment by itsmeakhil** [comment]
i am also trying to auto slide but the file gets auto rewritten every time , so how can i change it permanently

**Comment by eddiesigner** [comment]
I already explained it in my comment above https://github.com/eddiesigner/liebling/issues/229#issuecomment-663847783, please read and follow the steps carefully.

**Comment by lapphan** [comment]
```
  if ($featuredSlider.length > 0) {
    const numSlides = $featuredSlider.find('.js-featured-slide').length
    const featuredSlider = new Glide('.js-featured-slider', {
      type: 'slider',
      rewind: false,
      gap: 0,
      swipeThreshold: false,
      dragThreshold: false,
      direction: isRTL() ? 'rtl' : 'ltr',
      autoplay: 5000,
      breakpoints: {
        768: {
          swipeThreshold: numSlides === 1 ? false : 80,
          dragThreshold: numSlides === 1 ? false : 120
        }
      }
    })
```

@eddiesigner Is it correct? It's not working on my site.

**Comment by eddiesigner** [comment]
It looks good to me, did you generate a production build after making those changes? https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker#production-mode

**Comment by rafazafar** [comment]
@lapphan 
add Autoplay in import:

```
import Glide, {
  Controls,
  Swipe,
  Breakpoints,
  Autoplay
} from '@glidejs/glide/dist/glide.modular.esm'
```

Add "autoplay: 2000" and ".mount({ Autoplay })" when adding glide:

```
if ($featuredSlider.length > 0) {
    const numSlides = $featuredSlider.find('.js-featured-slide').length
    const featuredSlider = new Glide('.js-featured-slider', {
      type: 'slider',
      gap: 0,
      swipeThreshold: false,
      dragThreshold: false,
      autoplay: 2000,
      direction: isRTL() ? 'rtl' : 'ltr',
      breakpoints: {
        768: {
          swipeThreshold: numSlides === 1 ? false : 80,
          dragThreshold: numSlides === 1 ? false : 120
        }
      }
    }).mount({ Autoplay })
```
