### ISSUE TITLE
taglist page doesnt show pictures

### ISSUE THREAD

**Issue by timscha** [eddiesigner/liebling#231]
Hi!
I just updated to the latest version 0.77 und tried the taglist feature. In general this is working fine, he shows all tags. But unlike your demo it doesn't show any images on the tags itself.
I have some posts which haven't a feature image, some of them have. Is this maybe already the problem? 

Thanks for your help
Tim

**Comment by kmanojkumar** [comment]
Hi @timscha,

There is no issue with the Taglist page in the theme. For the images to be displayed in the Taglist grid, you have to add a **Tag image** to every Tag by going to _Ghost Admin > Tags > Open a Tag > Right Side Tag image upload_ option will be available, to upload an image for your Tag.

After you upload an image there, refresh https://your_blog.com/tags page, image will be available now.

FYI - Post featured images, have nothing to do with Tag Page images. 

Thanks!

**Comment by timscha** [comment]
Thanks @kmanojkumar! This wasn`t mentioned in the wiki or I didn`t saw it. Worked now! :)
