### ISSUE TITLE
Removing hero images from post page

### ISSUE THREAD

**Issue by maxpereira** [eddiesigner/liebling#232]
I want to remove the hero image from my post pages. When I remove the appropriate section from post.hbs, everything works however when the page is refreshed the page scrolls down a little bit each time. Can you advise how to remove hero images from the post page without incurring this behavior? Thanks.

**Comment by eddiesigner** [comment]
How did you remove the hero image from the post template?

To remove the hero from that template you have to remove this code:

```hbs
{{#post}}
  {{!-- Inject styles of the hero image to make it responsive --}}
  {{> hero background=feature_image}}
  </section>
{{/post}}
```

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
