### ISSUE TITLE
logo size

### ISSUE THREAD

**Issue by habnai** [eddiesigner/liebling#233]
how i can customize logo size i want insert logo but all time its so small which size for logo for the theme .thank you

**Comment by eddiesigner** [comment]
[These](https://github.com/eddiesigner/liebling/blob/master/src/sass/components/header/_logo.scss) are the styles for the logo, in the Ghost Admin you can overwrite the height value of the `.m-logo` class.

Also please make sure that your image doesn't have any "air" or empty space surrounding the actual logo, if it does then you have to remove that "air" with some editing tool.

**Comment by habnai** [comment]
thanks
