### ISSUE TITLE
GDPR-compliant version

### ISSUE THREAD

**Issue by schniewmatz** [eddiesigner/liebling#234]
Dear Eduardo,

First of all, thank you for this great theme :) :wink: :1st_place_medal: I really like the features you added, like the featured post slider and the Tags page. I'm currently testing it and I usually like to modify themes in a way, that they do not depend on any CDNs, especially to avoid any GDPR issues, directing my visitors information to third-parties outside the EU. Usually for e.g. jquery, mathjax, or prism this is super easy, but for your theme this isn't trivial with Google webfonts and polyfill:

**Google Webfonts - This is urgent for all sites with visitors from the EU!**
Google definitely stores the IP of the visitor for analytics: [_"Google Fonts logs records of the CSS and the font file requests, and access to this data is kept secure."_](https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users)
That means that Google stores data it doesn't need to provide the service and hence the use of Google webfonts from the Google API needs the users consent, otherwise you risk to get a letter from a lawyer that wants to make some money...

Options to solve this issue:  
- Host the fonts locally, basically include them in your theme as css  
- Don't use Google fonts....  
- Use a consent management tool (which I personally don't want as I hate those pop ups with sliders or ticks...)  
- Do you have other ideas?  

**polyfill.io**
I think it is safe and a nice feature for downward compatibility. On the privacy site it states:  
 _"We use that information to determine which polyfills are required by your browser. We then retain only the following information:_
- _the domain of the web page which has made the request to the Service;_
- _the user agent string for your browser;_
- _the set of polyfills that were requested by the web page."_
https://polyfill.io/v3/privacy-policy/  

Hence, I think it is safe to keep, especially as it is hosted via its own CDN.

I am looking forward to read about your point of view :nerd_face:

**Comment by schniewmatz** [comment]
This was partly discussed in #153 , but not with a focus on the legal implications.

**Comment by eddiesigner** [comment]
Hey, thanks for using this theme!

In the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.1) Google webfonts are now loaded locally ;)

Regarding to polyfill.io I will keep it as it is now.

**Comment by schniewmatz** [comment]
Nice, great work :slightly_smiling_face:  :+1:
