### ISSUE TITLE
Change Light and Dark mode Toggle icon

### ISSUE THREAD

**Issue by kmanojkumar** [eddiesigner/liebling#239]
Hi,

Based on user behaviour analytics, I observed that most of the readers aren't able to figure out the light and dark button toggle icon in the blog.

Maybe changing it to something more obvious and widely used like Sun+Moon, can help? For [ref](https://cdn0.iconfinder.com/data/icons/display-setting/64/Choose_theme-512.png).

Thanks.

**Comment by eddiesigner** [comment]
That's a good idea, I will try to implement as soon as I have time for it.

**Comment by eddiesigner** [comment]
This is already implemented in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) ;)
