### ISSUE TITLE
Slow loading time for larger posts

### ISSUE THREAD

**Issue by mustakimali** [eddiesigner/liebling#24]
The page load animation - that fades-in after the content it fully loaded sometime can confuse user into thinking that the page hasn't loaded. Is there any way this animation can be disabled? or perhaps a loading indicator would also help.

**Comment by eddiesigner** [comment]
Sorry but I don't get it, how the user can gets confused with that animation?

At the moment there is no way to disable it, I can implement something to achieve that but you'll need to edit a bit of code within the `Code injection` page.

**Comment by mustakimali** [comment]
The screen stays blank (white) until all of the elements are loaded. On one of my blog post (that has 6 gist and a few images) - the screen stays blank for 5/6 seconds. That's long enough for the user to think there is something wrong and leave.

Hope it explains it. I would appreciate if you implement the option to disable it (happy to inject some code within the `Code injection` page).

**Comment by eddiesigner** [comment]
From version 0.2.4 you can disable the fade animation following these steps: https://github.com/eddiesigner/liebling/wiki/How-to-disable-the-fade-animation ;)

**Comment by mustakimali** [comment]
That's awesome. Appreciate it very much. Thank you.
