### ISSUE TITLE
Markdown Image (link to a blogpost)

### ISSUE THREAD

**Issue by vikiivalle** [eddiesigner/liebling#240]
I have a doubt, we linked a photo with markdown so that when people click in the image they can go to a blogpost. The issue is that when we are in the post and we pass with the mousse through the photo, a zoom + icon appears so it doesn't look like a clickable image, do you know if we can change that so that it's more obvious that you have to click on it?

**Comment by eddiesigner** [comment]
I will close this issue since this bug was [already reported](https://github.com/eddiesigner/liebling/issues/206) some time ago, please download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.1) in order to fix it.

**Comment by vikiivalle** [comment]
Hi Eduardo

Thanks for the reply.

How can I do to update the new version? Attached is an image of what I see in ghost: do I have to click on "upload a theme" as if it was a new one?

In case I have to do that, eoes it modify anything in my blog<https://blog.jampp.com/>?
For example a developer has added a few things like to open the links in a new page or a search bar.. If I change the theme/updated it will I loose those things?

Thanks!

________________________________

**Comment by eddiesigner** [comment]
Hi,

If you've made changes in the theme then you might need to implement those again in this new version, it depends of the changes really. If he made the changes through the Ghost Admin then you can just upload the new version and that's it, but if he modified some theme files, then those changes have to be done again in the new version.

I know it's not optimal but that's how it works at the moment, that would happen with this theme or with any other theme.

**Comment by vikiivalle** [comment]
Hi Eduardo,

Thanks for your reply!

I have an issue with the markdown image link. I was able to add an image and link it without problem but when I add a gif and link it I don't know why it appears twice (attached) and below de image a text appears.

Do you know what can I do?

Thanks!
________________________________

**Comment by vikiivalle** [comment]
I was able to solve it by doing it with html!
________________________________
