### ISSUE TITLE
Disable Dark Theme without SRC Changes

### ISSUE THREAD

**Issue by jefcollins** [eddiesigner/liebling#242]
Hi there!
It would be great to have better control over the dark / light theming from the admin options.

Having to setup a Docker container to go and remove / edit 1 line (e.g. @media prefers-color-scheme: dark)) seems like massive overkill and then creates a custom theme.

Ideally this could be managed in Admin which I appreciate is up to Ghost.
Perhaps this could be better managed as an integration or just less tangled in the SRC to allow for Code Injection to override it?

Would appreciate any ideas / support to help!

You can see how the dark preference is breaking our theme here: https://blog.paddl.com/

**Comment by eddiesigner** [comment]
Hi!

Actually you can disable the dark theme easily through the Ghost Admin, basically you can inject some styles to overwrite the CSS variables, you can see an example in [this thread](https://github.com/eddiesigner/liebling/issues/98#issuecomment-562944840), just make sure to use the most [recent values](https://github.com/eddiesigner/liebling/blob/master/src/sass/common/_themes.scss).

Something like this would be enough:

```html
<style>
  :root,
  [data-theme="light"],
  [data-theme="dark"],
  :root:not([data-theme="light"]) {
    --background-color: #fff;
    --primary-foreground-color: #4a4a4a;
    --secondary-foreground-color: #000;
    --primary-subtle-color: #0470ee;
    --secondary-subtle-color: #f4f8fd;
    --titles-color: #333;
    --link-color: #293951;
    --primary-border-color: #9b9b9b;
    --secondary-border-color: aliceblue;
    --article-shadow-normal: 0 10px 10px rgba(0,0,0,0.08);
    --article-shadow-hover: 0 4px 60px 0 rgba(0,0,0,0.2);
    --transparent-background-color: rgba(255,255,255,0.99);
    --footer-background-color: #133467;
    --submenu-shadow-color-opacity: 0.25;
    --button-shadow-color-normal: rgba(108, 108, 108, 0.2);
    --button-shadow-color-hover: rgba(108, 108, 108, 0.3);
    --toggle-darkmode-button-color: #fff;
    --table-background-color-odd: #fafafa;
    --table-head-border-bottom: #e2e2e2;
  }
</style>
```

**Comment by jefcollins** [comment]
Brilliant, thank you Eddie!
That has worked perfectly.

Updated results here: blog.paddl.com
