### ISSUE TITLE
Vietnamese font support is broken

### ISSUE THREAD

**Issue by lapphan** [eddiesigner/liebling#244]
After updating to Version 0.8.1, my blog (written in Vietnamese) is display Vietnamese incorrectly. My guess is because of the new font version. 

![image](https://user-images.githubusercontent.com/11986206/88803189-4a6bb280-d1d6-11ea-934e-3dbc236ce75e.png)

**Comment by eddiesigner** [comment]
This should be fixed in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) ;)
