### ISSUE TITLE
Please add a bit of color to the hyperlinks

### ISSUE THREAD

**Issue by MereCivilian** [eddiesigner/liebling#245]
Hello

Firstly, this is a fantastic theme.

I do feel that the hyperlinks on my post are not that evident that they are links. They seem like underlined text rather than a link.

For example, for this post: https://merecivilian.com/keychronk1/

See attached images.
![54BBEDC6-2B57-490B-8B20-31FC19248F9E](https://user-images.githubusercontent.com/68980168/88873978-4df84b80-d261-11ea-93e6-f789f50a84fc.jpeg) 

![15844677-F4F7-4976-A1C3-3442F6198DB3](https://user-images.githubusercontent.com/68980168/88873968-48026a80-d261-11ea-962b-a386ec2f7e8e.jpeg)

I am not fussed on which color but I feel any color would make it more obvious that it is a link. The Ghost default theme (casper) basically changes the color when you hover over the link. This is also good option.

Thanking you once again for making this theme.

**Comment by eddiesigner** [comment]
The [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) implements a hover state for links in posts. However, if you want to use another color you have to change it by yourself through the Admin panel.
