### ISSUE TITLE
Credit for cover image

### ISSUE THREAD

**Issue by curiousdungbeetle** [eddiesigner/liebling#253]
Hello eddiesigner, thank you again for your great work on this theme!

I was wondering if there is a way to give credit (caption and link) for the cover image, please? Ghost by default doesn't do this, but it would be useful as giving credit is good practice, especially if not using my own imagery. I saw a workaround [on this page](https://forum.ghost.org/t/image-caption-for-feature-image/9184) but couldn't make it work for this theme. Any suggestion please?

Thank you!

**Comment by eddiesigner** [comment]
Hi,

Sorry but I can only implement features if Ghost provides tools to work with, that's not the case in this scenario.

If you really want to give credit you could add a small text at the beginning (or at the end) of your posts manually.

**Comment by curiousdungbeetle** [comment]
OK, thanks - I'll do that then!
