### ISSUE TITLE
Discourse comments

### ISSUE THREAD

**Issue by silvacraig** [eddiesigner/liebling#262]
I dropped the code for Discourse comments into the comments section on post.hbs - When there are no comments - the embedded url is cut off at the bottom - the button to start a discussion only displays the top . Had a bit of a look but web stuff is not my specialty - any  tip on how to size the iframe to get the button to display without getting cut off? I admit css is not my thing

**Comment by eddiesigner** [comment]
Can you please provide a link to see it? I don't understand what do you mean exactly.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
