### ISSUE TITLE
Modify menu ‚All stories‘ 

### ISSUE THREAD

**Issue by Singi20** [eddiesigner/liebling#263]
Hello, Is there a way to easily exclude one blog category from the ‚ All Stories‘ view? I would like that the articles in one category do not show up on the blog page but only by clicking on the category itself. Thanks for your help.

**Comment by eddiesigner** [comment]
Hi,

Hmm what "All stories" view do you mean? This theme doesn't have a view like that 🤔

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
