### ISSUE TITLE
How to disable Dark mode?

### ISSUE THREAD

**Issue by jessechowforeal** [eddiesigner/liebling#264]
Hi,

I love using this theme, great design!

Could you please tell me how to disable Dark mode? I'd like it to be light mode all the time.

Thanks!

Jesse

**Comment by eddiesigner** [comment]
Hi,

[This](https://github.com/eddiesigner/liebling/issues/242) and [this other](https://github.com/eddiesigner/liebling/issues/98) thread might help you.
