### ISSUE TITLE
Subscribe Button Home

### ISSUE THREAD

**Issue by Gabrunz** [eddiesigner/liebling#266]
How to delete the Subscribe Button in the Home Page when Ghost members is enabled ?

**Comment by eddiesigner** [comment]
You can remove the following code from the [`index`](https://github.com/eddiesigner/liebling/blob/master/index.hbs) template:

```hbs
{{#if @labs.subscribers}}
  <a href="{{@site.url}}/subscribe" class="m-button filled">{{t "Subscribe"}}</a>
{{/if}}
{{#if @labs.members}}
  <a href="{{@site.url}}/newsletter" class="m-button filled">{{t "Subscribe"}}</a>
{{/if}}
```

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
