### ISSUE TITLE
assign class name to "published with ghost"

### ISSUE THREAD

**Issue by distresscode** [eddiesigner/liebling#268]
Not really an issue but I didn't know where else to contact you. First, I'd like to say THANK YOU for creating an amazing theme and providing it for free for the community! I was able to customize Liebling using the code injection tool and without modifying the template files except for taking out the "published by ghost" which required editing the footer template. I'd really appreciate it if you could assign a class name so the site copyright (site name & year) is separate than the "published with ghost" part. Thanks again!

**Comment by eddiesigner** [comment]
Thanks for using Liebling! 🙂

There is no need for a new class, you can achieve it with this code:

```html
<style>
  .m-footer-copyright span:nth-child(2),
  .m-footer-copyright span:nth-child(3) {
    display: none;
  }
</style>
```

**Comment by distresscode** [comment]
That worked beautifully. Thanks Eddie!
