### ISSUE TITLE
Doesn't work on Ghost Local Install

### ISSUE THREAD

**Issue by Aiyush-G** [eddiesigner/liebling#271]
Hi,

I have downloaded the Liebling theme from here: https://github.com/eddiesigner/liebling/releases and I have clicked on this download and I add it to my ghost backend (localhost) and save it and activate it, no errors. But when I preview the site it is still on the default theme (Casper).

EDIT: Other themes work
EDIT: I am using Version 3.33.0 and have tried Version 3.0.0

Please can someone help, thanks
Aiyush Gupta

**Comment by eddiesigner** [comment]
That doesn't sound like an issue with this theme. If you see the Casper theme after activating Liebling then there is something happening in your Ghost instance or your server. If this theme had an issue then probably you would see errors or a blank page but not the Casper theme.

A lot of people have installed this theme and this is the first time I hear something like that, did you download this file? https://github.com/eddiesigner/liebling/releases/download/v.0.8.5/liebling.zip

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
