### ISSUE TITLE
Medium Zoom on gallery is not working on mobile

### ISSUE THREAD

**Issue by jules-ch** [eddiesigner/liebling#273]
Zoom is not properly zooming when on mobile for gallery images.

It seems to be related to `.medium-zoom-image-mobile` selector

**Comment by eddiesigner** [comment]
Can you please share a screenshot?

**Comment by jules-ch** [comment]
On master, it behaves like so :

![20-09-23-20-20-24](https://user-images.githubusercontent.com/43635101/94055420-3363ce00-fddd-11ea-9d51-7f189cb4bc2c.gif)

**Comment by jules-ch** [comment]
After removing this bit in `src/js/helper.js`

```diff
export const makeImagesZoomable = ($, mediumZoom) => {
  const zoom = mediumZoom('.js-zoomable')

-  zoom.on('open', (event) => {
-    if (isMobile() && $(event.target).parent().hasClass('kg-gallery-image')) {
-      setTimeout(() => {
-        const $mediumZoomImage = $('.medium-zoom-image--opened')
-        const transform = $mediumZoomImage[0].style.transform
-        const scale = transform.substr(0, transform.indexOf(' '))
-        const scaleValue = parseFloat(scale.substr(scale.indexOf('(') + 1).split(')')[0])
-        const translate = transform.substr(transform.indexOf(' ') + 1)
-        const translateY = parseFloat(translate.split(',')[1])
-        const newTranslateY = (translateY < 0) ? (scaleValue * translateY) + translateY : (scaleValue * translateY) - translateY
-        const newTransform = `scale(1) translate3d(0, ${newTranslateY}px, 0)`
-
-        $mediumZoomImage.addClass('medium-zoom-image-mobile')
-        $mediumZoomImage[0].style.transform = newTransform
-      }, 10)
-    }
-  })
-
-  zoom.on('close', () => {
-    if (isMobile() && $(event.target).parent().hasClass('kg-gallery-image')) {
-      const $mediumZoomImage = $('.medium-zoom-image')
-      $mediumZoomImage.removeClass('medium-zoom-image-mobile')
-    }
-  })
}
```

it becomes this : 

![20-09-23-20-22-20](https://user-images.githubusercontent.com/43635101/94055866-ca308a80-fddd-11ea-83cc-e2ed98b9cf77.gif)

**Comment by jules-ch** [comment]
Great work btw, I really like the theme so far ! ❤️

**Comment by eddiesigner** [comment]
The zoom works well on mobile devices, the only way it could behave like in the first gif is if you remove the `width: 100% !important;` as I saw you did 🤔 

The code in `src/js/helper.js` exists to solve [this other issue](https://github.com/eddiesigner/liebling/issues/169) so I wouldn't recommend to delete it.

**Comment by jules-ch** [comment]
Well retried on master, I still see this issue. `width: 100% !important` is applied on the image but it still not working.

![image](https://user-images.githubusercontent.com/43635101/94468293-78fd0e00-01c4-11eb-89ac-f182da7dcaec.png)

Didn't see the other issue, I was wondering what this bit of code was trying to solve.

**Comment by jules-ch** [comment]
It works image is smaller than the screen like in the issue you mentionned but width 100% when image is bigger than the mobile screen, thats another thing entirely

**Comment by eddiesigner** [comment]
For some reason two images are created in your website instead of just one when you activate the zoom, you can see that in the screenshot you sent. Maybe there is a bug with [medium-zoom](https://github.com/francoischalifour/medium-zoom) and images with `srcset`.

In my blog it works well because the images don't have that attribute, maybe a newer version of Ghost implements that now. You can see it working here: https://liebling.eduardogomez.io/video-games-playing-with-imagination/

If you hide the second image you can see the image below has the right size. For now you can keep the code you posted above and then hide the second image created with this style:

```html
<style>
img.js-zoomable.medium-zoom-image.medium-zoom-image--opened + img {
  display: none !important;
}
</style>
```

**Comment by jules-ch** [comment]
True good catch, out of curisity which version of ghost are you using i'll try to rollback see if it changes something

**Comment by eddiesigner** [comment]
Liebling uses Ghost `3.11.0` currently but I guess is better if you try what I wrote in my last comment. I will try to fix it in a future update anyways.
