### ISSUE TITLE
Docker chown in/out error

### ISSUE THREAD

**Issue by mewc** [eddiesigner/liebling#274]
When spinning up a fresh repo after `get-database`, i run `docker-watch` and in the container logs i get

```
chown: changing ownership of '/var/lib/ghost/content/themes/liebling/.git/objects/pack/pack-496578e41062728dceda14d01a69547c57158110.idx': Input/output error
```

In turn it makes default localhost hang, but i can hit the browserSync page.

I can make it work by running a ghost install, and run the dev script inside content/themes. 

Seems like something about the plug n play for docker-watch isnt fully working in some cases

**Comment by eddiesigner** [comment]
I'm not sure if this issue is really related to the theme itself or even to the Ghost image itself. It sounds more like a environment-specific issue, could you try on a different computer or with a different environment?
