### ISSUE TITLE
Executable file on git repo

### ISSUE THREAD

**Issue by planetahuevo** [eddiesigner/liebling#275]
Hi, 
I found that you have one executable file on the repo, which causes issues when updating it from the source. 

https://github.com/eddiesigner/liebling/blob/master/locales/zh-hans.json
![image](https://user-images.githubusercontent.com/2963191/94362927-57156580-00b6-11eb-9254-39a7d6f98291.png)

**Comment by eddiesigner** [comment]
Hi, thanks for the heads up. It's fixed now on master ;)

<img width="586" alt="CleanShot 2020-09-28 at 19 52 15@2x" src="https://user-images.githubusercontent.com/1477503/94468061-27ed1a00-01c4-11eb-9af7-0ac84d273576.png">

**Comment by planetahuevo** [comment]
Thanks!
