### ISSUE TITLE
Laravel Mix keeps rebuilding in development container

### ISSUE THREAD

**Issue by ichitaka** [eddiesigner/liebling#280]
So just spend this whole day fixing this issue on my machine 😢  Thought I might give you guys the solution if anybody is facing the same issue.
Because of something, my ghost container was having issues with the files in the .git folder of this project. You can test this by running 
```
docker-compose up
```
in the src folder. If you see chown issues with files in the .git folder, you are facing the same issue as I did. The solution was for me to overwrite it with the .git folder from my src folder. You can do that with the following addition to the docker-compose.yml file:
```
    volumes:
      - .git:/var/lib/ghost/content/themes/liebling/.git:Z
      - ./..:/var/lib/ghost/content/themes/liebling:Z
      - ./ghost.db:/var/lib/ghost/content/data/ghost.db:Z
```
Of course, you could also just link to any .git folder that is empty.

**Comment by greengraca** [comment]
I think I'm having this same issue, but this fix didn't help me. Am I supposed to replace that with the volumes that were already in the docker-compose file ? It didn't help

**Comment by ichitaka** [comment]
You can test if you have the same issue easily by running
```
docker-compose up
```
in the src folder. Does the container start up successfully, without any warning / error logs?

**Comment by greengraca** [comment]
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[14964] Failed to execute script docker-compose

**Comment by greengraca** [comment]
It also says when i run the docker-watch that I'm trying to send a windows file to a linux container and that it may perform bad. And it says that the Windows Home can only run the WSL 2 backend

**Comment by ichitaka** [comment]
Please first try to run that command without changing the docker-compose file. Also, I seem to have misunderstood why my solution was working. I have a .git folder in my src folder.

**Comment by greengraca** [comment]
This is what i get with the normal docker-compose file:

Recreating ghost ... done
Attaching to ghost
ghost    | [2020-10-14 09:49:15] INFO Ghost is running in development...
ghost    | [2020-10-14 09:49:15] INFO Listening on: 0.0.0.0:2368
ghost    | [2020-10-14 09:49:15] INFO Url configured as: http://localhost:2368/
ghost    | [2020-10-14 09:49:15] INFO Ctrl+C to shut down
ghost    | [2020-10-14 09:49:15] INFO Ghost boot 5.156s

**Comment by ichitaka** [comment]
Your container seems to be working. I'm sorry but you seem to have a different issue than mine.

**Comment by greengraca** [comment]
Ok, so, i just figured out i can access the /ghost (the admin page) , but i cant acess the normal :3000 port.
Maybe because the WSL2 only gives me backend ? I don't know
