### ISSUE TITLE
Theme got missing frequently 

### ISSUE THREAD

**Issue by sonipranjal** [eddiesigner/liebling#282]
500
The currently active theme "liebling-updated" is missing.
Go to the front page →

**Comment by sonipranjal** [comment]
I hosted it on heroku and using this theme but it is showing this again and again.

**Comment by eddiesigner** [comment]
I think you're not using this theme actually 🤔

The theme name is **liebling**, not _liebling-updated_.

I suggest you to download it from the [releases page](https://github.com/eddiesigner/liebling/releases) and try again.

If it happens again you can try to install a different theme and see how it goes. If you can install themes but after some time they just "disappear" then there is something going on with your server (your Heroku instance in this case).

**Comment by sonipranjal** [comment]
Thank you for replying. Your theme is just awesome. I think It is some issue with heroku. Not with theme.

**Comment by eddiesigner** [comment]
Thanks! Then I will close this issue, please feel free to reopen it if needed.
