### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by alinbarla87** [eddiesigner/liebling#283]
How do I activate the membership on liebling theme? when I activate the feature from admin dashboard and set some posts as membersip only they just disappear. I there a way to do it? By the way tx for your effort you did an amazing job!!!!

**Comment by eddiesigner** [comment]
Thanks for your interest in this theme :) but I'm afraid to tell you this is something I will not work on for now. I'm closing this issue since this was already discussed [here](https://github.com/eddiesigner/liebling/issues/70).
