### ISSUE TITLE
Featured images are too big

### ISSUE THREAD

**Issue by deanp70** [eddiesigner/liebling#286]
Thanks for this awesome theme!

I think I found a bug that I am trying to fix. If I use an Unsplash featured image, it doesn't load the responsive version.
This is very bad for SEO, as raw images can weigh 20MB which is super heavy and is punished by the Google algorithm.

The culprit seems to be that the featured image is loaded using the `background-image` attribute, which escapes the URL coming from `{{img_url background size="xl"}}` where all the added queries are ignored, so the original resolution is loaded.

Not sure there is a good way to continue using the `background-image` property, so I'm exploring how to have the hero image as and `<img>` tag. If that is something you'd be willing to accept a PR for, I'd be happy to create one when I'm done.

**Comment by eddiesigner** [comment]
Thanks for the feedback but I would encourage you to upload the images from Unsplash **manually** instead of using the Unsplash button directly in the post settings. The problem with that is Ghost doesn't generate smaller versions of those images, Ghost only does that if you upload the image manually, that's why you see the same version of the image no matter the screen size.

There is no issue with using `background-image` and also you will have the same issue even if you use an `<img>`. I don't know if this is really a bug or not but if so, it's unrelated to the theme itself and you should then head to the Ghost forum to ask for a solution for it ;)

**Comment by deanp70** [comment]
Thanks for the input. Most of the time, that's what I'm doing exactly because of the reason you mentioned. What I am discussing might be a bit of an edge case, but I've already solved it, so you might still want it as a PR (and BTW there is a PR in the original ghost to request different resolutions from the Unsplash API so that might become an issue).

In some cases (we have multiple writers submitting to our blog), someone would make a mistake and use an Unsplash image. In the default ghost them, that would result in requesting a 2000px wide image from Unsplash. That's big but definitely limited in size in most cases. In the Liebling theme due to problematic escaping, it would request the full resolution image, which might sometimes be significantly larger (20MB image is not an exaggeration). I fixed this by changing the code in `hero.hbs` as following:

```
{{#if background}}
  {{#contentFor "herobackground"}}
      <style>
        .m-hero__picture {
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .m-hero__picture img{
          width: 100%;
          height: 100%;
          object-fit: cover;
        }
      </style>
  {{/contentFor}}

  <section class="m-hero with-picture" data-aos="fade">
    <div class="m-hero__picture {{#is "post"}}in-post{{/is}}">
      <img class="post-image"
           srcset="{{img_url background size="s"}} 300w,
            {{img_url background size="m"}} 600w,
            {{img_url background size="l"}} 1000w,
            {{img_url background size="xl"}} 2000w"
           sizes="(max-width: 600px) 600px, (max-width: 1000px) 1000px, 2000px"
           src="{{img_url background size="l"}}"
           alt="{{title}}"
      />
    </div>
{{else}}
  <section class="m-hero no-picture {{#is "post"}}in-post{{/is}}" data-aos="fade">
{{/if}}
``` 

This solves it for all cases and has the added benefit of probably supporting the update of Ghost that will include multiple resolution requests from Unsplash :). Please let me know if you'd like me to make a PR out of this, it would be my pleasure.

**Comment by eddiesigner** [comment]
I see, a PR is more than welcome :) I would be happy if you do so!

Note: I use background images rather than images with `object-fit: cover;` because that doesn't work on IE 11, but that shouldn't be a real problem nowadays.

**Comment by deanp70** [comment]
PR opened!
