### ISSUE TITLE
Feature Request: Support LinkedIn Sharing

### ISSUE THREAD

**Issue by productceo** [eddiesigner/liebling#288]
While Facebook and Twitter are great communities, many writers seek to build a connection with audience on the professional network. 

Can Liebling support sharing post on LinkedIn? 

(Also Reddit if it is easy)

**Comment by eddiesigner** [comment]
I want to keep the sharing bar as simple as possible, if I add more buttons it will get crowded easily and soon it won't be enough space specially on mobile. If you want to add buttons for Linkedin and Reddit you can edit `post.hbs` and look for this piece of code:

![CleanShot 2020-11-30 at 19 13 16](https://user-images.githubusercontent.com/1477503/100647674-2533b000-3340-11eb-82bf-ba7ee85eee9e.png)

Then you can simply reuse one of the sharing links from there. The theme comes with a bunch of social icons so you can use `<span class="icon-linkedin" aria-hidden="true"></span>` or `<span class="icon-reddit" aria-hidden="true"></span>` for your links.

Linkedin example:

```html
<a href="https://www.linkedin.com/sharing/share-offsite/?url={{url absolute='true'}}" class="m-icon-button filled in-share" target="_blank" rel="noopener" aria-label="Linkedin">
  <span class="icon-linkedin" aria-hidden="true"></span>
</a>
```

Reddit example:

```html
<a href="http://www.reddit.com/submit?url={{url absolute='true'}}&title={{encode title}}" class="m-icon-button filled in-share" target="_blank" rel="noopener" aria-label="Reddit">
  <span class="icon-reddit" aria-hidden="true"></span>
</a>
```
