### ISSUE TITLE
Feature Request: More Pleasing Design for Text Heavy Blogs

### ISSUE THREAD

**Issue by productceo** [eddiesigner/liebling#289]
The Liebling design assumes blog has content with visuals (i.e. cover images). Many Ghost users write text-only articles, and we can see this from popularity of Medium-like minimal themes. 

Liebling does not look so great if a post has no cover art. Can there be a more pleasing design for text-only articles? Either trigger a more minimal design for posts with no art, or user might choose to toggle entire Liebling theme to be "text-mode" for the article cards. Maybe like Casper but without the images.

**Comment by eddiesigner** [comment]
There are different types of themes that focus on different needs, you can find themes for magazine-link content, minimal, photography, etc., I can't think of a theme that covers all those needs. This theme is not focused on text-only publications, if you want something like that then I would suggest you to look for a minimal (text-focused) theme.
