### ISSUE TITLE
Template isn't uploading to ghost. ¿Is it me?

### ISSUE THREAD

**Issue by ivanesro** [eddiesigner/liebling#290]
This is the last version and it ain't opening in my ghost. When I activate it, it remains the same Casper Default template.

[liebling-master (2).zip](https://github.com/eddiesigner/liebling/files/5633470/liebling-master.2.zip)

**Comment by eddiesigner** [comment]
I don't know where you got that file from but the latest downloadable version is this one: https://github.com/eddiesigner/liebling/releases/download/v.0.8.8/liebling.zip

You can also try to upload another theme and see what happens, if the problem persists then there is something going on with your server o with your Ghost setup.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
