### ISSUE TITLE
Changing the logo and changing the color scheme

### ISSUE THREAD

**Issue by tristor2** [eddiesigner/liebling#297]
Hello.
Tell me how to make a logo change. To have a dark logo when the dark theme is enabled. And light when the theme is light.

**Comment by eddiesigner** [comment]
Unfortunately Ghost doesn't allow to upload two different logos, so for now you have the following options:

1. Don't upload a logo at all so the theme uses your blog title instead, just like you can see in the [demo](https://liebling.eduardogomez.io/), that way the title color can change accordingly.

2. If your logo image is black you can invert its color with css like this:

```html
<style>
[data-theme="dark"] .m-logo img {
  filter: invert(1);
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) .m-logo img {
    filter: invert(1);
  }
}
</style>
```

You can paste that code in your Ghost Admin (Code injection -> Site Header)

3. You can combine your two different logos in the same image and use CSS Sprites to display one logo or another based on the color scheme, you can read more about this technique in [this article](https://css-tricks.com/css-sprites/). This method is a bit hacky and I can't give you a detailed explanation but you can search on the Internet to put all the pieces together.

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
