### ISSUE TITLE
Feature post card is wider than regular posts at certain screen width

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#3]
![Screen Shot 2019-05-14 at 10 58 45 AM](https://user-images.githubusercontent.com/6436149/57720714-44240180-7637-11e9-9ab8-1a77b76a3b95.png)

**Comment by eddiesigner** [comment]
@calvintam236 That was intentional, but maybe it should look like this just on smaller screens so I changed that ;)

**Comment by calvintam236** [comment]
I think it should look better either same width of the rest of the page or using the mobile card design.

**Comment by eddiesigner** [comment]
You're right, I fixed it with the latest release.
