### ISSUE TITLE
cannot show taglist page

### ISSUE THREAD

**Issue by poioit** [eddiesigner/liebling#300]
My ghost version is 3.40.2 
I followed the Wiki to create a "Tags" page, but the content of the Tags list is not showed.
[my taglist page](http://blog.urlaw.com.tw/tags/)
I checked the source, the tags.css is not included. I thought it should trigger automatically to generate the content.
Do you have any idea what go wrong?

**Comment by eddiesigner** [comment]
It seems like you have an old version of this theme, that feature was added in [version 0.7.7](https://github.com/eddiesigner/liebling/releases/tag/v.0.7.7). I would recommend you to download that version or the [newest (0.9.0)](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.0)

**Comment by poioit** [comment]
Yes, I know it is weird. I've read the wiki and already used the 0.9.0
it still doesn't work. 
This is my theme view
![截圖 2020-12-28 上午9 49 17](https://user-images.githubusercontent.com/977497/103233592-57f6a700-48f2-11eb-884d-bd9bd19d719c.png)
This is the tag post. I noticed that there is no template option in the option.
![截圖 2020-12-28 上午9 49 43](https://user-images.githubusercontent.com/977497/103233578-4e6d3f00-48f2-11eb-9200-d1bfdb7bbdaa.png)

**Comment by poioit** [comment]
thanks for your prompt reply. This is my mistake that I created under the posts list not page list.
