### ISSUE TITLE
Posts with no tags cause Query Error: unexpected character in filter at char 7

### ISSUE THREAD

**Issue by lpar** [eddiesigner/liebling#302]
Ran into what turned out to be [this problem discussed on the Ghost forums](https://forum.ghost.org/t/problem-with-filter-by-tags/13262). Every load of a post page resulted in:

```
Error: Query Error: unexpected character in filter at char 7
(tags:[]+id:-)+type:post
-------^
Expecting 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'
```

The culprit turned out to be the related posts section of `post.hbs`. Wrapping the suggested `if` around the `get` block seems to fix it:

```
      {{!-- Related posts --}}
{{#if post.tags.length}}
      {{#get "posts" limit="3" filter="tags:[{{tags[*].slug}}]+id:-{{id}}" include="tags,authors" as |related|}}
     ...rest of block...
{{/if}}
```

**Comment by eddiesigner** [comment]
Thanks for the heads up! This should be fixed in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.1).

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
