### ISSUE TITLE
reduce image height

### ISSUE THREAD

**Issue by os72** [eddiesigner/liebling#305]
hello! we love this theme, thank you!

how could we reduce the image height for:
- the main publication cover image (main page)
- the post image in the post page

basically we'd like to make those images occupy just a bit less vertical space

thank you!

**Comment by eddiesigner** [comment]
Hi,

You can do that by heading to Admin panel -> Code injection and injecting the following code into the Site Header section:

```html
<style>
.m-hero {
  min-height: 365px; /* The height you want for mobile */
}

@media only screen and (min-width: 48rem) {
  .m-hero {
    min-height: 400px !important; /* The height you want for desktop */
  }
}
</style>
```

**Comment by os72** [comment]
Thank you!

**Comment by os72** [comment]
BTW, if we wanted this as part of the theme, would there be a place to customize it there? Thanks again
