### ISSUE TITLE
Mobile navigation include subnav without dropdown

### ISSUE THREAD

**Issue by jonahlosh** [eddiesigner/liebling#307]
Is there any way that you can have the sub nav from desktop version to appear as main nav when on mobile instead of there being a "More" dropdown? So in the main nav for mobile, all of the nav links would be visible, versus in desktop some would be in the dropdown. Thanks!

**Comment by eddiesigner** [comment]
You could edit the partial template `header.hbs` and replace the following code:

```html
{{#if @site.secondary_navigation}}
  <li class="more">
    <span>
      <a href="javascript:void(0);" class="js-open-secondary-menu">
        {{t "More"}}
        <span class="icon-chevron-down" aria-hidden="true"></span>
      </a>
    </span>
  </li>
{{/if}}
```

with this code:

```html
{{#if @site.secondary_navigation}}
  <li class="more only-desktop">
    <span>
      <a href="javascript:void(0);" class="js-open-secondary-menu">
        {{t "More"}}
        <span class="icon-chevron-down" aria-hidden="true"></span>
      </a>
    </span>
  </li>
  <li class="mobile-secondary-menu">
    {{navigation type="secondary"}}
  </li>
{{/if}}
```

Then inject the following styles in your Ghost Admin (Code injection -> Site Header):

```html
<style>
.mobile-secondary-menu .m-secondary-menu li {
  font-size: 1.125rem;
}

.mobile-secondary-menu .m-secondary-menu a {
  padding: 0;
}

@media only screen and (min-width: 48rem) {
  .mobile-secondary-menu {
    display: none !important;
  }
}
</style>
```

I won't implement that in the theme because I think is better to keep the mobile menu short specially if the secondary menu has a lot of items.

**Comment by jonahlosh** [comment]
Awesome, thank you!
