### ISSUE TITLE
The interface of v.0.27

### ISSUE THREAD

**Issue by hiensarahly** [eddiesigner/liebling#31]
Hi Eddie! Have you ever experienced this issue with the latest version update?

I'm having this interface after updating to version 0.2.7:

![2019-08-23_200027](https://user-images.githubusercontent.com/21299841/63594529-db0e3b80-c5e0-11e9-981b-bf9b6a9a2ca7.png)

![2019-08-23_200120](https://user-images.githubusercontent.com/21299841/63594538-df3a5900-c5e0-11e9-8f6d-849c5fba0904.png)

PS: So I was a bit nervous contributing for the first time, never mind the getting famous joke! :D

**Comment by hiensarahly** [comment]
This is version v.0.2.6, still working fine

![2019-08-23_200842](https://user-images.githubusercontent.com/21299841/63594895-dbf39d00-c5e1-11e9-8ceb-6f4dbee7f8dd.png)

**Comment by eddiesigner** [comment]
Hi @hiensarahly! From version 2.0.7 you have to download the file `liebling.zip` from the releases page, it looks to me like you downloaded the wrong file, maybe you downloaded the source code zip file instead.

This is the correct link: https://github.com/eddiesigner/liebling/releases/download/v.0.2.7/liebling.zip 😄

PS: Don't worry about the joke! ;)

**Comment by hiensarahly** [comment]
Wow, thank youu! I didn't know that. I always download the source code, lol. But it is working nicely now Appreciate it :)

**Comment by eddiesigner** [comment]
You're welcome ;)
