### ISSUE TITLE
Better visibility for comments

### ISSUE THREAD

**Issue by orafaelfragoso** [eddiesigner/liebling#311]
This is a feature request that I would love to help but I have no clue on how to fix it.

Right now the comments are hidden by default and the UX is not clear enough. I ran some research among friends and they never seem to find the comments without me pointing them in the right direction.

This massively causes an impact on engagement.

Does that make sense?

**Comment by eddiesigner** [comment]
I decided to display the comments without having to click a button first, that should fix this issue. Please download the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.2) and see how it goes.

**Comment by curiousdungbeetle** [comment]
I had the same issue and couldn't solve it. This is helpful. Thank you!

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
