### ISSUE TITLE
Round Progress Bar Distorted In Safari

### ISSUE THREAD

**Issue by sereneinserenade** [eddiesigner/liebling#314]
First of all, thank you very much for creating this theme, it's my savior! 🚀 🚀 🚀 🚀 

I wanted to report distorted round progress bar around the `go to top` button in safari.

This is how it looks in safari, latest version of Safari, MacOS BigSur, latest version. And Liebling theme, 0.9.1 version
<img width="236" alt="image" src="https://user-images.githubusercontent.com/45892659/104808394-351b2c80-57e6-11eb-9918-57de01afa823.png">

This is how it looks in Chrome,
<img width="173" alt="image" src="https://user-images.githubusercontent.com/45892659/104808404-4d8b4700-57e6-11eb-9dee-3ee58adbeda0.png">

it can be seen here. https://webdevjeet.me/2020-12-git-basics/#command-git-diff

**Comment by eddiesigner** [comment]
Hi, thanks for the kind words!

I couldn’t reproduce the issue, maybe you can try to empty the cache?

This is how it looks on the latest version of Safari running on the latest version of macOS Big Sur:

<img width="1792" alt="CleanShot 2021-01-16 at 13 48 51@2x" src="https://user-images.githubusercontent.com/1477503/104812299-969cc480-5801-11eb-8850-fc03b1cc2ddc.png">

I also noticed you made some customisations, could be that the issue? It happens to you in the [demo website](https://liebling.eduardogomez.io/) as well?

**Comment by sereneinserenade** [comment]
Thanks for the blazing fast reply.

Yess, I also think that the customizations might've messed up the styles, but anyways I'm gonna update soon to 0.9.2 and will debug this issue one more time then.

**Comment by eddiesigner** [comment]
I'm closing this issue for now, please feel to reopen it if needed.
