### ISSUE TITLE
m-article-card__timestamp changes needed

### ISSUE THREAD

**Issue by morbishreejioff** [eddiesigner/liebling#316]
Hi,
Please kindly give a path where the m-article-card__timestamp class can be found?
Want to hide x hour to post and x min. read section

Please assist on this,
Many Thanks

**Comment by eddiesigner** [comment]
Hi,

if you want to hide that element you can inject the following styles in your Ghost Admin (Code injection -> Site Header)

```html
<style>
.m-article-card__timestamp {
  display: none;
}
</style>
```

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
