### ISSUE TITLE
Change styles

### ISSUE THREAD

**Issue by mariocnovoa** [eddiesigner/liebling#321]
Hello!
I'm very new to all this and I'm having some newbie problems :
I want to make changes in the scss sheets, but then those changes don't update in the css sheets. What do I have to do to make that happen?
I'm sorry for the silly question

Best regards!

**Comment by arshyn-t** [comment]
Read [this](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) wiki, it describes how you can develop a theme with docker, briefly speaking after `npm run docker-watch` you have to change styles in src/sass folder, then `docker-compose restart` after `npm run production` you'll see changes take place

**Comment by eddiesigner** [comment]
In general you don't need to touch those files unless you want to make deeper changes, if that's the case then you can follow [this guide](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) to setup a development environment and create a customised version of this theme.

If you only want to change some styles you can do it easily in the Ghost Admin as described in [this page](https://firepress.org/en/what-is-code-injection-in-ghost/#:~:text=The%20Code%20Injection%20allows%20you,and%20or%20a%20javascript%20element.).

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
