### ISSUE TITLE
Zoom out of the post image

### ISSUE THREAD

**Issue by Mansffer** [eddiesigner/liebling#322]
Hi. Is there any way to zoom out on the post image?

I wanted to make it look like the one on the homepage.
![Screenshot_20210128-214536~2.png](https://user-images.githubusercontent.com/57368089/106217647-7206fc00-61b4-11eb-9af4-238618af6d33.png)

Image on post page.
![Screenshot_20210128-214544~2.png](https://user-images.githubusercontent.com/57368089/106218001-36b8fd00-61b5-11eb-8e54-d6e2bf8dfd61.png)

**Comment by eddiesigner** [comment]
The purpose of that component is not to show the whole image or to show the relevant part of the image, this component is rather aesthetic.

The only thing you could do is to play with the height of the component to show more content in certain images.

You can do that by heading to Admin panel -> Code injection and injecting the following code into the Site Header section:

```html
<style>
.m-hero {
  min-height: 365px; /* The height you want for mobile */
}

@media only screen and (min-width: 48rem) {
  .m-hero {
    min-height: 400px !important; /* The height you want for desktop */
  }
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this issue now, please feel free to reopen it if needed.
