### ISSUE TITLE
Subscription button doesn't work

### ISSUE THREAD

**Issue by mehdihadeli** [eddiesigner/liebling#326]
Hi,
@eddiesigner I do the same instruction in your document
[How-to-enable-subscribers](https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers)
But when I click on the subscribe button to send an email, I don't get any email !
Actually, register an email will not add to the Members list.
Should I do other prerequisites?

**Comment by mehdihadeli** [comment]
Hi,
My issue resolve, the problem was because of integration my account with Mailchimp. I change subscribe button code to connect Mailchimp api.

**Comment by Leovaldez42** [comment]
Hi @mehdihadeli I am also facing the similar issue, have you self hosted the website or used ghost pro?
