### ISSUE TITLE
Tags in More button are displayed in alphabetical order

### ISSUE THREAD

**Issue by magicgg91** [eddiesigner/liebling#327]
Hello,
In More (...) button, tags are displayed in alphabetical order.
I would like to see them in most-used order, or at least chosen tags if possible.

Thanks.

**Comment by eddiesigner** [comment]
Hi,

you can edit the file `/partials/header.hbs` and replace [line 99](https://github.com/eddiesigner/liebling/blob/master/partials/header.hbs#L99) with this:

```html
{{#get "tags" limit="10" include="count.posts" order="count.posts desc"}}
```

**Comment by magicgg91** [comment]
Thanks a lot, it works perfectly, as wanted 👍
