### ISSUE TITLE
Suggestion: Javascript License Table

### ISSUE THREAD

**Issue by inknos** [eddiesigner/liebling#33]
It would be great to have a clear indication of all the libraries and licenses used in this theme.
My suggestion is to follow [this guide](https://www.gnu.org/software/librejs/free-your-javascript.html) in order to provide a *javascript license table* that properly lets you include and release external and embed code. 
I am forking the repo at the moment in order to add the js table to my website.

**Comment by inknos** [comment]
I added a pull request. My solution implements a static page with a table containing all the JS libraries and their licenses. For inline JS as in `default.hbs` tags are necessary.

**Comment by eddiesigner** [comment]
Thank you for your PR, it's already merged ;)
