### ISSUE TITLE
How can I detect dark/light theme in hbs files?

### ISSUE THREAD

**Issue by aonghas** [eddiesigner/liebling#331]
Hi there,
I have a dark and light version of my logo and I want to detect whether or not the site is in light or dark mode so I can render the correct logo in the hbs files. How would I do that?

Thanks!

**Comment by eddiesigner** [comment]
This might help you: https://github.com/eddiesigner/liebling/issues/297

**Comment by eddiesigner** [comment]
I'm closing this issue now, please feel free to reopen it if needed.
