### ISSUE TITLE
How can i translate this string

### ISSUE THREAD

**Issue by partizan007** [eddiesigner/liebling#333]
How can i translate this string "More"?
![изображение](https://user-images.githubusercontent.com/25349460/108506768-04855180-72c2-11eb-9b53-694aa9bda3f4.png)

**Comment by eddiesigner** [comment]
You can open the translation file for the language you're using with a text/code editor and replace the following line:

````
"More": "More",
````

with your own text like this:

````
"More": "Your own text goes here",
````

All the json files with translations are located in the `/locales/` directory. If you're using Ukrainian for example then you should modify the file `uk.json`

Save your changes and upload the theme again.

**Comment by eddiesigner** [comment]
I will this issue now, please feel free to reopen it if needed.
