### ISSUE TITLE
text-align: justify

### ISSUE THREAD

**Issue by mihaiguyard** [eddiesigner/liebling#334]
Hello,

Despite my attempts to solve this problem, I cannot put the correct CSS code to align the text (justify) and adapt its size (in code injection and {{ghost_head}}) ... Do you have any idea?

<style>
.page__content, .post__content {
   text-align: justify;
}
</style>
<style>
.page__content, .post__content  {
   font-size:20px;
}
</style>

Thanks !
Mihai Guyard
mihai.guyard@orange.fr

**Comment by eddiesigner** [comment]
Hi,

That's because the classes `.page__content` and `.post__content` don't exist in this theme. If you want to override some styles you should use `.l-post-content` instead.

To justify text you could use:

```html
<style>
  .l-post-content {
    text-align: justify;
  }
</style>
```

And to change the font size you could use:

```html
<style>
  .l-post-content p {
    font-size: 20px;
  }
</style>
```

**Comment by eddiesigner** [comment]
I will close this issue now, please feel free to reopen it if needed.
