### ISSUE TITLE
 Google Programmable Search

### ISSUE THREAD

**Issue by ever-blogger** [eddiesigner/liebling#336]
I'm trying to replace search icon to Google Programmable Search, however I couldn't find where to replace it.

**Comment by eddiesigner** [comment]
I think is better if you add the Google search box in the search overlay, in order to do that you can modify the [search.hbs](https://github.com/eddiesigner/liebling/blob/master/partials/search.hbs) template file. That would require fewer changes and it will work for mobile and desktop.

**Comment by ever-blogger** [comment]
Thank you, I had tried but it still not works really well with my code below:


<div class="m-search js-search" role="dialog" aria-modal="true" aria-label="Search">
  <button class="m-icon-button outlined as-close-search js-close-search" aria-label="Close search">
    <span class="icon-close" aria-hidden="true"></span>
  </button>
  <script async src="MY Google Programmable Search"></script>
<div class="gcse-search"></div>
</div>

**Comment by ever-blogger** [comment]
Thank you, it's working fine on my website with your advice. However, I'm not sure why the website is generate "#gsc.tab=0" in my Address bar after I clicked Search, and it did not disapear after exit Search, it's probably something wrong with my code
[search.hbs](https://github.com/ever-blogger/liebling/blob/master/partials/search.hbs)

**Comment by eddiesigner** [comment]
Don't think that's really related with your code or with the theme, if you [google it](https://www.google.com/search?q=%23gsc.tab%3D0&oq=%23gsc.tab%3D0&aqs=chrome..69i57.293j0j4&sourceid=chrome&ie=UTF-8) you can see there are some answers to that problem.

**Comment by ever-blogger** [comment]
Noted. Thanks
