### ISSUE TITLE
Change header and footer color

### ISSUE THREAD

**Issue by cerf203** [eddiesigner/liebling#339]
Can I change the color of the header and footer using code injection?
I'd like you to have a black background with white text.

**Comment by eddiesigner** [comment]
Sure, you can change the color using code injection.

To change the background color of the header you can inject this:

```html
<style>
.m-header {
  background-color: #111 !important; /* Or the color you prefer */
}

.m-header * {
  color: white !important;
}

.m-nav__right:before {
  linear-gradient(90deg, rgba(17, 17, 17, 0), rgba(17, 17, 17, 1)); /* #111 in rgba */
}
</style>
```

If you want to change more things in the header you can inspect the elements with the dev tools to find the classes that you would need to overwrite.

To change the background color of the footer you can inject this:

```html
<style>
.m-footer {
  background-color: #111; /* Or the color you prefer */
}
</style>
```

**Comment by cerf203** [comment]
Hi the header looks like a faded white line how can I fix this? and the letters are not visible in the drop-down menu.
I give you the link to my blog in case you like to review it: cesarreyes.pro
Thanks for the support

**Comment by eddiesigner** [comment]
I updated the code in my previous comment, you can use that instead.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
