### ISSUE TITLE
More Link in header opens a New Blank Tab

### ISSUE THREAD

**Issue by darkpanda08** [eddiesigner/liebling#340]
Hello,
After adding the script for "opening the external links in a new tab by default", when I click on the More link in the header it opens a new blank tab.

Ghost Version 4.0.1

**Comment by smhawkes** [comment]
Try this script, works for me.
``<script>
	var links = document.querySelectorAll('a');
	links.forEach((link) => {
		var a = new RegExp('/' + window.location.host + '/');
		if(link.href.indexOf("javascript") == -1){
			if(!a.test(link.href)) {
				link.addEventListener('click', (event) => {
					event.preventDefault();
					event.stopPropagation();
					window.open(link.href, '_blank');
				});
			}
		}
	});
</script>

**Comment by darkpanda08** [comment]
Thanks, @smhawkes. This works for me as well.
