### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by weeyin83** [eddiesigner/liebling#342]
I notice on the live demo that there is a search facility built into this theme, however when I apply it to my site the search doesn't seem to be there.  

Is there something I need to do or turn on to make it work?  I am running Ghost 4.0 within Ghost's own hosting platform. 

Thanks

**Comment by darkpanda08** [comment]
You can read here how to enable the search feature in this theme: https://github.com/eddiesigner/liebling/wiki/How-to-enable-search
