### ISSUE TITLE
Disable Newsletter

### ISSUE THREAD

**Issue by weeyin83** [eddiesigner/liebling#344]
How can I disable the newsletter feature? Is it something I need to edit within the template or through Ghost settings?

**Comment by eddiesigner** [comment]
Liebling is not yet optimised for Ghost 4, I'm working on that currently and this week I will release a new version where you will be able to remove the newsletter feature easily, for now you can hide it by injecting the following styles in the Ghost Admin (Settings -> Code injection -> Site header):

```html
<style>
.m-subscribe-section,
a[href*="newsletter"] {
  display: none !important;
}
</style>
```

**Comment by eddiesigner** [comment]
I just released a new version which is optimised for Ghost 4, I encourage you to download it, you can get it from here: https://github.com/eddiesigner/liebling/releases/tag/v1.0.0

I also updated the Newsletter documentation, I recommend you to take a look at it: https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers#ghost-4

**Comment by weeyin83** [comment]
Thank you @eddiesigner
