### ISSUE TITLE
Multiple Authors

### ISSUE THREAD

**Issue by echilundo** [eddiesigner/liebling#349]
Hey there!

Great work on the theme!

For multiple authors, I suggest changing this on post.hbs (lines 117-120).

**FROM:**

              {{#has author="count:>1"}}
                <p class="m-small-text in-author-along-with">
                  {{authors separator=", " prefix=(t "Among with no break line") from="2"}}
                </p>

**TO:**

              {{#has author="count:>1"}}
                <p class="m-small-text in-author-along-with">
                  {{authors separator=", " prefix=(t "With ") from="2"}}
                </p>

or

              {{#has author="count:>1"}}
                <p class="m-small-text in-author-along-with">
                  {{authors separator=", " prefix=(t "Along with ") from="2"}}
                </p>

The English in these two sounds much more natural.

**Comment by eddiesigner** [comment]
Yeah, I think something like that makes sense, would you mind to open a PR? 😄

Basically it's just matter of changing the values on the **right** side of the following translations in the `locales/en.json` file.

```json
"Among with": "<br>Among with ",
"Among with no break line": "Among with ",
```

**Comment by eddiesigner** [comment]
I'm closing this issue now since I already implemented those changes in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v1.0.3).
