### ISSUE TITLE
Quick questions from Newb

### ISSUE THREAD

**Issue by 22lane5** [eddiesigner/liebling#357]
Hi all!

I really like this theme so far. I was wondering how to do a couple of things ( I am not very good at coding)

1. Add a linkedin icon in the footer next to the facebook/twitter/rss. 
2. Right now anything in the second submenu/more option at the top of the page also appears in the footer. How do have it so it does not go to the footer as well. I would also be fine if it put all of the menu items from the top in the footer, not just the second menu/more. 

Thank you!

**Comment by eddiesigner** [comment]
Hi,

1. You can add the following code in the file `partials/footer.hbs` after [line 25](https://github.com/eddiesigner/liebling/blob/master/partials/footer.hbs#L25):

````hbs
<a href="YOUR_LINKEDIN_URL" target="_blank" rel="noopener" aria-label="Linkedin">
  <span class="icon-linkedin" aria-hidden="true"></span>
</a>
````

2. In the same file you can remove the following code:

````hbs
{{#if @site.secondary_navigation}}
  <nav class="m-footer__nav-secondary" role="navigation" aria-label="{{t "Secondary menu in footer"}}">
    {{navigation type="secondary"}}
  </nav>
{{/if}}
````

**Comment by 22lane5** [comment]
Thank you so much!
