### ISSUE TITLE
Hero as feature image

### ISSUE THREAD

**Issue by tomotvos** [eddiesigner/liebling#359]
From what I can tell, the feature image of a post is always used in "hero" style on a page. Where the featured image is not 16:9, or otherwise inappropriate for a "hero" spot, is there a way to turn that off? There is mention in the README of "Support for normal, wide and full images in posts", but I cannot find how to do that. I would like the feature image to appear in the post body, full size, as-is.

If easy, please point in the right direction and I can mod the template and create a PR.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
