### ISSUE TITLE
Missing images and icons from theme

### ISSUE THREAD

**Issue by alexrmacleod** [eddiesigner/liebling#36]
Love the theme looks great. 

I installed your theme like this https://www.ghostforbeginners.com/how-to-install-a-ghost-theme/ 

No images and icons what am I missing?

**Comment by eddiesigner** [comment]
What file did you download?

To get the latest version please head over the [releases](https://github.com/eddiesigner/liebling/releases) page and download the file `liebling.zip` of the latest release.

By now the latest version is 0.2.8 so you need to download [this file](https://github.com/eddiesigner/liebling/releases/download/v.0.2.8/liebling.zip).
