### ISSUE TITLE
Problem with Docker Missing Script

### ISSUE THREAD

**Issue by 22lane5** [eddiesigner/liebling#362]
Hi all, 

I was attempting to use docker to develop the theme. However after entering the `npm run docker-watch` into my macs terminal, it says it is missing the script "docker-watch" .
[2021-04-18T18_27_52_075Z-debug.log](https://github.com/eddiesigner/liebling/files/6331976/2021-04-18T18_27_52_075Z-debug.log)

**Comment by eddiesigner** [comment]
Hi,

please make sure to run all the commands in the `src` directory.
