### ISSUE TITLE
Some characters with diacritics look weird

### ISSUE THREAD

**Issue by emilian-mateut** [eddiesigner/liebling#364]
Hi! I like the Liebling theme so far, and I plan to use it for my new blog. It's really nice!

For the moment I'm playing with it and I'm getting familiar with Ghost. 

I've written some dummy articles in Romanian (my native language) and I've noticed that some of the Romanian special characters look like they have a different font and size as the others.

You can see the differences in this screenshot:
![characters-with-diacritics](https://user-images.githubusercontent.com/22546649/115993329-f4982f80-a5da-11eb-8c80-db230a0aff62.png)

When I write the post in the Ghost admin all the characters look good. The difference is only present after publishing.

I've checked the font `Source Sans Pro` in Google Docs and Microsoft Word and, except the diacritics., there is no difference between normal and special characters.

For now I've found a workaround: I've removed `Source Sans Pro` from `font-family` and I keep only the others: `Helvetica,Arial,sans-serif`. 

With the workaround the look&feel is not changed very much so I can use the theme, but I think it would be nice to have this fixed.

I am not able to fix this myself, but I have found a [list](https://maximilian.schalch.de/2018/05/complete-list-of-european-special-characters/) with most of the Latin special characters and I've added the normal one near each of them, to make the comparison easier. I hope this will help for testing. How to test: create a Ghost post that contains this text, publish and then check it on the published version.
```
AÄäa AÀàa AÁáa AÂâa AÃãa AÅåa AǍǎa AĄąa AĂăa Ææa AĀāa

CÇçc CĆćc CĈĉc CČčc

DĎđd DĐďd DðdD

EÈèe EÉée EÊêe EËëe EĚěe EĘęe EĖėe EĒēeE

GĜĝg GĢģg GĞğg

HĤĥh

IÌìi IÍíi IÎîi IÏïıi IĪīi IĮįi

JĴĵj

KĶķk

LĹĺl LĻļl LŁłl LĽľl LĿŀl

NÑñn NŃńn NŇňn NŅņn

OÖöo OÒòo OÓóo OÔôo OÕõo OŐőo OØøo OŒœo

RŔŕr RŘřr

SẞßŚśs SŜŝs SŞşs SŠšs SȘșs

TŤťt TŢţt TÞþt TȚțt

UÜüu UÙùu UÚúu UÛûu UŰűu UŨũu UŲųu UŮůu UŪūu

WŴŵw

YÝýy YŸÿy YŶŷy

ZŹźz ZŽžz ZŻżz
```

That's it. I hope this will be helpful.

Thanks again for creating and sharing the Liebling theme. 

Best Regards
Emilian

P.S. This my very first github issue. I hope the description is clear and it will be useful.

**Comment by eddiesigner** [comment]
Hi!

In the [latest release](https://github.com/eddiesigner/liebling/releases/tag/v1.0.3) I added support for Latin Extended which most likely will fix this issue, please download it and then follow [this guide](https://github.com/eddiesigner/liebling/wiki/How-to-use-a-different-character-encoding) to learn how to use a different character encoding (latin extended in your case).

**Comment by emilian-mateut** [comment]
Hi @eddiesigner! 

I've pulled the latest release, I've changed it to use the latin-ext asset and it works like a charm.

Thank you!
