### ISSUE TITLE
Unable to install theme from Ghost Marketplace

### ISSUE THREAD

**Issue by Yosemike** [eddiesigner/liebling#366]
Hey, I have tried to install Liebling from Ghost Marketplace. When I was redirected to my Ghost Admin, I clicked the Install button. An error message popped up (as attached) and it said "Liebling failed to install. Supplied GitHub theme does not exist or is inaccessible".
![Image 02-05-2021 at 2 46 PM](https://user-images.githubusercontent.com/66622246/116804890-28cc9c80-ab55-11eb-822b-516312ccd32a.jpg)

**Comment by eddiesigner** [comment]
Hi,

thanks for the report, I will contact the Ghost support team since I don't know how they handle the direct installs, hopefully they can find a solution.

For now, you can install the theme manually just like any other theme.

**Comment by eddiesigner** [comment]
The Ghost team just told me the issue is fixed 🎉
Can you please try again?

**Comment by Yosemike** [comment]
Hey yes! Thanks Eddie.
