### ISSUE TITLE
Tertiary Navigation for Languages?

### ISSUE THREAD

**Issue by Arberoo** [eddiesigner/liebling#367]
Hello,

I managed to setup multi-language support for our blog, https://blog.cakedefi.com - the German and Italian versions can be found under the URL https://blog.cakedefi.com/de and https://blog.cakedefi.com/it respectively, easily manageable with #tags 

The issue currently however is that there is no navigation to select the blog language. A user would have to manually type in the /de or /it URL.. not very user-friendly.

I now wanted to setup a "language" dropdown menu in the navigation, however only can edit a "primary" navigation (where everything directly appears in the navigation bar) or a "secondary" navigation, where every link is selectable after clicking on "More" in the bar.

Question: Is there a way to setup a "tertiary" navigation, that I can call "Select Language" instead of "More" ?

If not, is there a way to change the wording of the secondary navigation from "More" to "Select Language"? 

Thanks very much in advance.

**Comment by eddiesigner** [comment]
In your case I would use the secondary navigation for those links. You can change the string "More" like this:

1. Unzip the theme file.

2. Open the file `locales/en.json` with a text/code editor.

3. Search for the following line:

```json
 "More": "More",
```

4. Replace the text on the **right side** with yours and save your changes.

You might also want to do the same with the files `de.json` and `it.json`.

5. Zip the theme folder and upload it again.

**Comment by Arberoo** [comment]
Worked perfectly, thanks.
