### ISSUE TITLE
Hiding tittle, description, and newsletter on homepage 

### ISSUE THREAD

**Issue by trvic3** [eddiesigner/liebling#376]
Hi,

Thank you for this awesome theme, you really did a great job !

Can you tell me how can we hide in the homepage, the tittle, description, and newsletter button altogether ?

I saw how to hide newsletter button but not the other elements with code injection. 

Little precision, the background image shall stay.

Thank you!

**Comment by eddiesigner** [comment]
Hi,

You can inject the following code:

```html
<style>
.home-template .m-hero__content {
	display: none;
}
</style>
```

**Comment by trvic3** [comment]
Hi, works great! Many thanks !
