### ISSUE TITLE
Publication logo size issue

### ISSUE THREAD

**Issue by thefarazxr** [eddiesigner/liebling#377]
MY LOGO dimensions are 600x72px but stil it looks very small!

**Comment by eddiesigner** [comment]
That was already discussed here: https://github.com/eddiesigner/liebling/issues/233

You can inject the following code in the Ghost Admin:

```html
<style>
.m-logo {
	height: 25px; /* Change the height as you prefer */
}

.m-logo img {
	max-width: 150px; /* Change the max-width as you prefer */
}
</style>
```

Btw, I wouldn’t recommend to use a logo of that size. it's just too big, it won’t look good.
