### ISSUE TITLE
Changing hyperlink colors

### ISSUE THREAD

**Issue by trvic3** [eddiesigner/liebling#379]
Hello 👋 

Is it possible to change the default hyperlink color by injecting code and put a standard color of let's say green for all the hyperlinks ?

Thank you in advance for your time and have a great day.

**Comment by eddiesigner** [comment]
Hi,

What links do you mean? Links in post content? or absolutely ALL the links everywhere? I wouldn’t recommend to do the second since there are multiple types of links (nav links, buttons, tags, post cards, etc.) and no all of them would look good.

**Comment by trvic3** [comment]
Hello,
In post content mostly yes :).
Thank you

**Comment by eddiesigner** [comment]
You can inject the following style:

```html
<style>
.l-post-content a {
	color: green; /* You can use your desired color here */
}
</style>
```

**Comment by trvic3** [comment]
Thank you! Works perfectly!
