### ISSUE TITLE
How to edit the footer contents or add some other links.

### ISSUE THREAD

**Issue by saugat-rimal** [eddiesigner/liebling#380]

**Comment by eddiesigner** [comment]
To edit the footer please do the following:

1. Unzip the theme folder
2. Open the file `partials/footer.hbs` with a text/code editor
3. Implement your changes
4. Save the file, zip the theme folder and upload it again.

If you just want to add more navigation links you can add them in the Ghost Admin (Secondary Navigation).

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
