### ISSUE TITLE
RSS Error

### ISSUE THREAD

**Issue by jameshrose** [eddiesigner/liebling#386]
Hi bro, thank you for your amazing theme. But there is something wrong with my RSS page https://b2cstory.com/rss/, I think this is because the contents of my blog are in Chinese.
Since I'm not a coding expert, I have no idea how to fix this problem. Could you please do me a favor? Many thanks!
<img width="606" alt="iShot2021-06-17 11 04 02" src="https://user-images.githubusercontent.com/80946728/122324672-c4766880-cf5b-11eb-8a01-3aa3f2a84444.png">

**Comment by eddiesigner** [comment]
Hi,
Thanks for using Liebling!

However, the theme is not responsible of generating the RSS, that's something that Ghost itself is responsible for. I would suggest to ask for help in [the forums](https://forum.ghost.org/), I'm sure someone from the Ghost staff will help you.

**Comment by jameshrose** [comment]
Thank you for your advice and hope you have a nice day!

**Comment by eddiesigner** [comment]
Thanks, you too!
