### ISSUE TITLE
Customizable 404

### ISSUE THREAD

**Issue by schniewmatz** [eddiesigner/liebling#388]
Hi @eddiesigner,

First of all thank you very much for this awesome theme, I really like it :)

The 404 page for me is a great place to add some easteregg to a website.
Could you maybe add a wiki article on how to e.g. add a custom image to the 404 page?
I only know some very basics in web design, and simply adding an image tag within the main of error-404.hbs yields strange results (picture shifted to the very right in Firefox, text over image, etc.), so I definitely need some advice there...

Thank you :)

**Comment by eddiesigner** [comment]
Hi @schniewmatz 

You could add an image as a background:

1. Unzip the theme folder and open the file `error-404.hbs` with a code editor

2. Add the class `page-404` to the element `<main class="l-fullscreen">`

3. Save your changes, zip the folder and upload the theme again.

4. Inject the following code in the Ghost Admin (Code injection --> Site Header)

```html
<style>
.l-fullscreen.page-404 {
	position: relative;
    background-color: var(--background-color);
}

.l-fullscreen.page-404:before {
	content: '';
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-image: url(https://images.unsplash.com/photo-1624916888948-7015aa2b25b5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);
    background-repeat: no-repeat;
    background-size: cover;
	opacity: 0.6;
	z-index: 0;
	pointer-events: none;
}

.l-fullscreen.page-404 .l-fullscreen__content {
	position: relative;
	z-index: 1;
}
</style>
```

You can use a different image url if you prefer. Then save your changes and it should work.

**Comment by schniewmatz** [comment]
Hi @eddiesigner 

Thank you for the fast response! In general that works and adding the relative path like e.g. `url(/assets/images/404.png)` works as well. Is it possible to also use the {{asset}} helper in CSS?

**Comment by eddiesigner** [comment]
Not really, you can only use the `{{asset}}` helper in Handlebars files. Alternatively you could add the styles directly in the file `error-404.hbs`, that way you can use the `{{asset}}` helper in there.

**Comment by schniewmatz** [comment]
Thanks, that made things clearer :)
