### ISSUE TITLE
Compiling a modified Liebling theme - Gulp file?

### ISSUE THREAD

**Issue by Joshfairhead** [eddiesigner/liebling#389]
Heya,

Thanks for building this lovely theme, I'm particularly fond of the dark mode and trying to make it the default by getting rid of the switcher. I'm new to Ghost theme dev (and webdev in general) so the compilation step has me a bit confused...

I've followed [these](https://www.reddit.com/r/Ghost/comments/g8nuav/liebling_theme_set_default_dark_mode/) instructions to remove the CSS for the light theme but the compile to zip part is throwing me off. It seems Ghost uses Gulp to do this and minify everything to the `app.css` file. So I followed the instructions [here](https://romandesign.co/compiling-ghost-themes/) to get that installed and sorted.

However, once Gulp is installed I try to run it in the Liebling directory, it cant find the required Gulp file. It seems that there isn't one provided? Checking the Caspar theme I find that there is one provided. 

As such I'm wondering how to compile this theme with my small modifications? Do I need to create a Gulp file of some variety or do something different?

Thanks in advance for any help you may be able to provide!

**Comment by eddiesigner** [comment]
Hi,

There is no need to compile the styles to set dark mode as default, you can just inject some styles in the Ghost Admin to override the color variables.

You can follow the example described here: https://github.com/eddiesigner/liebling/issues/242

Basically you need to inject some code like this:

````html
<style>
  :root,
  [data-theme="light"],
  [data-theme="dark"],
  :root:not([data-theme="light"]) {
    --background-color: #111;
  --primary-foreground-color: #ccc;
  --secondary-foreground-color: #fff;
  --primary-subtle-color: #2c2fe6;
  --secondary-subtle-color: #141920;
  --titles-color: #b4b4b4;
  --link-color: #b6b7f6;
  --primary-border-color: #1d1d1d;
  --secondary-border-color: #0f0f0f;
  --article-shadow-normal: 0 4px 5px 5px rgba(0,0,0,0.1);
  --article-shadow-hover: 0 4px 5px 10px rgba(0,0,0,0.1);
  --transparent-background-color: rgba(0,0,0,0.99);
  --footer-background-color: #080808;
  --submenu-shadow-color-opacity: 0.55;
  --button-shadow-color-normal: rgba(10, 10, 10, 0.5);
  --button-shadow-color-hover: rgba(10, 10, 10, 0.5);
  --table-background-color-odd: #050505;
  --table-head-border-bottom: #1d1d1d;
  --toggle-darkmode-button-display-moon: none;
  --toggle-darkmode-button-display-sun: block;
  --toggle-darkmode-background-color: rgba(0, 0, 0, 0.5);
  --header-menu-gradient-first-color: rgba(17, 17, 17, 0);
  --header-menu-gradient-second-color: rgba(17, 17, 17, 0.65);
  }
</style>
````

You can also hide the toggle button with this code:

````html
<style>
.m-toggle-darkmode {
	display: none !important;
}
</style>
````

Hope it helps.

**Comment by Joshfairhead** [comment]
Oh that's quite nice, thank you for the help. In the end I managed to delete the code from the compiled/minified version. If its useful for anyone in the future its forked over here: https://github.com/Joshfairhead/liebling/

**Comment by jclarkdev** [comment]
Hey @eddiesigner , this is convenient - but say i _do_ want to compile in production. How can I do this? I'm used to running `grunt build`

What would be the terminal command to compile after I'm done working on files in production mode?

Thx
