### ISSUE TITLE
Newsletter flow

### ISSUE THREAD

**Issue by chiragnd** [eddiesigner/liebling#391]
Hi,

Only noticed this now since we switched to this theme, but upon activation of a new user as a subscriber, the theme redirects them to /signup (which is obviously a dead link). I couldn’t find any explanation in terms of what we need to create there or why it’s going to /signup, compared to say #/portal/signup which would automatically redirect to the home page but with the user signed-in.

What would be good to know is a) either if there’s a way to change/know what it intends to do with that page or alternatively b) if we update the welcome page fields in settings, will it use those instead, in which we can redirect them to some kind of a members page.

Thanks

**Comment by eddiesigner** [comment]
Hi,

This theme doesn't implement the Members feature and I don't have plans to implement that in the future. If you want to use Members then you should rely on Portal which should handle everything for you.

The signup page doesn't exist in this theme, maybe you should check your Portal settings and change the Welcome page url within the Signup tab.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
