### ISSUE TITLE
Translate membership sign-up boxes

### ISSUE THREAD

**Issue by AulaAstur** [eddiesigner/liebling#392]
Hello,
While the site may be translated into other languages, when a post is "paid-members only" the box is shown in English, ignoring the configured language. 
Do please provide support so this box can be shown in the selected language. If possible, take notes from the rediverge.com (https://rediverge.com/membership/) membership page, and create one for this theme that can be translated too, so the entire sign-up can be done in the same language. This cannot be done through portal, or through the Ghost's sign-up screens set up by default. 

I'm aiming at a sign-up / sign-in flow that can be in the preferred language. Not possible currently.
Thanks in advance,

**Comment by eddiesigner** [comment]
Hi,

What box do you mean? This theme doesn't have a box or something like that to differentiate between paid-member only posts.

Also, you should be aware that this theme doesn't implement the Members feature, you can implement that through Portal though.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.

**Comment by AulaAstur** [comment]
Hello, 
I'm aware that membership feature is a Ghost core feature, and not implemented through the themes.

Anyway, with this new feature, Ghost shows this kind of boxes when access to an article is restricted. (Members only, paid members only).

![imagen](https://user-images.githubusercontent.com/12502166/127353731-2f01a3b1-e953-4886-a914-c5912947e1a3.png)

I have looked into the Ghost Forum, and i have been told that this can be translated from the theme side, so i'm asking to add the strings on the locale file, so this boxes can be shown on the correct language.

I think you should add a "plans" page like https://rediverge.com/membership/, so when a plan is selected, the Stripe page is loaded, instead of the new Portal feature. As Portal cannot be translated, and Stripe does load the webpage based on the clients locale.

This changes will make this theme unbeatable.

**Comment by AulaAstur** [comment]
GitHub does not allow to reopen this issue as I'm not a collaborator and the issue was not closed by myself.
