### ISSUE TITLE
Modify the home page of ghost with Liebling theme

### ISSUE THREAD

**Issue by oliverkostoff** [eddiesigner/liebling#393]
Hi,

After days of research it seems like your theme is a perfect fit for any small portfolio website and is great addition to Casper. I have just one question - how can I create a custom home page ?

I have followed the guide in here:

https://jamesthorne.co.uk/blog/adding-a-custom-homepage-on-ghost/

and create a new home.hbs page. Respectively linked it to the root of the website via the routes.yaml definition. I have verified the routes work as if I intentionally break the Handlebar syntax, Node returns HTTP 400.

My goal is to be able to add small paragraph, controlled by a Ghost Page, between the index image ( with the subscribe button ) and the dynamic post loader under it. I thought that if I put the <article> section from page.hbs to home.hbs in the right div it would work, however this syntax of home.hbs does nothing:

```
...
  <div class="l-content">
                {{#post}}
    <article>
      <div class="l-content">
        <div class="l-wrapper in-post" data-aos="fade-up" data-aos-delay="300">
          <div class="l-post-content">
            <div class="pos-relative js-post-content">
              {{content}}
            </div>
          </div>
        </div>
      </div>
              </article>
          {{/post}}
    <div class="l-wrapper" data-aos="fade-up" data-aos-delay="300">
      <div class="l-grid centered">
        {{#get "posts" filter="featured:true" include="authors,tags" limit="5" as |featured|}}
...
```

I presume I need to do something else, but no idea what. I am relatively new to Handlebars and NodeJS overall. Any assistance would be massively appreciated.

**Comment by eddiesigner** [comment]
Hi,

It seems like you should use `{{#page}} {{/page}}` instead of `{{#post}} {{/post}}`

**Comment by oliverkostoff** [comment]
@eddiesigner you are awesome ! This worked like a charm. Appreciate your time with this.
