### ISSUE TITLE
Spotify widget

### ISSUE THREAD

**Issue by piskedemo** [eddiesigner/liebling#396]
Hi 👋 I'm setting up my newsletter based on Liebling theme, really happy so far! I've encountered one weird malfunction concerning the Spotify embed: 

1) When sending a test email to my OS mail client the email gets stuck, unscrollable: https://user-images.githubusercontent.com/87950540/126913512-dc5ff30c-7e73-4d05-9394-23ecf12f69be.mov

2) I managed to zoom out somehow and you can see how it seems to continue to the right: <img width="912" alt="spotify i stykker" src="https://user-images.githubusercontent.com/87950540/126913546-0b539549-0b9e-40c0-a957-aca83664d868.png">

3) Inside the Ghost editor the embed looks weird as well, kind of continues: https://user-images.githubusercontent.com/87950540/126913570-6844cc4d-7609-4f97-9d98-6d71d7a78e25.mov

Anything to do about this? Thanks a lot :)

**Comment by eddiesigner** [comment]
Hi,
Glad to hear you're happy with the theme!

However, you should contact the Ghost support team because this issue is not related to the theme (themes don't manage emails), you can also ask for help in [the forum](https://forum.ghost.org/).
