### ISSUE TITLE
Subscription button overlaps dark-theme button in mobile screen

### ISSUE THREAD

**Issue by ThiPhu** [eddiesigner/liebling#397]
I didn't know whether this issue has been solved yet or not. But as the title said, the subscription button overlaps the dark-theme button when I switched to the mobile screen 
![image](https://user-images.githubusercontent.com/63137232/127471577-626cdef1-24df-44f2-a96c-3eb17d0e3d7c.png)

**Comment by eddiesigner** [comment]
I think the Portal button shouldn’t overlap the menu actually, the problem is that that button has a higher `z-index` value. You can fix this by injecting the following code:

```html
<style>
.gh-portal-triggerbtn-iframe {
	z-index: 3;
}
</style>
```
