### ISSUE TITLE
Remove Facebook 

### ISSUE THREAD

**Issue by Joshfairhead** [eddiesigner/liebling#399]
How can I remove the Facebook social links? I have no information for it entered in the Ghost dashboard; how do I remove it from the posts (and across the theme in general)?

Thanks

**Comment by Leovaldez42** [comment]
You have to edit the footers in the liebling folder by changing the code in /partials/footer.hbs

**Comment by Joshfairhead** [comment]
@Leovaldez42 - Thank you.

**Comment by Joshfairhead** [comment]
Ah, sorry. Follow up. That didn't work.

I wonder if its to do with compiling the theme again after modification? I had issues doing that the last time I modified the style from light to dark mode (should have just injected code), instead I hacked around and removed things from the compiled js. If you have any advice or pointers to set up the appropriate environment and compile it would be appreciated :)

**Comment by eddiesigner** [comment]
To remove the Facebook from the footer you have to clear the input for the Facebook account in the Ghost Admin.

To remove the Facebook from the author profile page you have to clear the input for the author Facebook account in the Ghost Admin.

If you also want to remove the Facebook sharing button in posts you have to do the following:

1. Unzip the theme folder

2. Open the file [post.hbs](https://github.com/eddiesigner/liebling/blob/master/post.hbs) with a code editor and remove the following code:

```hbs
<a href="https://www.facebook.com/sharer/sharer.php?u={{url absolute='true'}}"
 class="m-icon-button filled in-share" target="_blank" rel="noopener" aria-label="Facebook">
	 <span class="icon-facebook" aria-hidden="true"></span>
</a>
```

3. Save your changes, zip the theme folder again and upload it in the Ghost Admin.
