### ISSUE TITLE
author page: not enough height with long bio (max 200 characters) set

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#4]
Demo: https://calvintam.dev/author/calvin/

**Comment by eddiesigner** [comment]
Sadly this is a Ghost limitation:

> Write about you, in 200 characters or less.

**Comment by calvintam236** [comment]
![Screen Shot 2019-05-15 at 8 26 59 PM](https://user-images.githubusercontent.com/6436149/57824429-db7c7800-774f-11e9-8609-24dbc3d97cb4.png)
Sorry for not attaching the screenshot. This occurs on smaller screen. You can see the height of the header is too close to the nav.

**Comment by eddiesigner** [comment]
Ok, I understand now, I fixed it with the latest release ;)

**Comment by calvintam236** [comment]
Thanks 😃
