### ISSUE TITLE
How to Remove Subscription Button

### ISSUE THREAD

**Issue by iqlal** [eddiesigner/liebling#400]
Hi Eddie, can you tell me how i can delete / hide my Subscription Button, because my blog is not for member, my blog is for all reader, thanks

![image](https://user-images.githubusercontent.com/64581779/130001740-4d7305d1-d977-4b24-8f7a-bba4e3ea7b13.png)

**Comment by Erebus88** [comment]
You can manually remove it by deleting line 34 in index.hbs in the theme root. The offending line is this:

`<a href="{{@site.url}}/newsletter" class="m-button filled js-newsletter">{{t "Subscribe"}}</a>`

Hope this helps

**Comment by iqlal** [comment]
Thanks :)
