### ISSUE TITLE
Change Footer Color in Light Mode

### ISSUE THREAD

**Issue by iqlal** [eddiesigner/liebling#401]
Hey Eddie your theme is amazing, but if i use light mode there is awkward color (blue footer) how i change that ? Thanks
![image](https://user-images.githubusercontent.com/64581779/130337685-44f62ad5-66a5-4052-8076-0f74c0d3c1aa.png)

**Comment by moldavitegirl** [comment]
I have the same query. I'd like to change the footer colour too. Thanks.

**Comment by eddiesigner** [comment]
Hi, you can change the footer color by injecting the following styles in the Ghost Admin:

```html
<style>
:root,
[data-theme="light"] {
	--footer-background-color: #f4f4f4; /* Example of color for light mode */
}
</style>
```

**Comment by moldavitegirl** [comment]
Thank you! That's much appreciated.

Nicola

________________________________
