### ISSUE TITLE
Font problem with Vietnamese

### ISSUE THREAD

**Issue by vutuanlinh2k2** [eddiesigner/liebling#404]
There's a problem with the font when I change Publication Language to vi (vietnamese). Can you guys check that !
Some letter was bolder
<img width="1440" alt="Screen Shot 2021-09-04 at 18 10 04" src="https://user-images.githubusercontent.com/69841784/132092381-da6ed292-a8a2-48f5-918d-2f882c219e9a.png">

**Comment by lapphan** [comment]
[How to use a different character encoding](https://github.com/eddiesigner/liebling/wiki/How-to-use-a-different-character-encoding)

**Comment by eddiesigner** [comment]
I will close this issue since the answer from @lapphan should fix the issue ;)
