### ISSUE TITLE
A Hugo theme support?

### ISSUE THREAD

**Issue by longkai** [eddiesigner/liebling#405]
Hi this is really a nice theme.

Do you have any plan support for static site theme like hugo?

**Comment by stephenajulu** [comment]
That would be absolutely amazing if acted upon! A hugo theme for Liebling, fantastic! But it all depends on the author and those who can build it. Let's hear what they have to say. I'm all up for it. I would help set up the SEO side of things and the overall project as a contributor.

**Comment by eddiesigner** [comment]
Hi,

Sorry but I don't have plans to develop a Hugo theme 😅

Cheers.
