### ISSUE TITLE
Remove Subsribe Section Each Post

### ISSUE THREAD

**Issue by iqlal** [eddiesigner/liebling#408]
Hello Eddie,
How i can remove this section (subcribe section) ???
![image](https://user-images.githubusercontent.com/64581779/135541649-be078728-c350-473e-878a-55c42c55f0e6.png)

**Comment by nikdjukic** [comment]
Hi,
Here is how:
https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

Paste the following code in the Site Header block:

<script>
  const disableNewsletter = true;
</script>

Cheers,

**Comment by eddiesigner** [comment]
In the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v1.0.5) the Newsletter form is removed if you [disable memberships](https://ghost.org/help/can-i-disable-memberships/#:~:text=Yes%20%E2%80%94%20if%20you%20don't,subscription%20access%20level%20to%20Nobody.) in the Ghost Admin.
