### ISSUE TITLE
Alt text does not appear

### ISSUE THREAD

**Issue by HelenaCornu** [eddiesigner/liebling#410]
This template is fantastic! However, I've noticed that though it has an option for alt text on images (but not on galleries), the alt text doesn't actually appear when I inspect the final blog post. 

<img width="1440" alt="Screenshot 2021-10-12 at 15 06 14" src="https://user-images.githubusercontent.com/73692302/136971868-355c5312-ce04-4952-b5cf-f597ccf4f5d8.png">
<img width="1440" alt="Screenshot 2021-10-12 at 15 07 04" src="https://user-images.githubusercontent.com/73692302/136971883-62fd74fd-9706-4a86-95f9-f1dfdf07ee0e.png">

However, if I write a caption, it appears as alt text.

<img width="1440" alt="Screenshot 2021-10-12 at 15 09 17" src="https://user-images.githubusercontent.com/73692302/136972081-2181b249-d616-425b-808f-8b26181810ad.png">
 
Would it be possible to fix this so that I can have both a caption and alt text, and so that the alt text option appears for galleries? 

Thank you!

**Comment by eddiesigner** [comment]
Thanks for pointing that out! I fixed the issue with the al text on images in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v1.0.6).

However, you should know that Ghost doesn't support alt text for galleries.
