### ISSUE TITLE
The progress indicator shows wrong progress if the post contains image.

### ISSUE THREAD

**Issue by Fabhi** [eddiesigner/liebling#411]
The circular progress indicator shows 100% progress before the post is even finished if the post contains images. I think the images have not been taken into accout for calculating the progress.

**Comment by eddiesigner** [comment]
Can you provide a link?

The theme tries to calculate the progress when the [load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is triggered, in theory that should happen when the whole page has loaded, including all dependent resources such as stylesheets and images.

Of course the progress is just an estimate, in some cases images or iframes that take longer to be fully loaded are not taking into account but that depends of your Internet speed or the size of the images.

For me it works correctly all the time in the demo website.

**Comment by eddiesigner** [comment]
I will close this issue for now due inactivity, please feel free to comment again if necessary.
