### ISSUE TITLE
Autofill email address does not work on iOS

### ISSUE THREAD

**Issue by rhoeijmakers** [eddiesigner/liebling#414]
When signing up on iOS you can autofill the name but not the email address. The option is presented but when chosen no email address appears in the field. Tested on multiple devices. 

![image](https://user-images.githubusercontent.com/62013791/140653987-dbb438ef-9bb9-4b05-90c6-26f23161fc79.png)

**Comment by eddiesigner** [comment]
I wonder if you're using Portal because Liebling doesn't implement a Membership form like that one, if that's the case then it's not related to the theme and you should contact the Ghost support theme to see if they can do something about it.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
