### ISSUE TITLE
Need help with reducing the height of the banner on the homepage

### ISSUE THREAD

**Issue by rmmdebruin** [eddiesigner/liebling#415]
Hi,

Thanks for the great theme, we like it a lot.

We try to reduce the height the banner on the homepage of our website: https://www.romuluseurope.eu/.

We digged into the css and tried multiple things but we can't seem to figure out how it's done.

Would be fantastic if you could help us.

Cheers,

Reinier

![image](https://user-images.githubusercontent.com/85482745/143609389-7e4954f0-8661-4c73-931e-2d6856d16835.png)

**Comment by eddiesigner** [comment]
Hi,

Please take a look to [this issue](https://github.com/eddiesigner/liebling/issues/305) where I explain how to do that.

Cheers.

**Comment by rmmdebruin** [comment]
Amazing, thanks!

**Comment by rmmdebruin** [comment]
Hi,

Thanks again for the previous solution.

We were wondering: is there also a way to separately adjust the image height on the home page and the image height on the post pages? So that they can have different heights in both situations.

Many thanks, cheers,

Reinier

**Comment by eddiesigner** [comment]
Hi,

Yes, you can inject the following code to do so:

```html
<style>
/* HOME PAGE */
.home-template .m-hero {
  min-height: 365px; /* The height you want for mobile */
}

@media only screen and (min-width: 48rem) {
  .home-template .m-hero {
    min-height: 400px !important; /* The height you want for desktop */
  }
}

/* POST PAGE */
.post-template .m-hero {
  min-height: 365px; /* The height you want for mobile */
}

@media only screen and (min-width: 48rem) {
  .post-template .m-hero {
    min-height: 400px !important; /* The height you want for desktop */
  }
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.

**Comment by rmmdebruin** [comment]
Yes that's fine, thanks for the helpful answer!
