### ISSUE TITLE
dropdowns

### ISSUE THREAD

**Issue by johnggraham** [eddiesigner/liebling#416]
Hi Can I apply dropdowns to any navigation title in the navigation bar, also can I fix the navigation bar on scrolling so it always stays in view?

**Comment by eddiesigner** [comment]
Hi,

Currently there is no way to add a dropdown to the navigation items, sorry.

To fix the navigation bar on scrolling you can inject the following code in the Ghost Admin:

```html
<style>
.m-header {
  transform: translateY(0) !important;
}
</style>
```

**Comment by johnggraham** [comment]
Thanks for replying! greatly appreciated
