### ISSUE TITLE
How can I install liebling theme insted of casper in localhost?

### ISSUE THREAD

**Issue by rcmangnale** [eddiesigner/liebling#417]

**Comment by eddiesigner** [comment]
The same way you would do it on production, just download the latest version from the [Releases page](https://github.com/eddiesigner/liebling/releases) and upload it in the Ghost Admin.

If you want to work on it and custom it you can follow [this guide](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) to learn how to setup a development environment.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
