### ISSUE TITLE
How to add Social Media Icons

### ISSUE THREAD

**Issue by dietrichai** [eddiesigner/liebling#419]
Hi Eddie! I love your theme and I would be using it for my blog/newsletter. I was just wondering how to add social media icons? I am having trouble adding it to the icomoon.svg file, it doesn't seem to work. In particular, I am trying to add Medium's icon/logo.

Thanks!

**Comment by eddiesigner** [comment]
Hi!

[This guide](https://github.com/eddiesigner/liebling/issues/47#issuecomment-531158185) might be helpful for you. You can inject the styles added in step 8 directly in the Ghost Admin.

Hope it helps.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
