### ISSUE TITLE
Help me with the Subscribe Button

### ISSUE THREAD

**Issue by chaitanyasaxena246** [eddiesigner/liebling#420]
Hello

I'm using your theme but I want to make sure that the Subscribe function will work I can't able to figure out How can I work with the subscribe function could you please help me on this.

**Comment by eddiesigner** [comment]
Hi,

Do you actually have an issue with the subscription form or what do you mean exactly? You don't need to do something in particular to make it work.

You might wanna check this article: https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

If you have troubles with the subscription form I recommend you to check some [related issues](https://github.com/eddiesigner/liebling/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+subscribe), they might be helpful.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
