### ISSUE TITLE
Subscribe button overlaps footer bar on mobile

### ISSUE THREAD

**Issue by gdommergue** [eddiesigner/liebling#421]
Thanks for your work on this theme.

As you can see on below screenshot, the subscribe button slightly overlaps the footer bar on mobile and makes the "return to the top of the page" button not working anymore.

![image](https://user-images.githubusercontent.com/63804616/144753803-86a1bcdd-2aca-4c0c-946c-d84b806b2c5a.png)

Expected result: the subscribe button should not overlap the footer bar obviously :)

**Comment by eddiesigner** [comment]
You can move a little bit that button so it doesn't overlap the bar, for example you could inject the following code in the Ghost Admin:

```html
<style>
@media only screen and (max-width: 48rem) {
  .post-template .gh-portal-triggerbtn-iframe {
    bottom: 30px !important;
  }
}
</style>
```

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
