### ISSUE TITLE
Changing Background Image and Text of Subscription Page

### ISSUE THREAD

**Issue by Justologist** [eddiesigner/liebling#422]
How can I change the background image and description "stay up to date!" of this page ?
![Newsletter Subscription Page](https://user-images.githubusercontent.com/92815168/145671923-879487c1-8c10-4e4b-a166-04eb4de05a2c.png)

**Comment by eddiesigner** [comment]
You can inject the following code in the Ghost Admin to change the background color:

```html
<style>
/* LIGHT MODE */
:root,
[data-theme="light"] {
  --newsletter-background-color: #ffe4e6;
}

/* DARK MODE */
[data-theme="dark"] {
  --newsletter-background-color: #1e3a8a;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --newsletter-background-color: #1e3a8a;
  }
}

.page-newsletter .l-fullscreen {
  background-color: var(--newsletter-background-color);
}
</style>
```

To change the description please follow these steps:

1. Unzip the theme folder
2. Open the file `locales/en.json` with a code editor
3. Replace the **right** part of this line with your own text:

```json
"Stay up to date! Get all the latest & greatest posts delivered straight to your inbox.": "Stay up to date! Get all the latest & greatest posts delivered straight to your inbox.",
```

Example:

```json
"Stay up to date! Get all the latest & greatest posts delivered straight to your inbox.": "Your own description text goes here.",
```

4. Save your changes
5. Zip the theme folder and upload it again
