### ISSUE TITLE
Github Gists are broken in darkmode

### ISSUE THREAD

**Issue by MatrixUsman** [eddiesigner/liebling#428]
First of all i hugely appreciate your work and a big thanks
So its my first time opening an issue https://droidmodders.com/caching-in-nodejs-with-redis/ but you can visit this link and see how github gists react when in darkmode

**Comment by MatrixUsman** [comment]
@eddiesigner just tagging

**Comment by eddiesigner** [comment]
Hi,

You can inject the following code in the Ghost Admin:

```html
<style>
.l-post-content table tbody tr:nth-child(odd) {
  background-color: transparent;
}
</style>
```

**Comment by MatrixUsman** [comment]
Thanks man ! Appreciate it
