### ISSUE TITLE
Copy code blocks like githubs UI and Desgin (Not an issue just a sugesstion or more like a feature request)

### ISSUE THREAD

**Issue by MatrixUsman** [eddiesigner/liebling#434]
Title says it al

https://user-images.githubusercontent.com/51532673/148052395-441f47bd-9c44-410f-9822-94af317c3e2e.mov

**Comment by eddiesigner** [comment]
Thanks for the suggestion! However, this is something that I don't plan to implement, sorry 😅. Pull requests are always welcome 😉
