### ISSUE TITLE
Progress circle no longer indicates progress

### ISSUE THREAD

**Issue by dazizian** [eddiesigner/liebling#437]
Previously, on scrolling, the progress ring would fill as the page scrolled. Now, there is no ring.

0.9.4:

![image](https://user-images.githubusercontent.com/49478924/149576910-1f37a9b1-be71-4687-b06b-6161b93b57ea.png)

1.5.0:

![image](https://user-images.githubusercontent.com/49478924/149576975-61757f53-1be1-4f44-961b-c041a1c3a2b3.png)

**Comment by eddiesigner** [comment]
Now you can set the accent color in the Ghost Admin (Desing settings --> Brand).

The accent color that Liebling uses in the demo website is `#0470ee`

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
