### ISSUE TITLE
Right to left languages - Arabic

### ISSUE THREAD

**Issue by allamiro** [eddiesigner/liebling#44]
How can I make this theme right to left friendly ?

**Comment by eddiesigner** [comment]
To be honest I had not thought about giving support for languages like Arabic, because of that I will have to modify many classes, I hope to be able to do it next week.

**Comment by eddiesigner** [comment]
The [latest release](https://github.com/eddiesigner/liebling/releases/tag/v.0.4.0) is RTL friendly ;)
