### ISSUE TITLE
theme just doesn't apply

### ISSUE THREAD

**Issue by ash-development** [eddiesigner/liebling#441]
i installed the liebling theme to my new ghost installation and it simply doesn't apply. it shows as the default theme when it's not activated. the ruby theme works perfectly fine, it's just this theme.

![image](https://user-images.githubusercontent.com/75553731/150691682-3ddbef8f-6b4c-4ee3-acaa-0fa2853f49ed.png)

**Comment by MatrixUsman** [comment]
Hi there, did you tried clearing any DNS and your browser cache. Moreover after applying did you checked on any other device or in another browser / incognito mode?

**Comment by ash-development** [comment]
I have tried clearing browser cache but I have tried on several different browsers and devices and it still does not work

**Comment by eddiesigner** [comment]
What version of Ghost are you using?

What file did you download? You have to download this file (latest version): https://github.com/eddiesigner/liebling/releases/download/v1.5.0/liebling.zip

**Comment by ash-development** [comment]
I am using version 4.33.0 of ghost. I downloaded that file and it still does not work.

**Comment by ash-development** [comment]
apologies - seems like it worked. thank you
