### ISSUE TITLE
Version 1.5.1 break recent article text

### ISSUE THREAD

**Issue by iamgiannisx** [eddiesigner/liebling#445]
Hello 

At recent articles Text Article Title does not wrap.

![Liebling_bug](https://user-images.githubusercontent.com/33219224/153595222-24ad0e1b-0263-40f7-8540-cd4d0b19f10c.png)

**Comment by eddiesigner** [comment]
Hey, thanks for the heads up! It's fixed in [version 1.5.2](https://github.com/eddiesigner/liebling/releases/tag/v1.5.2) ;)
