### ISSUE TITLE
Toggle not show icon collapse/expand

### ISSUE THREAD

**Issue by KhoaSuperman** [eddiesigner/liebling#453]
My site registered from ghost.io, free tier. [https://demo-khoaha.ghost.io/coming-soon/](https://demo-khoaha.ghost.io/coming-soon/)

The icon cannot display here. I install liebling by download zip file then upload to ghost. Have no touch on codebase. Please check

![image](https://user-images.githubusercontent.com/8596226/163667355-941dde90-5555-41bf-b888-55561cf36192.png)

**Comment by eddiesigner** [comment]
Thank you for the report, this is fixed in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v2.0.0) ;)
