### ISSUE TITLE
Ghost 5 update support?

### ISSUE THREAD

**Issue by kiraitachi** [eddiesigner/liebling#456]
Good morning.

I love your theme and work, thanks a lot! I was wondering if there is work in progress to support Ghost 5. It works for me but during upgrade procedure it gave me some errors:

![Screenshot 2022-05-30 at 10 04 25](https://user-images.githubusercontent.com/40744673/170948528-61df85b4-4ea6-48a0-a5e9-c3f45a37b148.png)

Cheers!

**Comment by nagaame** [comment]
Hi , you can check my pull request and fixes the error codes , then use `yarn production` repackages this project .

**Comment by eddiesigner** [comment]
@kiraitachi I just released a [new version](https://github.com/eddiesigner/liebling/releases/tag/v2.0.0) with Ghost 5 support ;)

Btw, thanks for your kind words!

**Comment by kiraitachi** [comment]
@eddiesigner  and @nagaame thanks a lot for your work and contributions! Will test it right now.

Cheers!
