### ISSUE TITLE
Support native search?

### ISSUE THREAD

**Issue by shincurry** [eddiesigner/liebling#462]
Ghost Official introduced Native Search recently. 

https://ghost.org/changelog/search/

> Adding Search to a Ghost site is easy, and can be done in two ways:
> 
> Add a #/search link to your site navigation in Ghost Admin, and you'll have a clickable navigation link that opens the search interface.
> Read more in our [help docs](https://ghost.org/help/search).
> Add a data-ghost-search attribute to any element in your theme (a 🔎 icon, perhaps?), and you'll have a clickable button to open the search interface.
> Read more in our [developer docs](https://ghost.org/docs/themes/search).

**Comment by Just5KY** [comment]
https://github.com/eddiesigner/liebling/wiki/How-to-enable-search

@shincurry

**Comment by monster1612** [comment]
> https://github.com/eddiesigner/liebling/wiki/How-to-enable-search

that solution is the pre-5.x approach to enabling search in the Liebling theme, and isn't quite as powerful as the native search feature available in Ghost now.

one possible workaround is to add a link in the header with the URL `#/search`, but a more native solution (bonus points if it can bind to Ctrl/Cmd + K) would be ideal.

**Comment by Just5KY** [comment]
Ok, I see what you mean, the new search thingy is so much better and fast 
I added it to Custom CTA
![image](https://user-images.githubusercontent.com/71321862/181217260-68ffe84b-3e17-44e5-957f-96ef636811d8.png)


![Recording 2022-07-27 at 15 14 32](https://user-images.githubusercontent.com/71321862/181216987-0eb48f82-c5c8-4020-a7b1-edfaf66aae72.gif)

**Comment by magicgg91** [comment]
@Just5KY yes that's a solution, but it's not best integration we can have.
Search button on top right is still there with different search algorithm.

I would expect to have this button using builtin Ghost search feature.

**Comment by FAFDK** [comment]
How about the translation of the search string? Where is that located? :  " Search posts, tags and authors".
Testing a fresh Danish da.json now.
