### ISSUE TITLE
Featured image cropped and weird look on the posting page (mobile and desktop)

### ISSUE THREAD

**Issue by tedknow44** [eddiesigner/liebling#463]
First, thanks for this awesome ghost theme. I have a problem with featured images. The home page shows featured images without cropped and no issue, but when I click the post, the posting page features image cropped and does not show all images contents. Also, the mobile version has that issue.

here is the post link [https://tedknow.com/domain-name-how-to-choose-the-right-domain/](url)

**Comment by eddiesigner** [comment]
The following issues might help you to understand the current behavior and to know how you can adapt it to your needs:

https://github.com/eddiesigner/liebling/issues/365

https://github.com/eddiesigner/liebling/issues/322

**Comment by tedknow44** [comment]
Thank you! I will check and try.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
