### ISSUE TITLE
Issue: Ghost Version 5

### ISSUE THREAD

**Issue by RyanStekken98** [eddiesigner/liebling#466]
1.I can deactivate the Subscribe button but in my Homepage is existing the button for that.
![image](https://user-images.githubusercontent.com/43929173/185393781-a20ba4ea-c338-45c0-83fc-dcc9797c8f9b.png)

2. is Possible to integrate a comment section for ghost 5?

Regards Nizar

**Comment by eddiesigner** [comment]
Hi, I'm not sure if I understand it correctly, could you please elaborate a bit more?

Maybe the following links are helpful for you:

https://github.com/eddiesigner/liebling/wiki/Custom-CTA-button-in-the-Home-page

https://github.com/eddiesigner/liebling/wiki/Add-comments-to-your-blog

If you want to remove the Subscribe button you can remove the Custom CTA text and the Custom CTA url from the theme settings or you can also disable Subscription access in the Ghost Admin (Settings --> Membership):

![CleanShot 2022-08-20 at 11 24 41](https://user-images.githubusercontent.com/1477503/185738864-d349e75a-567c-4d1d-8781-6a460b129ca1.png)

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
