### ISSUE TITLE
Linkedin social sharing

### ISSUE THREAD

**Issue by veshitala** [eddiesigner/liebling#47]
I want to add linkedin social sharing in the theme can you please suggest me how can i do this

**Comment by D3473R** [comment]
Afaik Ghost does only support Facebook and Twitter natively: https://forum.ghost.org/t/additional-social-accounts-in-general-settings/750
You can add however your own links with icons.
1. Download https://github.com/eddiesigner/liebling/blob/master/src/sass/fonts/icomoon/icomoon.svg
2. Open https://icomoon.io/app/#/select
3. Click on `Import Icons` and select the downloaded `icomoon.svg` (Use this font's metrics and metadata when exporting fonts? click yes)
4. Select every icon from the base font (should be the upper row) and any additional icons you want in the pack (linkedin in your example)
5. In the bottom left click `Generate Font` and then `download`
6. Remember the id that is written under the new Icon (for instagram its `e90c`)
![Screenshot from 2019-09-13 10-45-46](https://user-images.githubusercontent.com/10356892/64849452-af94d480-d613-11e9-906c-ec5bee54b63d.png)
7. Download the `.zip` file and replace the font files in `src/sass/fonts/icomoon/` with those in the `.zip` file `fonts` directory
8. Open `src/sass/common/_icons.scss` and add your new icon with his id
```css
.icon-instagram:before {
  content: "\e90c";
}
```

so for linkedin:
```css
.icon-linkedin:before {
  content: "\eYOUR_ID";
}
```
9. After that you can add the linkedin link in the footer for example in `partials/footer.hbs` after the twitter icon
```hbs
{{#if @site.twitter}}
<a href="{{twitter_url @site.twitter}}" target="_blank" rel="noopener" aria-label="Twitter">
    <span class="icon-twitter"></span>
</a>
{{/if}}
<a href="LINKEDIN_URL" target="_blank" rel="noopener" aria-label="Linkedin">
    <span class="icon-linkedin"></span>
</a>
```

Now you should see the linkedin icon in the footer
@eddiesigner I just noticed that i snuck in the instagram icon with 8eccc87723fa1ccfcb2b44cf1f99ceefe9673bbe :see_no_evil:

Regards,
D3473R

**Comment by veshitala** [comment]
Thank you so much this is so helpful. I will let you know once it's done

**Comment by eddiesigner** [comment]
@D3473R Cool! Thank you so much for this detailed explanation, I think I should add it to the Wiki for future reference 👌🏼

And don't worry about the Instagram icon 😆

@veshitala To keep the same style, please consider using this icon: https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/linkedin.svg or this one: https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/linkedin-in.svg

**Comment by eddiesigner** [comment]
Since Linkedin is not supported right now by Ghost, I'll close this issue by now since this workaround helps ;)
