### ISSUE TITLE
Is multiple dropdown menu coming  in a future update ?

### ISSUE THREAD

**Issue by Jiminy68** [eddiesigner/liebling#479]
Hi Ed,

And congrats for the nice job done on this Ghost theme. 

Do you have any plan to support multiple dropdown menu in this theme in a near future ?

Would the trick posted for Casper theme with [has_child] and [subitem] tags in the navigation settings be a valid solution ?

Thanks for your feedback.
Jim

**Comment by eddiesigner** [comment]
Hi Jimi,

Since Ghost only supports a secondary menu I don't have plans to support multiple dropdowns, however, I'm wondering about the trick you mentioned in your comment, maybe you can elaborate a bit more on that or maybe share a link where I can read more bout it.

**Comment by Jiminy68** [comment]
Hello Edouardo and sorry for the delay, 

I totaly agree with you. From my POV, the primary menu should be the site main menu , and for News site with wide rrrange of information, it could be very usefull to have multi-level support. The secondary menu should be used as a side menu or bottom menu, offering alternate navigation, but not linked to the primary.

The trick I've found so far to have a dropdown menu on Casper theme use js code injection as explained on [this thread](https://forum.ghost.org/t/add-dropdowns-to-main-menu-through-the-site-admin-copy-paste-into-site-header-footer-injections/30551) 

I've tested the trick on [the site](https://info.maizeroy.net) I'm working on and it works fine so far. However, I'd like to switch to Liebling for the localization and have my site fully available in French.

Waiting forward to read from you.
Cheers.

**Comment by Jiminy68** [comment]
Hi Ed,

So what do you think about this dropdown menu trick ? Any chance to see it in a future version of Liebling ?

Take care,
Jimi

**Comment by eddiesigner** [comment]
Hi Jim,

Sorry for the late answer, I think that's a very hacky way to have multiple dropdowns, therefore I don't think I will implement it in the theme.

You could try to use that trick with Liebling since it should work on any theme, if you have troubles you could ask directly on that thread or here if it's related to the theme.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
