### ISSUE TITLE
Archive function

### ISSUE THREAD

**Issue by zzzqu** [eddiesigner/liebling#483]
Hello author, I like your theme very much. Is there any plan to add the archive function? If not, what can be done?

**Comment by eddiesigner** [comment]
Hi, at the moment I don't have plans to add an archive page, if you want to have it in your website you could use the [page template](https://github.com/eddiesigner/liebling/blob/master/page.hbs) as a foundation and then follow [this tutorial](https://bironthemes.com/blog/ghost-post-archive/) to implement that functionality within that template. You would need to provide your own styles though.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
