### ISSUE TITLE
Ghost.org Table of Contents Tutorial doesn't work with liebling theme

### ISSUE THREAD

**Issue by wandermax4** [eddiesigner/liebling#488]
Hey guys,

I am trying to install the following [ToC](https://ghost.org/tutorials/adding-table-of-contents/). It doesn’t work with my liebling themed site. 

I am a absolute noob. Followed all the steps, but it didn’t work.

I would love to hear your suggestions.

Thank you for your help :slight_smile:

**Comment by eddiesigner** [comment]
Hi,

These threads might be helpful:

* https://github.com/eddiesigner/liebling/issues/146
* https://github.com/eddiesigner/liebling/issues/372
* https://github.com/eddiesigner/liebling/issues/435

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
