### ISSUE TITLE
Remove Social Media Buttons

### ISSUE THREAD

**Issue by charlies2022** [eddiesigner/liebling#491]
Hi. I need to hide the social media buttons from my website for now. They are removed from the footer on the homepage, but they still show up in all posts in the top right. 
I found this for twiter: 
<style>
div.m-share > div > a[href^='https://twitter.com/'] { display: none; }
</style>
I am still missing to hide Facebook, which I tried to replace the web address in the code before, but it doesn't work.

Thanks in advance.
Regards.

**Comment by ClassUnwind** [comment]
Either duplicate the rule and replace the URL with `https://www.facebook.com/`, or use the following to hide *all* Share buttons:

```
<style>div.m-share a.m-icon-button { display: none; }</style>
```

**Comment by eddiesigner** [comment]
I will close this issue for now since the answer posted above is correct, please feel free to reopen it if needed.
