### ISSUE TITLE
Theme development permission denied

### ISSUE THREAD

**Issue by Lastofthefirst** [eddiesigner/liebling#493]
Hey there, I'm trying to set up the docker dev environement using colima.

When I run `pnpm run docker-watch` the browser window opens up and starts loading, but I get "permission denied" errors, like these:

```
[DOCKER] ghost  | chown: changing ownership of '/var/lib/ghost/content/themes/liebling/src/sass/fonts/icomoon/icomoon.eot': Permission denied
[DOCKER] ghost  | chown: changing ownership of '/var/lib/ghost/content/themes/liebling/src/sass/fonts/icomoon/icomoon.svg': Permission denied
[DOCKER] ghost  | chown: changing ownership of '/var/lib/ghost/content/themes/liebling/src/sass/app.scss': Permission denied

DOCKER] ghost exited with code 1
[DOCKER] docker-compose up exited with code 0
--> Sending SIGTERM to other processes..
[WEBPACK] npm run watch exited with code 0
```

Any idea what direction I should look to debug?

**Comment by eddiesigner** [comment]
This seems to be related to your system, I'm not sure what could be the issue but you can try this: https://stackoverflow.com/questions/62697189/chown-permission-denied-while-docker-volume-binding

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
