### ISSUE TITLE
Excerpts, image aspect ratio, and featured post on smartphone mode

### ISSUE THREAD

**Issue by spaceship77** [eddiesigner/liebling#496]
Hi, 

Thanks for the great template!

1) Is it possible to display excerpts? 
2) Is it possible to change the aspect ratio of a publication cover?
3) is it possible to change the aspect ratio of a feature image in a post?
4) When a feature post exists, on smartphone, there is no gap between a publication cover image and the feature image of the featured post. Is it possible to put a gap there?

Thank you!

**Comment by eddiesigner** [comment]
Hi,

The following links might be useful:

1. https://github.com/eddiesigner/liebling/issues/407
2. https://github.com/eddiesigner/liebling/issues/305
3. https://github.com/eddiesigner/liebling/issues/463

You can add a gap by injecting the following code in the Ghost Admin (Settings --> Code injection --> Site Header):

```html
<style>
  .m-featured-slider.swiper {
    margin-top: 0;
  }
</style>
```

**Comment by spaceship77** [comment]
Hi eddiesigner, thank you for your reply, the codes worked! 
Thank you!
