### ISSUE TITLE
Not all in french?

### ISSUE THREAD

**Issue by zarevskaya** [eddiesigner/liebling#497]
Hello and thank you for this theme, he is great!

I have two questions about the translation.

I want to translate in french:

![Capture d’écran 2023-01-04 181726](https://user-images.githubusercontent.com/60230221/210612697-fb8d298b-76b8-46b9-a5c6-b145af63ebe5.png)

And I want to transalte all email form in french:

![Capture d’écran 2023-01-04 181802](https://user-images.githubusercontent.com/60230221/210612769-835665d0-d8a3-4841-b2dc-1f2d222d3b22.png)

where are all these files and how to translate them correctly?

Thank you very much to reading me.

**Comment by L4ma** [comment]
I can't help you with the first screenshot, but unfortunately, as far as I know, you can't change anything in the email. The email comes directly from Ghost.

**Comment by eddiesigner** [comment]
Unfortunately you can't translate emails and Portal components because those are not handled by the theme but Ghost itself.

**Comment by zarevskaya** [comment]
Thank you both for your answer.

Have a nice day.

**Comment by djerfy** [comment]
You can found all details here: https://ghost.org/docs/faq/translation/ (why not all in french)
