### ISSUE TITLE
divider and image width in page

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#5]
![Screen Shot 2019-05-14 at 11 17 42 AM](https://user-images.githubusercontent.com/6436149/57721904-315efc00-763a-11e9-9a2a-2b239751774b.png)

missing margin for divider?
image width should be `max-width: 100%`?

**Comment by eddiesigner** [comment]
@calvintam236 How did you put those elements? the divider has a completely different appearance and the images have a `max-width: 100%`. It should looks like this post:

https://liebling.eduardogomez.io/make-myspace-your-best-designed-space/

**Comment by calvintam236** [comment]
Still in preview: https://calvintam.dev/p/8f4abc63-aa6f-401f-b01d-71a7617e78c0/

**Comment by eddiesigner** [comment]
Finally I figured it out what was the problem, it's already fixed in the latest version (0.1.4) 👍🏼
