### ISSUE TITLE
Error: Oops! You seemed to have used invalid Handlebars syntax. 

### ISSUE THREAD

**Issue by nsudhanva** [eddiesigner/liebling#50]
I get the following error, when I upload .zip of your theme to Ghost
```
Oops! You seemed to have used invalid Handlebars syntax. 
This mostly happens, when you use a helper that is not supported.
See the full list of available helpers here.

Affected files:
index.hbs: Missing helper: "authors"
post.hbs: Missing helper: "authors"
```

![image](https://user-images.githubusercontent.com/11288918/65151586-03545300-da44-11e9-96a3-eb4f19861bf7.png)

**Comment by D3473R** [comment]
Looks like you are running an old ghost version. (https://github.com/zutrinken/attila/issues/24)

**Comment by nsudhanva** [comment]
Thanks @D3473R. Updating the version to 2.3.x solved the problem
