### ISSUE TITLE
How can I change the number of posts on the homepage?

### ISSUE THREAD

**Issue by L4ma** [eddiesigner/liebling#502]
Hi,
I've been searching through the code for a while now and unfortunately I can't find a place where I can adjust the number of postings. Can anyone help me?

**Comment by eddiesigner** [comment]
Hi,

Unfortunately this is only possible by editing the following line in the `package.json` file (after unzipping the theme file):

```json
"posts_per_page": 10,
```

Afterwards you have to zip the folder and upload it again.

**Comment by L4ma** [comment]
Thank you for your help!
