### ISSUE TITLE
File download block's icon isn't visible in dark mode

### ISSUE THREAD

**Issue by Lastofthefirst** [eddiesigner/liebling#503]
Here's a screenshot:
<img width="875" alt="Screen Shot 2023-01-19 at 11 38 47 AM" src="https://user-images.githubusercontent.com/47003973/213501950-33ab2207-04e4-4f0e-bd1c-a87120770ba4.png">

Thanks for all the good work.

**Comment by eddiesigner** [comment]
Thank you for the heads up! I will fix it in a next release. In the meantime you can inject the following code in the Ghost Admin (Settings --> Code injection --> Site header):

```html
<style>
.l-post-content .kg-file-card .kg-file-card-icon svg {
  color: var(--accent-color);
}
</style>
```

**Comment by eddiesigner** [comment]
I just realised that this was fixed several months ago, that means that you're probably using an old version of the theme, I would suggest to update to the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v2.1.3), just be aware that the theme is now only compatible with Ghost 5.
