### ISSUE TITLE
Un-clickable checkbox and radio buttons when building HTML form

### ISSUE THREAD

**Issue by hieuphung97** [eddiesigner/liebling#506]
I have an issue with the Liebling theme when building my own HTML form

Here is the HTML form with the default ghost theme
<img width="791" alt="Screenshot 2023-02-05 at 11 14 02" src="https://user-images.githubusercontent.com/59104348/216801314-ec709c31-adff-4f07-a691-197e1a48f704.png">

And here is this form with Liebling theme.
Not only are radio buttons look wield, but also un-clickable. 
<img width="863" alt="Screenshot 2023-02-05 at 11 13 19" src="https://user-images.githubusercontent.com/59104348/216801325-6f6384fe-f6c8-4527-bbdf-4cb2ecf3442f.png">

**Comment by eddiesigner** [comment]
Thanks for the heads up! This is already fixed in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v2.1.3).
