### ISSUE TITLE
Add top bar announcement

### ISSUE THREAD

**Issue by bastienperez** [eddiesigner/liebling#511]
Hello,
I want to add a top bar announcement to my website.
I try to follow the [official ghost tutorial](https://ghost.org/tutorials/offer-banners/) but it seems not working.

Have you any recommendation to do this?

Thanks.

**Comment by eddiesigner** [comment]
This has been fixed in the [latest release (2.1.5)](https://github.com/eddiesigner/liebling/releases/tag/v2.1.5):

![CleanShot 2023-05-28 at 14 36 30](https://github.com/eddiesigner/liebling/assets/1477503/e3912336-c6c5-4b75-96cc-622b2570378c)

**Comment by bastienperez** [comment]
Awesome, thanks!
