### ISSUE TITLE
Footer submenu scrolling issue

### ISSUE THREAD

**Issue by EchoBilisim** [eddiesigner/liebling#521]
Hello, why does the menu slide at the bottom even though there are spaces on the bottom menu edges in the footer, how do I edit it, I want it to stay organized.

![Ekran görüntüsü 2023-05-31 214936](https://github.com/eddiesigner/liebling/assets/17055352/af22748b-f1df-4426-be5e-718cecd0566e)

**Comment by eddiesigner** [comment]
You can try to inject the following styles in the Ghost Admin:

```html
<style>
#ghost-portal-root iframe {
  right: -16px;
}
</style>
```

Please next time open a different issue if it's not related to the same topic.

**Comment by EchoBilisim** [comment]
> You can try to inject the following styles in the Ghost Admin:
> 
> ```
> <style>
> #ghost-portal-root iframe {
>   right: -16px;
> }
> </style>
> ```
> 
> Please next time open a different issue if it's not related to the same topic.

unfortunately it didn't work

**Comment by eddiesigner** [comment]
It seems that you need to add `!important` to it, I updated my comment.

**Comment by EchoBilisim** [comment]
ok now thank you very much
