### ISSUE TITLE
Change the footer color and excerpt not showing.

### ISSUE THREAD

**Issue by 0xSegmented** [eddiesigner/liebling#526]
Hi,
I've started using this theme, the best free theme available for Ghost. You are much appreciated for the development of this!

## Footer
So the footer has the color blue, and I could not find a footer.css file where I can modify its color.
Would be lovely if you'd have a solution for this.
[Check footer](https://hacked.rip)

## Excerpt
Also when going to the homepage, I notice that the excerpt is not showing. Take an example for the theme: `ruby`. This has about the same tiles and does contain the excerpt or the top of the blog post.
How would I enable this? And/or would be a great part of the theme.
[ruby preview](https://ghost.org/themes/ruby/)

Thank you for reading, hopefully, there is a solution soon.

Kind regards,

Xatt.

**Comment by MaliciousXatt** [comment]
I was able to change the color of the footer in the following file:
```bash
ghost/content/themes/liebling/assets/css/app.css
```
- [x] Footer color

Only the excerpt is still standing.
