### ISSUE TITLE
Authors Page not displaying new author (3rd)

### ISSUE THREAD

**Issue by buarle** [eddiesigner/liebling#545]
Hi Ed,

could you please assist me in fixing this issue.

We are currently two authors and a third one is joining. We added him as a staff but he is not showing up next to us.

Thanks and best,
buarle

**Comment by eddiesigner** [comment]
Hi,

He needs to be the author of a post or a page in order to appear in the Authors page.

Cheers.

**Comment by buarle** [comment]
Thanks that worked! It might be worth a note in the wiki.

Best regards!
