### ISSUE TITLE
CSS not getting applied

### ISSUE THREAD

**Issue by meshfields** [eddiesigner/liebling#55]
Happens only with these theme, strange. I see only HTML, CSS not getting applied. Ever exprienced this?

**Comment by D3473R** [comment]
Have you downloaded the theme from https://github.com/eddiesigner/liebling/releases or just cloned the repo?
If you just cloned the repo you have to build theme yourself with:
- `cd src`
- `npm install`
- `npm run production`

**Comment by eddiesigner** [comment]
@meshfields You just need to download the right file which is `liebling.zip` from the releases page, not the source code:

Latest version at the moment: https://github.com/eddiesigner/liebling/releases/download/v.0.4.0/liebling.zip

**Comment by eddiesigner** [comment]
I'll close this for now since both answers should solve the problem.
