### ISSUE TITLE
Installation errors and warnings!

### ISSUE THREAD

**Issue by tareqmahmud** [eddiesigner/liebling#57]
Hi,
During install this theme got these errors.

![Error1](https://user-images.githubusercontent.com/4035645/65826178-25e73700-e2a2-11e9-832a-64074bb2ec8e.png)
![Error2](https://user-images.githubusercontent.com/4035645/65826179-28499100-e2a2-11e9-94cc-34d205bcd3bd.png)

liebling version: v0.4.1
Ghost version: v2.31.1

Thanks

**Comment by eddiesigner** [comment]
Thanks for the heads up, it should be fixed with the latest release ([Version 0.4.2](https://github.com/eddiesigner/liebling/releases/tag/v.0.4.2))
