### ISSUE TITLE
Not support IE 11

### ISSUE THREAD

**Issue by luyxeon** [eddiesigner/liebling#58]
Unable to display full content on ie 11
![擷取](https://user-images.githubusercontent.com/38381008/66030066-25190400-e533-11e9-9b67-2ec85a8e1b19.PNG)

**Comment by eddiesigner** [comment]
Thanks for the heads up, please install the latest version, it should be fixed now.

https://github.com/eddiesigner/liebling/releases/tag/v.0.4.3

**Comment by luyxeon** [comment]
Thanks for your quick update, now it works.
