### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by partizan007** [eddiesigner/liebling#59]
![Выделение_005](https://user-images.githubusercontent.com/25349460/66167319-7a900680-e642-11e9-909c-28ed065bafe0.png)

Any ideas what to do?

Ghost version - last
New instalation

**Comment by eddiesigner** [comment]
Please make sure to download the right file, you have to download the file `liebling.zip`, not the source code. You can download it from the releases page: https://github.com/eddiesigner/liebling/releases

**Comment by eddiesigner** [comment]
I will close this since it should be solved by doing what I said above ;)
