### ISSUE TITLE
Two header tags

### ISSUE THREAD

**Issue by ocundale** [eddiesigner/liebling#60]
I notice the markup includes two header tags, which seems incorrect to me- I am working on a fix, but wanted to make sure you didn't want both of these for some reason...

I am assuming this is a mistake as I have always thought that no single element should directly contain two <header> elements.

**Comment by eddiesigner** [comment]
It depends of the context, you can have a `header` element inside an `article` for instance. Taking into account that and what you say, I decided to change the `header` tag for a `section` in the hero component and keep it in the articles.

**Comment by ocundale** [comment]
Great- Yes, I think definitely better to just have a single header tag in this case.
