### ISSUE TITLE
Uploading theme error in Ghost

### ISSUE THREAD

**Issue by deissh** [eddiesigner/liebling#61]
docker ghost:1.21.1-alpine and liebling 0.5

![image](https://user-images.githubusercontent.com/21129524/66270929-59f1c780-e861-11e9-987e-1342f9c0681f.png)

**Comment by eddiesigner** [comment]
Please update your Ghost instance, this theme supports version 2.x.

Related to: https://github.com/eddiesigner/liebling/issues/50
