### ISSUE TITLE
Docker stuck in a loop

### ISSUE THREAD

**Issue by robbertrosario** [eddiesigner/liebling#64]
Hi I have just downloaded v0.5.2 and tried the docker image on (MacOS Mojave) but after following the steps and running `docker-watch` it opens the localhost:3001 page in the browser and the page just keeps loading, also in the terminal the "browser reloading" event just keeps stacking up. i.e. 

`[Browsersync] Reloading Browsers... (buffered 79 events)`

I guess it keeps seeing changes and therefore never finishes?

Does anyone know what might be the problem? I haven't changed anything to the files inside the zip.

**Comment by D3473R** [comment]
Hmm strange :/ 
You followed [these](https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker) instructions?
Do you have any other application running on port `3000` and/or `2368`?
The browser should open on port `3000` and port `2368` should also be free for the ghost docker instance.

**Comment by eddiesigner** [comment]
It also happens to me sometimes, still I don't know why. I can make it work after two or three times though.

When I have more time I can take a look on that, in the meantime you can just run `docker-watch` until it works, I know is not the best option but is the way to go for now.

**Comment by vixrant** [comment]
Any non-docker alternative for theme development? It's stuck in a loop for an hour now.

**Comment by tilenkavcic** [comment]
For now you could do something like:

1. install and run local Ghost
2. clone repo in content/themes and change the theme to liebling
3. `yarn install` and `yarn watch` in ./src
4. zip with `yarn zip`

**Comment by eddiesigner** [comment]
@vixrant you can try to run `npm run docker-watch`, wait for ~30 seconds and then refresh the page, that works for me all the time.

**Comment by vixrant** [comment]
I and my team have been working without docker for some time but I decided to google the issue with Laravel-mix and got this:

https://laracasts.com/discuss/channels/elixir/laravel-mix-keeps-compiling-every-second-without-stop-after-npm-run-watch

It fixed the docker environment for me :p

**Comment by eddiesigner** [comment]
😮 Thanks for the info! I already pushed a commit that tries to fix that https://github.com/eddiesigner/liebling/commit/9720e53cee74ed07cac152c106a96b7cd9255173

I'm not sure though if it solves the issue completely because it already works more or less well on my environment and I don't see a big difference but if you say it fixes the issue on yours then it should work for someone else.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.

**Comment by vixrant** [comment]
Hey! I recently tried to update my theme recently and start the docker-watch dev environment again. It's still stuck in a loop :p
