### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by JonPurvis** [eddiesigner/liebling#65]
Hey,

Love the theme! I downloaded the .zip file of master and uploaded it but none of the styles or fonts pulled through, upon closer inspection in the `/assets/` folder, it appears to be missing:

- `/css`
- `/fonts`
- `/js`

For now I've installed the previous version which is working great, is there any chance the missing assets can be added back so I can use the latest release?

Thanks

**Comment by eddiesigner** [comment]
To get the latest version please head over the [releases page](https://github.com/eddiesigner/liebling/releases) and download the file `liebling.zip` of the latest release.
