### ISSUE TITLE
How do dark mode work

### ISSUE THREAD

**Issue by creekorful** [eddiesigner/liebling#67]
Hello,
First of all thank you for this theme, I'm loving it so far !

I have a little question: how do dark mode is toggle on or off? Based on which predicate?

Can I, for example, force light mode without having to rebuild the theme?

**Comment by creekorful** [comment]
Nevermind, I got it! Maybe you should add a section on the readme to indicate how the dark theme is toggled?

**Comment by eddiesigner** [comment]
I will!

**Comment by Xenonstaforums** [comment]
> Nevermind, I got it! Maybe you should add a section on the readme to indicate how the dark theme is toggled?

Hi! Could you tell me how to do that? :3
