### ISSUE TITLE
Navigation Bar not showing logo when Navigation Menu is Empty

### ISSUE THREAD

**Issue by praveentcom** [eddiesigner/liebling#71]
![image](https://user-images.githubusercontent.com/38263565/67388723-d5b87780-f5b6-11e9-9423-5c3c7cade8a5.png)

The navigation bar shows the logo followed by the navigation menu items. When I removed all the navigation menu items from the ghost settings and looked the website, the logo was also not showing up. We might use the logo to click and navigate to the homepage. This might be a blocker for people to navigate to homepage after reading a post.

**Comment by eddiesigner** [comment]
This is fixed with the latest version 0.5.5 👍🏼
