### ISSUE TITLE
Add local css file to theme leads to 'failed to read zip file' when uploading it

### ISSUE THREAD

**Issue by Bodhiguard** [eddiesigner/liebling#72]
Hello,

I've been trying to add the prism.js js and css to the theme with no success, leading over and over to the error 'Failed to read zip file' when uploading the zip.

I have added the correct tags to the `default.hbs` for the style and the script, like this :
```
<link rel="stylesheet" type="text/css" href="{{asset "css/prism.css"}}" media="screen" />
<script type="text/javascript" src="{{asset "js/prism.js"}}"></script>
```

I have put the files respectively into `assets/js/prism.js` and `assets/css/prism.css`

I zip it, upload it : `Error: Failed to read the zip file`. Once I remove the `prism.js` and `prism.css` files, no more problem. Am I not zipping it right ? Do I have to build something ? Do I have to edit somewhere that I added a new file ? 

Thank you.

**Comment by D3473R** [comment]
Have you downloaded a release zip file like this https://github.com/eddiesigner/liebling/releases/download/v.0.5.7/liebling.zip and modified it?
If you only have cloned the repository you can add your `prism.js` and `prism.css` files and then generate the other javascript files with:
```
cd src
npm install
npm run production
```
Now you should have a `liebling.zip` file in the root directory which you can upload.

**Comment by eddiesigner** [comment]
@Bodhiguard I think you've downloaded the wrong file. You have to download a release zip file (as @D3473R said), uncompress it, then add the Prism files, modify the `default.hbs` file just like you did and compress it again.

I tried doing that and everything worked as expected.

**Comment by Bodhiguard** [comment]
I indeed downloaded the https://github.com/eddiesigner/liebling/releases/download/v.0.5.7/liebling.zip file, unzipped, added the file into assets/js and assets/css, then zipped using 'zip' command and tried to upload. Did not work, failed to read.

Should I try cloning the git, then adding the files as previously and then go into src, to install / run production ? Or should I do download the release zip and do something else (considering there is no 'src' folder in the release zip).

Thanks :)

**Comment by D3473R** [comment]
You are right, the `src` folder is missing in the release zip. you can clone and run `npm run production` to build the necessary js files yourself until @eddiesigner has uploaded a fixed release.

**Comment by D3473R** [comment]
Maybe you have zipped the `iebling` folder itself an not just the contents?
If you open your zipped file do you see the the `liebling` folder or just the contents?
![Screenshot from 2019-11-04 16-16-50](https://user-images.githubusercontent.com/10356892/68132189-8f500a80-ff1e-11e9-8fde-c4006dfcb6b3.png)
Left is correct, right is wrong

**Comment by Bodhiguard** [comment]
I will sum up again.

Downloading the release file, then extracting, modifying files and zipping again works.

Downloading the release file, then extracting, adding the prism.js and prism.css files, zipping again : Failed to read zip file. I tried to clone the git, add files to src/assets/ and running the npm commands, still in progress.

**Comment by eddiesigner** [comment]
You don't need to clone the repo and you don't need the source code neither.

I think the problem is this: 

> then zipped using 'zip' command and tried to upload.

You have to zip the folder with _right click -> compress liebling folder..._

As I said, I just tried and everything works just fine.

I attached the zip file that I created following those steps:

[liebling.zip](https://github.com/eddiesigner/liebling/files/3806094/liebling.zip)

**Comment by Bodhiguard** [comment]
> You don't need to clone the repo and you don't need the source code neither.
> 
> I think the problem is this:
> 
> > then zipped using 'zip' command and tried to upload.
> 
> You have to zip the folder with _right click -> compress liebling folder..._
> 
> As I said, I just tried and everything works just fine.
> 
> I attached the zip file that I created following those steps:
> 
> [liebling.zip](https://github.com/eddiesigner/liebling/files/3806094/liebling.zip)

This is so weird. Here is a imgur link containing all my images to describe the problem, I tried your archive : no error, I tried to zip mine : Failed to read zip. It's just weird.

So as you see, on the first picture inside `Liebling/assets/js` I have `prism.js` and inside `Liebling/assets/css` I have `prism.css`.
![image](https://i.imgur.com/xaAIsgO.png)

Then I add the lines to `default.hbs`.
![image](https://i.imgur.com/5FyJ9kg.png)

I zip it.
![image](https://i.imgur.com/RSCFdKP.png)
![image](https://i.imgur.com/VLt7UuW.png)


Then when I upload the file, I get the error displayed at the end (of the imgur photos). 
![image](https://user-images.githubusercontent.com/36224223/68159757-adcff900-ff52-11e9-8f2f-edb00c6611b0.png)

What am I doing wrong ? Am I stupid or is it just not working on my machine ?

**Comment by D3473R** [comment]
Very strange indeed, can you attach your broken zip file?

**Comment by Bodhiguard** [comment]
Sure, here is a link https://www.swisstransfer.com/d/c935a6bb-56c2-4a16-9eb4-b2ace4bff0c8.

**Comment by eddiesigner** [comment]
Ok, I see two issues here:

1. You haven't downloaded the latest version. I know that because the file `assets/js/polyfill.js` was removed and you still have it.

2. Your zip file is way smaller than mine: ~187kb against ~891kb

I can't test it because I don't have 7Zip but it could be that this programm is compressing the folder above normal and maybe Ghost reject it because it thinks is corrupted or something like that. You should check your settings to see if you can change the compression levels.

**Comment by Bodhiguard** [comment]
> Ok, I see two issues here:
> 
> 1. You haven't downloaded the latest version. I know that because the file `assets/js/polyfill.js` was removed and you still have it.
> 2. Your zip file is way smaller than mine: ~187kb against ~891kb
> 
> I can't test it because I don't have 7Zip but it could be that this programm is compressing the folder above normal and maybe Ghost reject it because it thinks is corrupted or something like that. You should check your settings to see if you can change the compression levels.

I only had the 0.5.3 so for the example I used it, but does not matter : the 0.5.7 file zipped is 893ko. Still an error. Here, have a link at the 0.5.7 file with the assets file : https://www.swisstransfer.com/d/ada7fd0b-6188-4512-856d-b35e0a91f9fc.

It raises this error : 
![image](https://user-images.githubusercontent.com/36224223/68227801-9ea18780-fff4-11e9-88b0-a3c6e9da83d8.png). When I try to upload the zip of the 0.5.7 version WITH the prism.js and prism.css. Otherwise, without the files, no problem runs smooth and works.


EDIT : What program do you use to edit ? Zip command line from Linux ? Windows utility ?

**Comment by D3473R** [comment]
I tested it with a Windows machine and it looks like a strange windows permission error.
https://gscan.ghost.org/ throws a permission denied error for me even after extraction and zipping again with 7zip.
You could use something like: https://hub.docker.com/r/kramos/alpine-zip/ to use it without a linux machine or vm.
