### ISSUE TITLE
Featured articles text display issue

### ISSUE THREAD

**Issue by ilovecats516** [eddiesigner/liebling#74]
Some photos don't work well with white text for the Featured article. Not sure how this could be fixed, but just mentioning it.

![Screen Shot 2019-11-04 at 4 39 26 PM](https://user-images.githubusercontent.com/30846409/68169630-c116a080-ff21-11e9-8abb-12670f709cf6.png)

**Comment by eddiesigner** [comment]
Sorry, I mistakenly overwritten the opacity of the background of the featured articles. It's fixed with the lates release:  https://github.com/eddiesigner/liebling/releases/tag/v.0.5.8

**Comment by ilovecats516** [comment]
Great, thanks.
