### ISSUE TITLE
[request] toggle button for dark mode

### ISSUE THREAD

**Issue by Jamelle-Boose** [eddiesigner/liebling#75]
Even though I have a dark theme set for my computer, the option to easily toggle between dark mode on/off from the theme itself would be useful.  :smile: 

- [Create A Dark/Light Mode Switch with CSS Variables](https://codepen.io/ananyaneogi/pen/zXZyMP)
- [Light and dark page toggle](https://codepen.io/tatimblin/pen/RMjaqb)

**Comment by eddiesigner** [comment]
This has been implemented in the latest version (0.5.9) 🌓
