### ISSUE TITLE
Switch to white theme - (First experience with Ghost)

### ISSUE THREAD

**Issue by Xenonstaforums** [eddiesigner/liebling#76]
Hi!
I really love this theme and It's one of the coolest themes I've seen. I really appreciate your work.
I have read closed issues but I couldn't solve the problem. Later I checked for my device's theme and it selected as Light theme. After that, I tried by editing the app.css but it's so difficult to find tags. What should I do? Also, Could I get csstag names for the shadow of article-cards on the main page?
Thank you!

**Comment by Xenonstaforums** [comment]
Oh, It's only happening when I use Brave browser. And still I have a problem. How does this dark theme work? 
Thank you!

**Comment by eddiesigner** [comment]
Currently the dark theme is shown when devices that support `@media (prefers-color-scheme: dark)` have the dark-mode enabled. If the device doesn't support that or if you have the dark mode turned off then the light theme is shown.

More info about this here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

But I don't understand yet what do you need exactly, do you want to disable the dark theme for your blog and just show the light theme? If you want to do that then please take a look on this:

https://twitter.com/_edev/status/1190724632556556288

**Comment by Xenonstaforums** [comment]
After reading this: [https://github.com/eddiesigner/liebling/issues/68](https://github.com/eddiesigner/liebling/issues/68)
I thought the dark theme depends on OS's default theme. I worried because of the Liebling theme was still black even though my default theme was light. After I found that my browser's theme selected as dark. Now I got it. (I think in the dark theme we can't see even shadows. can we?) That's why I tried to force light mode.

Thank you for your co-operation! =)

after referring to this: [https://github.com/eddiesigner/liebling/issues/62](https://github.com/eddiesigner/liebling/issues/62), I tried with my own colours... 

```
:root {
 --background-color: #243239;
 --primary-foreground-color: #ECEFF1;
 --secondary-foreground-color: #fff;
 --primary-subtle-color: #64FFDA;
 --secondary-subtle-color: #2A383F;
 --titles-color: #ECEFF1;
 --link-color: #64FFDA;
 --primary-border-color: #2A383F;
 --secondary-border-color: #243239;
 --article-shadow-normal: 0 0px 0px 30px rgba(0,0,0,0.5);
 --article-shadow-hover: 0 0px 0px 60px rgba(0,0,0,0.9);
 --transparent-background-color: rgba(27,38,43,1);
 --foter-background-color: #1f2a30
 --submenu-shadow-color-opacity: 0.55;
 --button-shadow-color-normal: rgba(10, 10, 10, 0.5);
 --button-shadow-color-hover: rgba(10, 10, 10, 0.5);
}
```

And I removed the secondary border of article-cards:


~~```border:1px solid var(--secondary-border-color);```~~


Not too darker, not too brighter. isn't it? :3 
Few screenshots:

<img src="https://user-images.githubusercontent.com/28010975/68609997-bdb08580-04dc-11ea-99bc-1e6d7dbd6922.png" width="300"> <img src="https://user-images.githubusercontent.com/28010975/68610028-ce60fb80-04dc-11ea-8fa7-e2521302ee7e.png" width="300">

<img src="https://user-images.githubusercontent.com/28010975/68610067-e9cc0680-04dc-11ea-8b22-9e4990b465fc.png" width="300"> <img src="https://user-images.githubusercontent.com/28010975/68610081-f2244180-04dc-11ea-82b1-bffa6b685de2.png" width="300">

![Annotation31](https://user-images.githubusercontent.com/28010975/68610089-f7818c00-04dc-11ea-8a50-77ed5e7c75f7.png)
