### ISSUE TITLE
feature post card failed to reset layout when rotating device

### ISSUE THREAD

**Issue by calvintam236** [eddiesigner/liebling#8]
![rotate](https://user-images.githubusercontent.com/6436149/57944431-d4f31b00-788b-11e9-86ac-6c1b9d1e79ae.PNG)

This happens when you rotate on a iPad.

**Comment by eddiesigner** [comment]
@calvintam236  Did you try with a real device? That doesn't happen on my phone, that only happen with the dev tools because I think when you "rotate" the layout there, the window doesn't trigger the resize event.

**Comment by eddiesigner** [comment]
I'll close this issue for now, please feel free of open it again if you needed.

**Comment by calvintam236** [comment]
![Screen Shot 2019-05-21 at 3 05 58 PM](https://user-images.githubusercontent.com/6436149/58133898-106a4e00-7bda-11e9-962f-bc7f9ceb3b94.png)
Firefox has the same problem as well. I think bigger screen width is needed to reproduce this problem.
BTW if you close it, I cannot reopen it..

**Comment by eddiesigner** [comment]
I think this is not a real problem, maybe also the Firefox dev tools don't trigger the resize event when you switch the layout, when you are inspecting the theme with those tools, you always can refresh the page. If this issue only happen with the dev tools then for me is not a real issue.

As I said, on my phone it works well when rotating, unfortunately I have not an iPad where I can test it.

**Comment by calvintam236** [comment]
![android emulator](https://user-images.githubusercontent.com/6436149/58194519-93db7c00-7c7a-11e9-9623-8c8dcc3bb175.PNG)

I can reproduce it on android emulator (with android studio) after rotating the device twice. When more rotations done, and width of the first post card is getting smaller.

![android emulator2](https://user-images.githubusercontent.com/6436149/58194602-d2713680-7c7a-11e9-9a80-0e7de8697b46.PNG)

Looks like some JS calculation is off.
Android Q (with android studio), Chrome

**Comment by eddiesigner** [comment]
But again it's not a real device, I've just tested it on an Android device and it works well 👍

**Comment by calvintam236** [comment]
What resolution did you test on? The emulator tests on 1024*576px. Emulator should be treated as real device because this is why it exists.

**Comment by eddiesigner** [comment]
I don't know, it was in some HTC phone but I'm pretty sure is not about resolutions. Emulators are there to test mobile apps (not websites really), I don't think people visit websites and play with them on emulators. If the slider works well on real devices, I don't think it's worth to spend a lot of hours trying to understand and fix this weird issue that only happens on emulators or dev tools.
