### ISSUE TITLE
How to remove tiny author logo on every post thumbnail ?

### ISSUE THREAD

**Issue by saravanks** [eddiesigner/liebling#80]

**Comment by eddiesigner** [comment]
You have two options:

You can find and remove the element `m-article-card__author` from the file `/partials/loop.hbs`: https://github.com/eddiesigner/liebling/blob/master/partials/loop.hbs#L15

Also find and remove the element `m-featured-article__author` from the file `/index.hbs`: https://github.com/eddiesigner/liebling/blob/master/index.hbs#L47

The other thing you can do is simply adding this css rule into the "Site Header Code Injection" section of your Ghost instance:

```html
<style>
.m-article-card__author,
.m-featured-article__author {
  display: none !important;
}
</style>
```

**Comment by saravanks** [comment]
Thank you !
