### ISSUE TITLE
How to build a multi-language site with Liebling

### ISSUE THREAD

**Issue by Xenonstaforums** [eddiesigner/liebling#82]
How to build a multi-language site with Liebling. I have read this article: [https://ghost.org/tutorials/multi-language-content/](https://ghost.org/tutorials/multi-language-content/)
There is a tutorial for the German language.
But I can't understand how to create templates for each collection according to that article.
This is the part I can't understand. Because I can't see HTML tag in the `index.hbs`

```
"Create templates for each collection"
Once your collections are in place, you'll need to create different templates for each collection and define html lang attributes in those templates, for example:

index.hbs
<html lang="en">

de.hbs
<html lang="de">

If you need further help creating a custom template, visit the theme documentation for more detailed information about working with the Ghost theme layer.

Finally, update your post template to ensure the correct template is used for each collection, for example:

"post.hbs"

{{#post}}
  {{#has tag="de"}}
    <html lang="de">
  {{else}}
    <html lang="en">
  {{/has}}
{{/post}} 
```
I'm waiting for a swift reply.

**Comment by eddiesigner** [comment]
This is not related to Liebling actually. That guide is very vague, I don't understand it fully neither.

I follow the recommendations and guidelines of theme development for Ghost and even follow the same structure as the default Ghost theme ([Casper](https://github.com/TryGhost/Casper)) so the only file where you can set the `lang` attribute is [here](https://github.com/eddiesigner/liebling/blob/master/default.hbs#L2).

It seems like they just forgot about the `default.hbs` template which inherits all these tags to the other templates (index, post, page, tag, etc.).

It's better if you try first adding multi-language support to the default Casper theme and then, if everything works, then replicate it with Liebling.

I would say you must ask for help in the [forum](https://forum.ghost.org/).
