### ISSUE TITLE
Support for members

### ISSUE THREAD

**Issue by XxPoNaGeXx** [eddiesigner/liebling#83]
Add support for memebrs ghost 3.0? 

I can see all paid posts even when logged out

**Comment by Xenonstaforums** [comment]
Check this out dude! [https://github.com/eddiesigner/liebling/issues/70](https://github.com/eddiesigner/liebling/issues/70)

**Comment by eddiesigner** [comment]
Duplicate of https://github.com/eddiesigner/liebling/issues/70
