### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by Xenonstaforums** [eddiesigner/liebling#84]
Hi! Could I use a custom font like Montserrat? Could you explain? Is it possible to use google fonts?

**Comment by eddiesigner** [comment]
To do that you have to follow these steps:

1. Clone or download this repository.

2. Change [line 34 of `default.hbs`](https://github.com/eddiesigner/liebling/blob/master/default.hbs#L34) file like this:

```js
google: { families: ['Montserrat:400,600,700&display=swap'] }
```

3. Change [line 10 of `src/sass/common/_global.scss`](https://github.com/eddiesigner/liebling/blob/master/src/sass/common/_global.scss#L10) file like this:

```css
font-family: 'Montserrat', Helvetica, Arial, sans-serif;
```

4. Install [Nodejs](https://nodejs.org/en/download/) and [npm](https://www.npmjs.com/get-npm)

5. Open a terminal and go to the `src` directory.

6. Run `npm install`.

7. Build the theme for production just by running `npm run production` (within the `src` directory)

8. Upload the file `liebling.zip` to your Ghost instance.

**Comment by mehrdad-shokri** [comment]
@eddiesigner what if the font isn't hosted on google fonts? how to load font files?
