### ISSUE TITLE
404 Error at /authors/

### ISSUE THREAD

**Issue by BraydenGirard** [eddiesigner/liebling#85]
Hello,

First off great theme! Thanks for all the hard work.

I am just having trouble getting my theme to show the authors page you have in the demo theme. Currently I have one author and I have added that author to a post.

If I add a a menu link to /authors/ it gives me a 404.

Thanks!

**Comment by BraydenGirard** [comment]
Just need the documentation :)

**Comment by xiaobaz** [comment]
How did you solve this @BraydenGirard ?

**Comment by eddiesigner** [comment]
@xiaobaz please check this out: https://github.com/eddiesigner/liebling/wiki/How-to-enable-the-Authors-page
