### ISSUE TITLE
Search not showing up in Ghost 3.0

### ISSUE THREAD

**Issue by BraydenGirard** [eddiesigner/liebling#86]
My menu does not have a search icon in it? Is this normal? Maybe I need to activate it somehow?

**Comment by tilenkavcic** [comment]
Check the docs over here: 
https://github.com/eddiesigner/liebling/wiki/How-to-enable-search

**Comment by BraydenGirard** [comment]
I didn’t even realize there were docs! thank you so much.
On Nov 15, 2019, 6:34 PM -0500, Tilen Kavčič <notifications@github.com>, wrote:

Check the docs over here:
https://github.com/eddiesigner/liebling/wiki/How-to-enable-search

**Comment by BraydenGirard** [comment]
Thanks worked great
