### ISSUE TITLE
PWA support would be great !

### ISSUE THREAD

**Issue by saravanks** [eddiesigner/liebling#87]
or at least help article in wiki would be nice

**Comment by saravanks** [comment]
or at least needed help article in wiki

**Comment by eddiesigner** [comment]
I think PWA support for web applications is important but not for blogs. The necessary code is not trivial, I don't think it's worth the work invested in something very few are going to use.

Also I think this should be a feature that Ghost has to include by default, it's a kind of feature that can't rely on a theme, it should be something that is part of the Ghost core.

If you still want to turn your blog into a PWA you can try this:

https://codeseo.io/node-ghost-and-progressive-web-apps-pwa/
