### ISSUE TITLE
layout .m-recommended-slider is wrong if there are no images

### ISSUE THREAD

**Issue by najcardboyz** [eddiesigner/liebling#89]
hi everyone, I like the liebling theme for my blog, there are only a few css errors in the .m-recommended-slider class if the post is without an image, like the following, the post title is truncated

![Screen Shot 2019-11-20 at 22 25 33](https://user-images.githubusercontent.com/1538699/69248141-a9f4d580-0be6-11ea-879e-fc70e005b4c6.png)

**Comment by eddiesigner** [comment]
I already fixed it, please download the latest version (0.6.2).
