### ISSUE TITLE
Theme is Broken

### ISSUE THREAD

**Issue by vamsi3001** [eddiesigner/liebling#93]
When loading the site with this theme, the styling is missing and found in the console that these files are missing from the theme directory.

assets/css/app.css
assets/js/manifest.js
assets/js/vendor.js
assets/js/app.js
assets/js/home.js
assets/js/manifest.js
assets/js/manifest.js

You can see the same in the screenshot below. 
<img width="1439" alt="Screenshot 2019-11-23 at 10 28 51" src="https://user-images.githubusercontent.com/13076901/69473711-4bde1300-0ddd-11ea-9749-ad1cc22688b1.png">

**Comment by oghie** [comment]
Do not clone from github. Just download from this [releases url](https://github.com/eddiesigner/liebling/releases)

**Comment by eddiesigner** [comment]
Please take a look to https://github.com/eddiesigner/liebling#download
