### ISSUE TITLE
Wrong horizontal scroll side in Recent article

### ISSUE THREAD

**Issue by Bodhiguard** [eddiesigner/liebling#95]
Hey there,

A friend of mine just noticed a weird behavior : the horizontal scroll on the Recent Article in the three dots menu is revert-side. If you scroll left, it goes left, which usually goes the opposite.

Indeed, the normal behavior on the phone is that if you scroll bottom to top on a phone, it goes down, well there if you scroll left to right it goes right instead of left (instead of making everything go right).

Any way to correct this ? Thanks you 👍

**Comment by eddiesigner** [comment]
What theme version do you have installed?
